arcus_zk.c
공인IP 환경에서 memcached 가 기동할 수 있도록 수정했습니다.
=> modification to be operating in the public ip

lqdetect.c
Rebased #17 to develop branch.
=> Uninitialized variable in lqdetect_dupcheck

include/memcached/types.h, memcached.c, memcached.h, thread.c
cmd_incr, cmd_decr stats 정보 추가
=> Refactor : update cmd_incr, cmd_decr stats

memcached.c, memcached.h, thread.c
UPDATE_INCR_DECR code tag 삭제 안된부분이있어서
함께 삭제하였습니다.
감사합니다~
=> Refactor : update cmd_delete stats.

items.c
SET_DELETE_NO_MERGE  code tag 추가한 뒤 주석처리하였습니다.
=> Refactor : update do_set_elem_traverse_fast() function.

include/memcached/types.h, items.c, items.h
BTREE_DELETE_NO_MERGE code tag 추가 후 주석처리하였습니다.
감사합니다!
=> Refactor : do_btree_elem_delete_fast() function.

memcached.c
=> Optimize tokenize_command() fucntion.

t/issue_163.t, t/issue_22.t
=> Fix unittest for long key support(maintain slabs_clsid)

.gitignore, INSTALL, configure.ac
The PR is a modification of the existing memcached
memcached/memcached@6b65e45
=> Add INSTALL file and automake improvements

doc/arcus-ascii-protocol.md, doc/arcus-basic-concept.md, doc/arcus-collection-concept.md, doc/arcus-item-attribute.md, doc/command-administration.md, doc/command-map-collection.md, doc/command-pipelining.md, engines/default/assoc.c, engines/default/assoc.h, engines/default/default_engine.c, engines/default/default_engine.h, engines/default/items.c, engines/default/items.h, engines/demo/demo_engine.c, engines/demo/demo_engine.h, include/memcached/engine.h, include/memcached/types.h, memcached.c, memcached.h, stats.c, stats.h, t/coll_mop_delete.t, t/coll_mop_get.t, t/coll_mop_insert.t, t/coll_mop_update.t, t/lib/MemcachedTest.pm, t/stats-detail.t, t/stats_prefixes.t, thread.c, topkeys.h
=> MAP_COLLECTION

memcached.c, t/noreply.t, t/verbosity.t
process_verbostiy_command 에서 noreply 옵션 제거 및 test 파일 수정
First reviewer
Final reviewer
=> Delete noreply option of verbosity and modify test file

memcached.c
@jhpark816 
getattr command에서 collection 확인 후 attribute가 추가되는데,
filter에 map을 추가하는 부분을 놓쳤습니다.
확인 부탁드립니다. 감사합니다.
=> MAP_COLLECTION: fix bug for add attr_data type filter

engines/default/default_engine.c, engines/default/default_engine.h, engines/demo/demo_engine.c, engines/demo/demo_engine.h, include/memcached/engine.h, include/memcached/types.h, memcached.c
engine_config struct 에 sticky ratio 변수 추가하였습니다.
First reviewer
Final reviewer
=> Add sticky_ratio value in engine_config struct

include/memcached/types.h, memcached.c
maxcollsize 를 제외한 나머지 2개의 configuration에 SETTING_LOCK 추가 하였습니다. 
First reviewer
Final reviewer
=> Add SETTING_LOCK

engines/default/items.h, memcached.c
setting stat을 보여주는 부분과,
주석에 map collection 놓친 부분 추가를 위한 PR입니다.
=> MAP_COLLECTION: add map in process_stat_settings

engines/default/items.c
=> Prohibition of bop zero len value incr/decr

doc/command-btree-collection.md, doc/command-list-collection.md, doc/command-map-collection.md, doc/command-set-collection.md, memcached.c, t/topkeys.t
=> Add error code processing that ENGINE_ENOTSUP

memcached.c
=> Refactor: get/set attr

t/coll_bop_mget_1.t, t/coll_bop_smget_1.t
=> Add unit test in btree mget, smget for use EFlag Filter

memcached.c
memlimit, sticky_limit 음수 입력에 대한 예외처리입니다.
memlimit을 음수처리를 하며 sticky_limit에서 잘못된 부분이 있어 같이 수정했습니다.
=> Refactor: prohibition memlimit, sticky_limit negative number

memcached.c
=> Fixed print format

arcus_zk.c
Reviewer
arcus zk module에서 zk info strucutre를 사용하도록 변경한 PR입니다.
관련된 부분도 함께 수정했습니다.
확인 요청 드립니다.
=> CLEANUP: refactoring arcus_zk for use zk structure

.travis.yml
Travis ci test 추가 관련 PR 입니다.
확인 요청 드립니다.
=> TEST: add travis ci test

engines/default/items.c
@jhpark816 @minkikim89 @MinWooJin 
기존 collection의 get 함수의 return type 변경한 PR입니다.
기존 uint32_t -> ENGINE_ERROR_CODE로 수정했습니다.
확인 부탁드립니다.
=> CLEANUP : change the return type of the collection get function

README.md
travis ci test status image 추가 관련 PR입니다.
현재 develop branch 기준으로 보이게 되어 있습니다.
=> TEST: add travis ci test status image in README

doc/command-administration.md
Fix typos on doc. calss -> class
=> Fix typos on doc. calss -> class

config/autorun.sh
https://github.com/naver/arcus/pull/24 와 같이 autorun.sh도 backquote 대신 $( ) 꼴을 사용하는 것이 좋을 것 같아서 pull request를 보냅니다.
(이 PR과 관련은 없지만 close된 다른 pull request를 보니 master branch 대신 develop branch에 pull request를 보내달라고 하셔서, master branch로 보냈던 PR은 close하고, 새로 PR을 보냅니다!)
=> Use $(STATEMENT) instead of legacy `STATEMENT`

config/autorun.sh
args에 대한 iteration을 위해서는 for문에서 $@ 대신 "$@"을 사용해야 하는 것 같습니다.
=> iteration for $@ -> "$@"

Makefile.am, engines/COMMON/mblock_allocator.c, engines/COMMON/mblock_allocator.h, engines/default/default_engine.c, engines/default/default_engine.h, engines/default/items.c, engines/default/items.h, engines/demo/demo_engine.c, include/memcached/engine.h, include/memcached/types.h, memcached.c, memcached.h
=> FEATURE : Add block allocator for more efficient memory management(task/eblock)

engines/default/default_engine.c, engines/default/items.c, engines/default/items.h, engines/demo/demo_engine.c, include/memcached/engine.h
=> CLEANUP : change the range type of bop gbp

arcus_zk.c, arcus_zk.h, doc/command-administration.md, include/memcached/types.h, memcached.c
@MinWooJin @jhpark816 
failstop 옵션에 대한 PR입니다.
config 명령어에 failstop on/off 추가했으며
rejoin의 경우 cluster rejoin이라는 명령어를 새로 만들었습니다.
=> FEATURE: failstop configuration

memcached.c
@jhpark816 
help command에 대한 추가가 빠져있어서
추가 했습니다.
=> CLEANUP: simple refactoring for help command

doc/protocol.txt
=> fix Typo: unsigner -> unsigned

arcus_zk.c
arcus_zk module 에서 zpath 변수에 대해
각 함수마다 local value로 쓰던 부분을
global value 하나로 공유해서 사용하도록 변경 했습니다.
@jhpark816 
확인 요청 드립니다.
=> CLEANUP: use global zpath value for sharing in the arcus_zk module

arcus_zk.c
sm_state_thread 만 global zpath 를 사용하기 위해
기존에 global zpath를 사용하던 부분을 local value로 변경 하고 length를 수정 했습니다.
@jhpark816 
확인 요청 드립니다.
=> CLEANUP: use local zpath value and change the length

arcus_zk.c
=> CLEANUP: increased MAX_SERVICECODE_LENGTH from 32 to 128

run_test.pl
echo 로 보여지는 engine 명을 좀 더 common 한 형태로 변경.
=> TEST : modified run_test.pl

arcus_zk.c
=> CLEANUP: move arcus_zk_log into arcus_create_ephemral_znode

engines/default/items.c, memcached.c, memcached.h, thread.c, topkeys.h
=> FEATURE: add STAT 'cmd_cas'

arcus_zk.c, engines/default/default_engine.c, engines/default/default_engine.h, engines/default/items.c, engines/default/items.h, include/memcached/engine.h, include/memcached/types.h
=> FEATURE: run automatic scrub stale when a new node is added

t/lib/MemcachedTest.pm
@jhpark816 
unit test blocking issue
https://github.com/jam2in/arcus-memcached-EE/issues/601
에 대한 PR 입니다.
확인 부탁드립니다.
=> TEST : fixed mem_cmd_is blocking issue

t/coll_bop_random_insert.bt, t/coll_lop_large_test.bt, t/coll_mop_large_test.bt, t/lib/MemcachedTest.pm, t/tlist/engine_default_b.txt
@jhpark816 
https://github.com/jam2in/arcus-memcached-EE/issues/650 관련 PR입니다.
list, map, btree에 대해서 big test를 작성하였습니다.
set test는 기존 t/coll_sop_unittest.t로 충분할 것 같아서 제외했습니다.
=> TEST : add big test(list, map, btree)

engines/default/slabs.c
free_avail_space reduction log가 ```verbose > 1```로 세팅되어 있을 때
출력되도록 수정 했습니다.
=> CLEANUP: add log verbose level check of free_avail_space reduction

engines/default/slabs.c
기존 동작은 100번의 slab allocate, free 요청이 수행되고 나서
space shortage level을 확인 했습니다.
memory가 작은 instance 의 경우 shortage level 을
확인하고, eviction을 시작하기 전에 이미 free space가
모두 소모되어 out of memory error를 return할 수 있습니다.
slab allocate, free 요청이 수행될 때 마다 space shortage level을
확인하여 level에 맞는 eviction 동작이 수행될 수 있도록 변경 했습니다.
=> CLEANUP: always check space shortage level

t/flush-prefix.t, t/tlist/engine_default_b.txt, t/tlist/engine_default_s.txt
flush_prefix test 추가를 위한 PR 입니다.
@jhpark816 
확인 요청 드립니다.
=> TEST: add flush_prefix test

README.md
Reviewer
README 파일에 지원가능한 Collection 리스트에 Map을 추가했습니다.
=> CLEANUP: add map description on README

include/memcached/types.h, lqdetect.c, lqdetect.h, memcached.c
reviewer
long query detection에 map collection을 추가하였습니다.
확인해주세요.
=> CLEANUP : add map at long query detection

include/memcached/types.h, lqdetect.c, lqdetect.h, memcached.c
reviewer
long query detection code를 refactoring 하였습니다.
확인해주세요.
=> CLEANUP: refactoring at long query detection

run_test.pl
travis ci test 에서 테스트 실패를 검출하지 못하는 문제를
수정 했습니다. 테스트 결과를 확인하여 성공이 아니면 exit 합니다.
@jhpark816 
확인 요청 드립니다.
=> FIX: travis ci test failure detection

arcus_zk.c
zk의 cache_server_mapping 노드에 hostname도 같이 검사할 수 있도록 추가했습니다.
1. cache_server_mapping/IP:PORT 검사
2. 1번 노드가 없으면 cache_server_mapping/HOSTNAME:PORT 검사
3. 2번 노드가 없으면 cache_server_mapping/IP 검사
4. 3번 노드가 없으면 cache_server_mapping/HOSTNAME 검사
5. 4번 노드가 없으면 종료
=> FEATURE: check cache_server_mapping with hostname

arcus_zk.c
proxy 사용관련 버그 수정입니다.
코드 흐름대로라면 원래
proxy 사용여부에 따라 hostip가 들어갈 위치에
proxy 사용이면 proxyip가, 아니라면 hostip가 들어가는게 맞지만
그러려면 proxyip를 보관하는 변수를 추가해야합니다.
제 생각으로는 실제 proxy 노드 역할을 하는 노드(arcus 노드가 아닌 연산을 입력받는 실제 proxy)가
예전 cache_server_mapping 등록 형태를 사용하지는 않을 것이기 때문에
backward compatibility이 필요없을 것이라 보고, proxy 사용시에는 해당 체크를 하지 않도록
코드를 수정해보았습니다.
=> FIX: incorrect ip checking when it is proxy mode

engines/default/cmdlogrec.c
bkey 정보를 출력하는 함수를 다른 곳에서도 사용할 수 있도록 변경.
Reviewer
=> [persistence] refactoring to make reusable function.

Makefile.am, engines/default/item_clog.c, engines/default/item_clog.h, engines/default/items.c, engines/default/items.h, include/memcached/types.h
Change log 생성을 위한 macro 추가 PR 입니다.
각 함수마다 틀만 만들어 놓은 상태이고,
생성 조건은 공통으로 들어가야 할 부분이라서 미리 만들어 놓았습니다.
@jhpark816 
확인 요청 드립니다.
=> FEATURE: add change log generation macro

engines/default/items.c, engines/default/items.h, include/memcached/types.h
기존에 EE 에 있던 collection element scan 기능을 범용적으로 사용할 수 있도록 default engine으로 옮김.
현재는 data snapshot, replication, migration 에서 element scan 기능이 필요함. 
Reviewer
=> FEATURE: scan element items

engines/default/cmdlogrec.h
nbytes field 크기를 uint32_t 로 변경.
Reviewer
=> [persistence] fix the size of nbytes.

engines/default/cmdlogrec.c
=> [persistence] fix the length of log record body

engines/default/assoc.c, engines/default/assoc.h
scan을 이용해 visited area 검사 함수 추가를 위한 PR 입니다.
@jhpark816 
확인 요청 드립니다.
=> FEATURE: added assoc_scan_in_visited_area() function

engines/default/cmdlogbuf.c
issue : https://github.com/naver/arcus-memcached/issues/272
- 외부 log record header write 코드 제거
- 다른 코드와 스타일 맞추기 위해 일부 refactoring
Reviewer
=> [persistence] remove duplicate header write code | refactor some code.

engines/default/default_engine.c
**관련 issue : https://github.com/naver/arcus-memcached/issues/268**
**기능 :** 
- check engine configuration.
</br>
@jhpark816 리뷰 부탁드립니다.
=> FEATURE: Check engine configurations.

engines/default/cmdlogrec.c
필요시에만 log record가 출력되도록 print define을 주석처리 하기 위한 PR 입니다.
=> [persistence] print log records only when debugging is required

engines/default/checkpoint.c, engines/default/default_engine.c
백업 디렉토리 설정 및 확인.
- data_path, logs_path 모두 NULL 인 경우
=> default 디렉토리를 ARCUS-DB 사용.(없는 경우 create)
- data_path, logs_path 모두 사용자가 설정한 경우
=> path 확인.(open)
- 둘 중 하나만 설정한 경우
=> ENGINE_FAILED.
@jhpark816 리뷰 부탁드립니다.
=> [persistence] check and set data & logs directory path

engines/default/items.c, engines/default/items.h, engines/default/mc_snapshot.c, engines/default/mc_snapshot.h
https://github.com/naver/arcus-memcached/issues/260 를 위한 PR 입니다.
snapshot module에 checkpoint mode를 추가했고,
간단한 추가라서 따로 code tag는 넣지 않았습니다.
@jhpark816 
확인 요청 드립니다.
=> [persistence] added checkpoint mode in snapshot module

engines/default/items.c
https://github.com/naver/arcus-memcached/issues/252 관련 PR 입니다.
향후 use_persistence가 향후 dynamic 변경이 가능할 수 있으므로
waiter free 조건을 변경 했습니다.
@jhpark816 
확인 요청 드립니다.
=> [persistence] refactoring related to waiter free

engines/default/checkpoint.c, engines/default/cmdlogbuf.c, engines/default/cmdlogbuf.h
https://github.com/naver/arcus-memcached/issues/204 명령로깅 파일 선택 기능 구현을 위한 cmdlog file관련 리팩토링 PR 입니다.
next_fd를 추가했고, 기존 file open, close 부분을 수정 했습니다.
@jhpark816 
확인 요청 드립니다.
=> [persistence] refactoring related to cmdlog file

engines/default/items.c
기존 함수 중 collection struct create 부분에서
waiter 관련 코드가 빠져있어서 추가 했습니다.
@jhpark816 
확인 요청 드립니다.
=> [persistence] added waiter in collection struct create

engines/default/checkpoint.c, engines/default/checkpoint.h, engines/default/cmdlogmgr.c, engines/default/default_engine.c
https://github.com/naver/arcus-memcached/pull/288#discussion_r321103514
checkpoint init 을 cmdlog_mgr_init()에서 수행.
@jhpark816 리뷰 부탁드립니다.
=> [persistence] init checkpoint in cmdlogmgr

engines/default/checkpoint.c
잘못된 경로를 unlink 하고 있어서 수정하였습니다.
=> [persistence] fix wrong file path.

engines/default/cmdlogbuf.c
checkpoint file set이 없는 상태에서 구동 될 경우,
처음 log file을 checkpoint를 통해 생성하도록 되어있습니다.
이로인해 cmdlogbuf module의 checkpoint complete 동작이 맞지 않아
처음 log file 생성을 위한 checkpoint(```log_file.next_fd == -1```)는
complete 동작을 수행하지 않도록 수정 했습니다.
@jhpark816 
확인 요청 드립니다.
=> [persistence] fix error at first checkpoint

.travis.yml, README.md
coverage test를 enable 시키기 위한 PR 입니다.
Coverage Status를 표시하는 badge를 README에 추가 했습니다.
@jhpark816 
확인 요청 드립니다.
=> TEST: add coverage test badge

engines/default/items.c, engines/default/mc_snapshot.c
=> [persistence] fix things related to log.

engines/default/checkpoint.c, engines/default/mc_snapshot.c, engines/default/mc_snapshot.h
get checkpoint time from snapshot file name.
=> [persistence] get checkpoint time from snapshot file name.

engines/default/default_engine.c, engines/default/default_engine.h, engines/default/items.c, engines/default/items.h, include/memcached/types.h, memcached.c, memcached.h
scrub count 설정 기능 추가 커밋입니다.
내부에서 CACHE_LOCK을 잡고 설정하는데 이 부분이 꼭 필요한지는 의문이네요.
=> FEATURE: add scrub_count config command

engines/default/cmdlogrec.c, engines/default/cmdlogrec.h, engines/default/mc_snapshot.c
issue : https://github.com/naver/arcus-memcached/issues/318
log record rename(snapshot tail -> snapshot done).
=> [persistence] log record rename(snapshot tail -> snapshot done).

engines/default/cmdlogrec.c
issue : https://github.com/naver/arcus-memcached/issues/310 
lrec_write_to_buffer() 와 lrec_redo_from_record() 에서 공용으로 lrec_XXX_print()를 사용하기 위해
lrec_XXX_print() 에서 key, value 출력시 body->data 필드를 사용해서 출력하도록 변경.
=> [persistence] use body->data field in lrec_XXX_print().

engines/default/cmdlogrec.c
flags 값을 그대로 보여주는 것보단 human readable 값을 보여주는 것이 나아보입니다.
=> [persistence] print flags using htonl() for human readable.

engines/default/cmdlogrec.c
=> [persistence] fixed typo.

engines/default/cmdlogrec.c
fixed not setting attr.maxbkeyrange.len.
=> [persistence] fixed not setting attr.maxbkeyrange.len.

engines/default/default_engine.c, engines/default/default_engine.conf
persistence 에서 사용될 snapshot, log file path 는 사용자가 반드시 default_engine.conf 에 설정을 하도록 변경하였습니다.
=> [persistence] backup path must be set in conf file.

engines/default/mc_snapshot.c
snapped 정보가 반영되지 않는 문제를 수정하였습니다.
=> [persistence] incremented snapped item count.

engines/default/cmdlogmgr.c, engines/default/items.c
Use TLS manner in waiter to avoid holding cache lock.
=> [persistence] Use TLS manner in waiter to avoid holding cache lock.

engines/default/checkpoint.c, engines/default/cmdlogbuf.c, engines/default/mc_snapshot.c, include/memcached/types.h
Refactored log messages about thread.
스레드 생성, 시작, 중지 시에 메세지를 출력합니다.
=> [persistence] Refactored log messages about thread.

engines/default/checkpoint.c, engines/default/cmdlogbuf.c, engines/default/cmdlogmgr.c
Refactored the checkpoint and cmdlogbuf code.
=> [persistence] Refactored the checkpoint and cmdlogbuf code.

engines/default/cmdlogbuf.c
#333 persistence 에서 flush_all flag가 true일 때,
마지막 flush queue 내용을 flush 하고 handling 하기 위해 last_flush_flag를 두고 사용 했습니다.
flush_all flag가 true이면, fend pointer를 증가시키는 방법으로
last_flush_flag를 제거하기 위한 PR 입니다.
@jhpark816 
확인 요청 드립니다.
=> [persistence] remove last_flush_flag for refactoring

engines/default/cmdlogbuf.c, engines/default/mc_snapshot.c
현재 복구 모듈에서 로그 레코드 재수행을 실패하면 즉각 엔진을 종료합니다.
한 예로 복구 과정에서 expire 또는 evict 로 인해 아이템이 제거되면,
unlink, element command, setattr 재수행 시에 ENGINE_ENOENT 이 발생하여 복구를 하지 못합니다.
OOM 으로 인해 재수행이 실패된 경우가 아니라면,
복구 동작을 중단시키지 않고 에러 메세지만 출력해준 후 다음 로그 레코드를 복구하도록 합니다.
=> [persistence] Didn't stop reapplying log records unless it failed by OOM

engines/default/checkpoint.c, engines/default/cmdlogbuf.c, engines/default/cmdlogmgr.c
group commit module 리팩토링 작업입니다. 
다른 persistence module 과 코드 스타일을 맞추기 위한 변경이 있습니다.
=> [persistence] Declared group commit thread state as volatile.

CONTRIBUTING, CONTRIBUTING.md, t/whitespace.t
ARCUS-memcached 컨트리뷰션을 위한 CONTRIBUTING.md 수정을 위한 PR 입니다.
기존 CONTRIBUTING 파일은 제거 했고, markdown format으로 관리하기 위해 md 파일로 변경 했습니다.
CONTRIBUTING.md 에는 아래와 같은 내용이 포함되었습니다.
- 컨트리뷰션 방법 (CLA)
- 문의 및 토론 방법
- 개발 워크플로우
- 스타일 가이드
@jhpark816 
확인 요청 드립니다.
=> DOC: include contribution process documentation

engines/default/cmdlogrec.c
issue : https://github.com/naver/arcus-memcached/issues/286
아이템의 expire time 값은 server-start-relative time 으로 저장되어 있어서
이 값을 그대로 기록하고 복구하면, 재시작 시에는 엔진 시간이 0부터 시작하므로, 맞지 않습니다.
따라서 로깅 시와 복구 시에 expire time representation 을변환합니다.
**로깅 시(GET_LOG_TIME) : relative -> absolute**
- current unix time 과 아이템의 TTL(exptime - engine time)을 더해서 기록합니다.
- absolute unix time 으로 기록하기 때문에 기록된 time 보다 뒤에 엔진이 재시작 되면, 
해당 아이템의 복구는 skip 됩니다.
**복구 시(GET_REDO_TIME) : absolute -> relative**
- engine time과 아이템의 TTL(exptime - current unix time)을 더해서 복구합니다.
@jhpark816  검토 부탁드립니다.
=> [persistence] Logged expire time with absolute unix time.

engines/default/cmdlogrec.c
do_construct_item_attr() 함수 refactoring을 위한 PR 입니다.
memcpy src pointer와 size를 넘겨 함수 내에서 계산하는 방식에서,
src pointer를 계산해서 위치만 넘기는 방식으로 변경 했습니다.
@jhpark816 
확인 요청 드립니다.
=> [persistence] simple refactoring of construct_item_attr

engines/default/cmdlogbuf.c
https://github.com/naver/arcus-memcached/issues/366 이슈에 대한 수정입니다.
sync logging 최적화 작업 진행 중에 관련성이 있고 작업이 작아보여서 우선적으로 작업했습니다.
리뷰 부탁드립니다.
=> CLEANUP: remove log_file prev_fd

engines/default/item_clog.c, engines/default/item_clog.h, engines/default/items.c
#255 #259 
btree element delete change log를 기록하기 위한 방법으로,
logical delete를 추가하기 위해 필요한 macro와 interface
변경을 위한 PR입니다.
@jhpark816 
확인 요청 드립니다.
=> FEATURE: add generate btree elem delete logical clog

engines/default/cmdlogrec.c, engines/default/items.c
issue https://github.com/naver/arcus-memcached/issues/404 에 대한 PR입니다.
@MinWooJin 리뷰 요청드립니다.
=> CLEANUP: decrease where refcount was increased.

engines/default/cmdlogbuf.c
#415 관련 PR입니다.
comlog_complete_dual_write 함수 로직 중
buffer 부분과 file 부분을 분리하여 함수로 처리하도록 수정 했습니다.
@SuhwanJang @jhpark816 
확인 요청 드립니다.
=> [persistence] cleanup cmdlog_complete_dual_wirte function

t/coll_bop_maxbkeyrange.t, t/tlist/engine_default_b.txt, t/tlist/engine_default_s.txt
binary bkey의 maxbkeyrange 동작을 검증하는 테스트입니다.
bkey의 길이가 같은 경우, 다른 경우에 각각에 대해 smallest_trim과 largest_trim 동작을 모두 검증합니다.
=> TEST: add test for verifying binary bkey OUT_OF_RANGE response

README.md, doc/compilation_faq.md
- compilation FAQ 문서를 추가하였습니다.
- PR 반영되었을 때의 모습 참고 : https://github.com/SuhwanJang/arcus-memcached/tree/develop
=> DOC: added compilation FAQ page.

engines/default/cmdlogbuf.c
issue:https://github.com/naver/arcus-memcached/issues/431 의 PR 입니다.
=> [persistence] refactoring cmdlog_file_sync()

doc/command-administration.md
stats 명령에서 나오는 통계 정보를 모두 추가했습니다.
=> DOC: update document about stats

cluster_config.c
hash collision이 일어날 경우 syslog에 로깅하도록 코드 추가했습니다.
=> CLEANUP: do logging when hash collision ouccurs

engines/default/default_engine.c, engines/default/default_engine.h, include/memcached/types.h, memcached.c
max_element_bytes 설정을 엔진 안에서 하도록 합니다.
@MinWooJin 리뷰 요청드립니다.
=> CLEANUP: set max_element_bytes config in engine.

config_parser.c, include/memcached/config_parser.h
config parser 모듈에 uint32_t 타입을 추가하였습니다.
=> CLEANUP: added uint32_t datatype in config_parser.

engines/default/item_clog.c, engines/default/item_clog.h, engines/default/items.c
collection element delete 에서 clog의 범위를 표현하기 위한
ELEM_DELETE_BEGIN, ELEM_DELETE_END clog 추가 PR 입니다.
@jhpark816 
확인 요청 드립니다.
=> FEATURE: add BEGIN, END clog to indicate clog range

doc/command-administration.md
config 명령으로 변경할 수 있는 설정이 누락되어 있어 추가합니다.
=> DOC: add description about config command

doc/command-btree-collection.md, doc/command-list-collection.md, doc/command-map-collection.md, doc/command-set-collection.md
콜렉션 문서에 STORED가 STROED로 잘못 입력되어 있어 수정했습니다.
=> DOC: fix typo in collection documents

doc/command-key-value.md, include/memcached/types.h, memcached.c, memcached.h, t/lib/MemcachedTest.pm, t/mdelete.t, t/tlist/engine_default_b.txt, t/tlist/engine_default_s.txt
지금까지의 mdelete 작업입니다.
STAT 함수 관련 리팩토링들이 적용이 되어 있지 않아 유닛 테스트에서 오류가 발생했습니다. 수정후 PR 합니다.
=> FEATURE: add multi delete feature

doc/command-key-value.md
=> DOC: add detailed descrption for kv response

t/coll_pipeline_general.t
[c 클라이언트 이슈](https://github.com/naver/arcus-c-client/issues/89) 해결 도중 
서버에 PIPE_ERROR command overflow 결과를 확인하는 테스트 케이스가 없다는 걸 알게 되어 추가했습니다.
=> TEST: add pipe overflow test

doc/ap01-arcus-telnet-interface.md, doc/ch00-arcus-ascii-protocol.md, doc/ch01-arcus-basic-concept.md, doc/ch02-collection-items.md, doc/ch03-item-attributes.md, doc/ch04-command-key-value.md, doc/ch05-command-list-collection.md, doc/ch06-command-set-collection.md, doc/ch07-command-map-collection.md, doc/ch08-command-btree-collection.md, doc/ch09-command-pipelining.md, doc/ch10-command-item-attribute.md, doc/ch11-command-administration.md
파일 이름에 챕터를 붙이고 일부 문서의 챕터를 다시 붙였습니다.
바뀐 파일 이름에 맞게 문서 링크를 수정하였습니다.
=> DOC: divided docs into chapters

doc/ap01-arcus-telnet-interface.md, doc/ch00-arcus-ascii-protocol.md, doc/ch01-arcus-basic-concept.md, doc/ch02-collection-items.md, doc/ch03-item-attributes.md, doc/ch04-command-key-value.md, doc/ch08-command-btree-collection.md, doc/ch09-command-pipelining.md, doc/ch10-command-item-attribute.md, doc/ch11-command-administration.md
=> DOC: Capitalize ARCUS

doc/ch03-item-attributes.md, doc/ch11-command-administration.md
collection 외의 문서에도 #498 과 같은 문제가 있어 수정했습니다.
=> DOC: fix indentation of list items

doc/ch06-command-set-collection.md
=> DOC: fix wrong link

CONTRIBUTING.md
=> Added some information about contributing to CONTRIBUTING.md

engines/default/default_engine.c, engines/default/items.c, engines/default/items.h, engines/demo/demo_engine.c, engines/demo/dm_items.c, engines/demo/dm_items.h, include/memcached/engine.h, include/memcached/types.h, memcached.c
Issue : https://github.com/naver/arcus-memcached/issues/489
`make test` PASS 하였습니다.
=> IMPROVE: do not increase the refcount when allocate an hash_item.

engines/default/cmdlogbuf.c
fix typo : positon -> position
=> [persistence] fix typo

arcus_zk.c
=> CLEANUP: fix typo

include/memcached/types.h, memcached.c, t/mgets.t, t/tlist/engine_default_b.txt, t/tlist/engine_default_s.txt
- mgets 명령을 위해 기존 mget protocol 형태를 기반으로 함수 호출하도록 개발을 진행하였습니다.
- 추가된 mgets 명령어를 테스트하기 위한 테스트 코드를 추가하였습니다.
=> FEATURE: added mgets command

doc/ch04-command-key-value.md
- mgets 명령 설명을 ch04-command-key-value.md 에 추가하였습니다.
=> DOC: fix ch04-command-key-value.md mgets info

engines/default/item_base.c
=> CLEANUP: fix typo. LUR => LRU.

doc/ch11-command-administration.md
@jhpark816 @SuhwanJang 
[persistence] Persistence 설정 및 상태 정보를 조회하는 stats persistence 명령 개발 ( issue : #555 )
persistence stats와 관련하여 설명 추가하였습니다.
=> DOC: add description for persistence stats

doc/ch03-item-attributes.md, doc/ch05-command-list-collection.md, doc/ch06-command-set-collection.md, doc/ch07-command-map-collection.md, doc/ch08-command-btree-collection.md
**bop create unreadable attribute 사용 에러** https://github.com/naver/arcus-memcached/issues/566
collection create/insert 명령 설명에 unreadable 지정 설명을 추가하였습니다.
=> DOC: added unreadable description.

engines/default/assoc.c
해시테이블 확장 시간을 좀 더 단축시키도록 재분배 버켓 개수를 4개로 증가하였습니다.
=> IMPROVE: increased redistribute bucket count.

engines/default/item_base.c
=> CLEANUP: replace magic numbers with constants

arcus_zk.c
zk_reconfig auto enable 기능을 추가하였습니다.
- 현재는 캐시 서버의 zk_reconfig 설정을 다시 활성화할 수 있는 방법이 없어
- 캐시 서버가 연결된 ZK 가 3.4 => 3.5 로 바뀐 경우 재구동하여 zk_reconfig 를 활성화시키는 수 밖에 없습니다.
기능 설명입니다.
- 주키퍼 서버와 재연결이 된 경우 (ZK down or reconfig 수행 등으로 인해) ZK session event 가 발생되고,
- 해당 event를 처리하는 global zk watcher (arcus_zk_watcher) 에서 zk config znode 를 확인하여 zk_reconfig 활성화시킵니다.
=> FEATURE: supported zk_reconfig auto enable feature.

memcached.c
help 명령 결과에서 stats zookeeper 출력을 scrub 위에 하도록 수정하였습니다.
=> CLEANUP: relocated stats zookeeper code.

arcus_zk.c
issue: https://github.com/jam2in/arcus-memcached-EE/issues/913#issuecomment-822375529
enterprise 동작과의 호환성을 위해 sm_init()은 원래 위치인 arcus_check_server_mapping() 이후에 수행하고, 이와 연관된 reconfig 로직을 일부 수정하였습니다.
- arcus_zk_watcher()에서는 arcus_conf.init == true인 경우만 zk_reconfig 검사
- sm_init() 수행 직후 그리고, arcus_conf.init = true 설정 전에 arcus_check_zk_reconfig_enabled() 수행
- zk_reconfig = true이면, sm_info.request.update_zkconfig = true 설정
enterprise 정상 동작 여부는 확인하였습니다.
=> FIX: do sm_init() after arcus_check_server_mapping().

engines/default/items.c
Too many "flush prefix" message 발생 (jam2in/arcus-works#285) 관련 PR 입니다.
사전에 상의했던 내용과 같이 T분에 N개의 flush prefix log 가 출력되도록 구현하였습니다.
현재 10분에 최대 10개의 flush prefix log 가 출력되도록 설정하였습니다.
=> FEATURE: add flush prefix message compact feature

doc/ch01-arcus-basic-concept.md
automatic scrub feature 설명을 추가하였습니다.
preview : https://github.com/SuhwanJang/arcus-memcached/blob/develop/doc/ch01-arcus-basic-concept.md
=> DOC: added automatic scrub feature explanation.

engines/default/items.c
=> CLEANUP: removed double semicolon

cmdlog.c, cmdlog.h, memcached.c
command log 코드 리팩토링 및 일부 수정하였습니다.
=> CLEANUP: refactored command log code

t/keyscan.t, t/lib/MemcachedTest.pm, t/tlist/engine_default_b.txt, t/tlist/engine_default_s.txt
=> TEST: add keyscan test

doc/ch11-command-administration.md
keyscan 명령 설명 문서를 추가하였습니다.
preview : https://github.com/SuhwanJang/arcus-memcached/blob/suhwan/scan/doc/ch11-command-administration.md#keyscan-%EB%AA%85%EB%A0%B9
=> DOC: added keyscan document.

engines/default/items.c, include/memcached/types.h, memcached.c
KEY_MAX_LENGTH 값에 의존하고 있는 코드를 최근에 변경된 값에 맞게 수정하였습니다.
=> CLEANUP: KEY_MAX_LENGTH value has been reduced.

doc/ap01-arcus-telnet-interface.md, doc/ch00-arcus-ascii-protocol.md, doc/ch01-arcus-basic-concept.md, doc/ch02-collection-items.md, doc/ch03-item-attributes.md, doc/ch04-command-key-value.md, doc/ch05-command-list-collection.md, doc/ch06-command-set-collection.md, doc/ch07-command-map-collection.md, doc/ch08-command-btree-collection.md, doc/ch10-command-item-attribute.md, doc/ch11-command-administration.md
ARCUS-Memcached 문서 시스템에서 수정한 사항들 반영하였습니다.
- 오타 및 비문 수정
- outdated된 code 예시 수정
- 리스트를 표로 변경
=> Updated ARCUS-MEMCACHED Docs

lqdetect.c, lqdetect.h, memcached.c
=> CLEANUP: refactored lqdetect code.

memcached.c
pipe_response_save() 에서는 pipe 와 관련된 데이터만 설정하고, 밖에서 noreply 변경하도록 수정하였습니다.
=> CLEANUP: change noreply the outside of pipe_response_save().

t/coll_pipeline_general.t
이번에 수정한 pipeline bug 에 대한 테스트 케이스를 추가하였습니다.
pipeline bug fix 이전 버전에서 `make test` 시 :
- pipe error 이후 보낸 요청이 swallow 되어 socket timeout 동안 응답이 오지 않아 failed.
```
./t/nested_prefix.t ............... ok
./t/keyscan.t ..................... ok
./t/coll_pipeline_general.t ....... Timeout.. killing the process
./t/coll_pipeline_general.t ....... 3/3
./t/coll_pipeline_general.t ....... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests
Test Summary Report
-------------------
./t/whitespace.t                (Wstat: 512 Tests: 290 Failed: 2)
Failed tests:  199, 290
Non-zero exit status: 2
./t/coll_pipeline_general.t     (Wstat: 256 Tests: 3 Failed: 1)
Failed test:  3
Non-zero exit status: 1
Files=95, Tests=145638, 642 wallclock secs ( 8.97 usr  0.84 sys + 28.82 cusr  4.50 csys = 43.13 …
```
=> TEST: added pipeline test case of swallowing normal data issue.

engines/default/default_engine.c
default_keyscan() 함수에서 for문이 정상적으로 동작하지 않을 수 있는 점을 수정했습니다.
=> INTERNAL: Fix loop count bug in default_keyscan.

memcached.c
keyscan 명령어 실행 시 header 문자열이 로컬 변수로 있는 것을 동적 할당으로 바꾸었습니다.
=> INTERNAL: Move keyscan header memory space from stack to heap.

doc/ch11-command-administration.md, engines/default/default_engine.c, engines/default/prefix.c, engines/default/prefix.h, include/memcached/engine.h, include/memcached/types.h, memcached.c, memcached.h, t/lib/MemcachedTest.pm, t/prefixscan.t, t/tlist/engine_default_b.txt, t/tlist/engine_default_s.txt
`scan prefix <cursor> [count <count>] [match <pattern>]` 명령어를 추가했습니다.
=> FEATURE: Add prefixscan command.

doc/ch00-arcus-ascii-protocol.md, doc/ch01-arcus-basic-concept.md, doc/ch11-command-scan.md, doc/ch12-command-administration.md, memcached.c
https://github.com/naver/arcus-memcached/pull/640
위에서 논의된 사항으로, scan 명령어를 scan이라는 새로운 집합으로 구분하여 document 변경과 help command 변경을 수행했습니다. branch 이름을 변경하면서 새로운 PR을 올리게 되었습니다.
=> DOC: Add scan command document and help scan command.

memcached.c
- #650 
- jam2in/arcus-hubble-v3#319
- jam2in/arcus-memcached-EE#1038
- `stats prefixes item|operation` 명령이 제거됩니다.
해당 명령을 지원하지 않는 캐시 노드에 사용하는 경우 에러 응답이 아닌
`stats prefixes`의 결과를 응답하기 때문에 문제가 생길 수 있습니다.
- `stats prefixlist item|operation` 명령이 추가됩니다.
이전 `stats prefixes item|operation` 명령과 동일하게
prefix 목록을 지정하는 경우 해당 prefix에 대한 item or 명령 관련 stats 응답하며
prefix 목록 없이 사용하는 경우 전체 prefixes에 대한 stats 응답합니다.
=> FEATURE: Add "stats prefixlist" command

arcus_zk.c
- jam2in/arcus-works#355
zk dynamic config 문자열로부터 zk host string을 가져오는 로직이 변경됩니다.
- 기존: `;` 뒤의 문자열을 host string으로 사용
- 신규
- 조건에 따라 ip와 port 조합하여 사용
- ip
- `;` 뒷부분이 `ip:port` 형태인 경우
- ip가 `0.0.0.0` 또는 `127.0.0.1`인 경우: 앞부분 ip 사용
- 그 외 경우: 해당 ip 사용
- `;` 뒷부분이 ip 없이 port만 있는 경우: 앞부분 ip 사용
- port: `;` 뒤의 port 사용
=> FIX: Get valid connect string from dynamic config

memcached.c
pipelining 종료 시 관련 값을 초기화하기 위한 `pipe_state_clear(conn *c)`가 추가됩니다.
=> INTERNAL: Add pipe_state_clear()

arcus_zk.c
- jam2in/arcus-works#363
아래 조건을 모두 만족하는 경우 dynamic reconfig 기능을 비활성화합니다.
- `,`으로 나눈 token이 1개
- `inet_aton()`이 실패
- host addr list의 크기가 2 이상
=> INTERNAL: Disable reconfig when domain name given

arcus_zk.c
- jam2in/arcus-works#362
`arcus_zoo_set_servers()` 함수가 추가됩니다.
- lock을 잡고 동작합니다.
- `zoo_set_servers()`를 호출합니다.
- `main_zk->ensmeble_list`를 설정합니다.
=> INTERNAL: Add arcus_zoo_set_servers()

doc/ch03-item-attributes.md
* maxbkeyrange의 부족한 설명을 보충하였습니다.
=> DOCS: Edit maxbkeyrange document.

memcached.c
- jam2in/arcus-works#420
`getaddrinfo()` 결과 중 하나 이상의 주소가 이미 사용중인 경우 구동 실패로 판단하여 프로세스를 종료하도록 변경합니다.
`listen()` 성공 시 해당 주소 정보를 남기는 info 로그를 추가합니다.
=> FIX: Terminate the process if any address already in use

memcached.c
문제가 있던 해당 로그에 대하여 time interval(60초) 내의 발생 회수를 기록하여 이후의 시간에 한번에 출력하도록
변경되었습니다.
시간 기록 및 로그 출력은 '최초 발생' 또는 '이전 기록 시간에서 INTERVAL 시간이 지난 이후 발생했을 때' 입니다.
기록되는 형식은 아래와 같습니다.
Too many open connections (maxconns) (Previous {$count} logs occured during {$elapsed} secs) 
jam2in/arcus-works#430
=> FIX: summarize log message occured frequently

memcached.c
(해당 PR은 프로토콜 모듈화와 일부 관련이 있습니다.)
발견된 버그 사항은 아래와 같습니다.
1. UDP 헤더 구성에 동적으로 할당되는 hdrbuf에 대하여 free 구현부가 없습니다.
(이전에 언급한 바와 같습니다.)
#675
2. 바이너리 프로토콜 구현부에서 msghdr 동적할당 실패 시 클라이언트에
에러 메시지가 전달되지 않습니다.
바이너리 프로토콜의 경우 ```add_msghdr```가 ```try_read_command```에서 호출되며,
해당 위치에서 ```return 0```을 하게 될 경우 ```conn_closing```으로 넘어가게 되어
```out_string```을 통해 메시지를 구성해도 클라이언트로 전달되지 않습니다.
```c
if (add_msghdr(c) != 0) {
out_string(c, "SERVER_ERROR out of memory");
return 0;
}
```
ASCII 프로토콜의 경우 ```add_msghdr```가 ```protocol_command```에서
수행되며, 실패시 함수 종료 후 ```try_read_command```에서 return 1을 반환하여
```conn_write``` 상태로 변경됩니다.
```c
if (add_msghdr(c) != 0) {
out_string(c, "SERVER_ERROR out of memory preparing response");
return;
}
```
변경된 사항은 다음과 같습니다.
1. hdrbuf의 경우 conn_closing시 호출되는 conn_cleanup에서 해제시킵니다.
2. 바이너리 프로토콜 또한 …
=> FIX: Fix possible problems in UDP and binary protocol

memcached.c
UDP 프로토콜에서 유효하지 않은 헤더 처리 시
출력되지 않는 메시지에 관한 수정입니다.
jam2in/arcus-works#439
=> FIX: Fix a message that is not trasmitted in UDP protocol

arcus_zk.c, engines/default/item_base.c, engines/default/slabs.c, memcached.c
verbose 조건과 log level을 맞추기 위한 PR 입니다.
현재 이슈에 올린 로그에 대해서만 레벨을 조정했고,
해당 로그들 중 INFO 이상인 경우 조건문을 제거했습니다.
jam2in/arcus-works#436
=> FIX: Modify mismatched levels between log and verbose

memcached.c
- jam2in/arcus-works#444
- jam2in/arcus-works#442
바이너리 프로토콜에서 발생할 수 있는 버그에 대한 픽스 PR입니다.
주요 사항은 3가지 입니다.
->  해당 메시지를 현재 사용중인 프로토콜에 따라 write_bin_packet을 사용하게끔 조건문을 추가했습니다.
제가 살펴본 바로는 msghdr 구성 실패 가능성이 없다고 생각합니다.
- connection 시작 시 conn 구조체에 10개의 msghdr를 사전에 할당합니다.
- msghdr realloc을 실패해도 기존 공간은 유지합니다.
- out_string, 바이너리 헤더 구성 둘다 msghdr 0번을 덮어씌웁니다.
(즉, 최소 10개의 공간이 있는 상황에서 0번만을 사용하므로 실패할 가능성이 없다고 생각합니다.)
- out_string 또한 msghdr을 구성합니다.
(실패 가능성이 없다고 생각하나 바이너리 헤더에서 실패했다면 out_string 또한 실패할 가능성이 큽니다.) 
- out_string은 바이너리 헤더를 덮어버리고, ASCII 문자열만 출력합니다.
(가장 큰 제거 이유입니다.)
=> FIX: Fix bugs in binary protocol

memcached.c
- jam2in/arcus-works#468
item value에 대한 iov를 구성하기 위해
ASCII에서 호출하는 `add_iov_h/einfo_value_all(conn *c, eitem_info *einfo)`  함수, 
Binary에서 호출하는 `add_iov_h/einfo_value_some(conn *c, eitem_info *einfo, int length)` 함수를 통합합니다.
두 함수는 기능상 같으며, binary의 경우 item info에 저장된 value 중 끝의 
`\r\n` 을 제외하기 위해 함수명이 조금 다르고, length 인자가 추가되었습니다.
리팩토링시 갖게되는 이점은 다음과 같습니다.
- 기능이 공통되는 함수를 하나로 합침으로써 코드라인 수 감소
- 분리되어 있어 이해가 힘들었던 함수를 합침으로써 직관적으로 함수의 기능을 알 수 있게 됨
> assert(c->protocol == binary_prot) 의 확실한 보장에 대한 설명
memcached에서는 3가지의 프로토콜을 사용합니다. (`ascii`, `binary`, `negotiating`)
(udp의 경우 )
memcached를 구동할 때에 프로토콜(option : `B`)을 `ascii` 또는 `binary`로 주어질 경우
모든 connection 은 해당 프로토콜로 지정되지만 `auto`로 줄 경우 `negotiating`로 지정됩니다.
`negotiating`의 프로토콜은 connection에 따라 클라이언트에서 처음 명령어를 보냈을 때 `ascii` 또는 `binary`로 변경됩니다.
관련 코드
```c
/* …
```
=> CLEANUP: Integrate iov functions about item value between ASCII/Binary

engines/default/items.c
- jam2in/arcus-works#467
`item_cachedump()` 함수 내부에서 keybuf를 별도로 사용하지 않도록 변경합니다.
다른 함수에서는 크게 아래와 같은 2가지 형태로 key를 출력하고 있습니다.
```c
#define PRINT_NKEY(nkey) ((nkey) < 250 ? (nkey) : 250)
```
https://github.com/naver/arcus-memcached/blob/56c65ebf6ae3091bff6c5b6709d85a534579f600/engines/default/coll_btree.c#L4484-L4492
현재 lqdetect에서만 사용하고 있는 형태
https://github.com/naver/arcus-memcached/blob/56c65ebf6ae3091bff6c5b6709d85a534579f600/lqdetect.c#L133-L140
캐시 서버에서 key를 출력하는 경우 `%.*s` format을 활용하는 것 같아서, 이를 적용했습니다.
key의 일부분만 출력하는 것이 아닌 전체 key를 출력합니다.
=> CLEANUP: Do not use keybuf in item_cachedump()

arcus_zk.c
- jam2in/arcus-works#504
- #735
ZOO_SESSION_EVENT를 처리하는 arcus_zk_watcher()의 로그 메시지를 보강합니다.
- CONNECTED state 메시지 보강
- 로그 레벨 변경: `DEBUG` => `INFO`
- 서버 주소 / timeout 정보 추가
- EXPIRED state 메시지 보강
- 메시지 내용 변경
- session id 추가
- CONNECTING state 메시지 보강
- 로그 레벨 변경: `DEBUG` => `WARNING`
- 메시지 내용 변경
- ensemble string 추가
```
2024-02-16 12:56:19,387:129595(0x7f156cc5f740):ZOO_INFO@zookeeper_init_internal@1188: Initiating client connection, host=ncp-2c4-001:40000,ncp-2c4-002:40000,ncp-2c4-003:40000 sessionTimeout=30000 watcher=0x437e50 sessionId=0 sessionPasswd=<null> context=0x651c00 flags=0
2024-02-16 12:56:19,387:129595(0x7f1568486700):ZOO_INFO@check_events@2498: initiated connection to server [10.33.111.24:40000]
2024-02-16 12:56:19,396:129595(0x7f1568486700):ZOO_INFO@check_events@2550: session …
```
=> INTERNAL: Enhance arcus_zk_watcher log messages

memcached.c
- jam2in/arcus-works#497
함수명을 의미에 맞게 일부 변경합니다.
- human_readable_time → lefttime
- add_iov_e/hinfo_value → add_iov_e/hinfo_ascii/bin
- e/hinfo_check/append_ascii_tail_string → e/hinfo_check/append_tail_crlf
=> INTERNAL: Rename some functions

memcached.c
Binary 프로토콜에서 Dynamic Buffer 활용으로 인하여 `write_and_free` 사용 시
에러(Dynamic Buffer가 NULL인 경우) 처리로 ASCII 프로토콜 용도의 `out_string`을 사용하는 것을 수정합니다.
`write_and_free`에서는 인자로 받는 포인터가 NULL이 아닌 것을 보장하게 끔 했고,
`write_and_free` 호출하는 주변 로직에서 에러를 처리하게끔 변경했습니다.
대부분 `write_and_free`를 호출할 경우 포인터가 NULL이 아니게 끔 보장하고 있어 
관련 에러 처리가 없는 코드만 수정했습니다.
=> INTERNAL: Fix the wrong write_and_free error handling in binary protocol

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-refactoring-request.md, .github/PULL_REQUEST_TEMPLATE.md
- naver/arcus-java-client#733
- Issue/PR template을 추가합니다.
- 템플릿 내용은 java-clinet와 동일합니다.
=> DOC: Create issue/pr templates

docs/ascii-protocol/ch12-command-administration.md
- #707
- #752 
- 신규 명령어에 대한 문서를 추가합니다. [미리보기](https://github.com/namsic/arcus-memcached/blob/doc-newcmd/docs/ascii-protocol/ch12-command-administration.md#ready)
- 기존 문서의 표현 양식과는 약간의 차이가 있습니다.
- `lqdetect command는 아래와 같다.` => `### Syntax`
- `show 명령은 저장된 명령어 샘플을 출력하고 그 결과는 아래와 같다.` => `### Response`
- 각 응답을 별개의 코드 블럭으로 구분하고, 각 응답에 대한 설명을 하단에 추가
=> DOC: Add ready, shutdown command

memcached.c
- jam2in/arcus-works#529
- UDP에서 connection 재사용을 위해 conn_cleanup 일부 로직을 conn_close로 이동했습니다.
- UDP에서 conn_cleanup 수행 후 conn_read로 바꾸게 끔 했습니다.
- UDP 소켓 실패 시 conn_closing으로 바꾸게 끔 했습니다.
- 기존 로직에서 UDP의 conn_closing 시 발생하는 문제
1. conn_cleanup 만 수행  
2. c->thread = NULL / c->std = -1 변경 (이벤트에서 제거 X)
3. 해당 connection에서 새로운 이벤트 발생
4. 이벤트에 등록된 sfd와 c->sfd(= -1) 차이 발생
5. conn_close
6. c->thread = NULL 이므로 assert(c->thread) 로 인한 전체 프로그램 종료
- conn_read로의 변경 이유
- conn_cleanup 이후 새로운 명령어를 받을 수 있는 state로 변경이 필요
- read 데이터 존재 X 시 read 이벤트를 등록하는 conn_waiting으로 변경도 필요
- conn_read : 완전히 새로운 read를 받음
- conn_new_cmd : read buffer에 남아있는 cmd를 수행 후 새로운 read 수행
- 에러로 인한 재수행이므로 완전히 새롭게 명령을 수행하는 conn_read가 더 맞다고 생각됩니다.
> conn_cleanup()만 호출하는 경우에는 sfd가 -1로 초기화되어야 하나요?
conn_cleanup 만 수행해야 하는경우 sfd를 초기화해서는 안됩니다.
- ~Perl …
=> INTERNAL: Fix problems about not released items and an assertion in UDP

cmdlog.c
- jam2in/arcus-works#559
- cmdlog stop 시 flush thread의 sleep을 깨우고, 해당 thread가 종료될 때 cmdlog start가 불가하도록 변경
=> INTERNAL: Wait till the cmdlog flush thread ends

lqdetect.c, lqdetect.h, memcached.c
- jam2in/arcus-works#526
- lqdetect_in_use 변수를 lqdetect 모듈 내부로 이동시켰습니다.
- on_detect 변수를 제거했습니다.
=> INTERNAL: Move a lqdetect_in_use variable

memcached.c, memcached.h
- jam2in/arcus-works#526
- mc_engine 변수를 내부 변수에서 외부 변수로 변경합니다.
=> INTERNAL: Externalize a mc_engine variable

memcached.c
- #772
- process_mop_prepare_nread 내 버그를 수정합니다.
=> FIX: Correct wrong actions in process_mop_prepare_nread

docs/ascii-protocol/ch07-command-map-collection.md
- #772
- mop upsert 명령어 관련 설명을 Docs에 추가합니다.
- Bop upsert와 동일하게 수정했습니다.
=> DOC: Add a upsert description in the map document

ChangeLog, config/version.pl
=> version 1.14.0

memcached.c
- jam2in/arcus-works#607
- 서버 쪽에서 delete의 exptime 관련 내용을 수정합니다.
=> DOC: Fix a comment about expiretime of delete command

lqdetect.c
- char client_ip[] => char *client_ip 변경하여 통일화
=> CLEANUP:  `lqdetect.c` pointer type

docs/ascii-protocol/ch08-command-btree-collection.md
=> DOC: Fix typo in smget document

lqdetect.c
- lq_detect_buffer에서 keypos 와 keylen을 제거하고 이를 대신해 lq_detect_argument에 key 필드를 삽입했습니다.
- key의 최대 사이즈를 250으로 설정하였습니다.
=> INTERNAL: Remove keypos, keylen field from lq_detect_buffer

docs/ascii-protocol/ch12-command-administration.md
-
- `stats cachedump` command 설명을 최신화 하였습니다.
=> DOC: Fix comment about cachedump command

docs/ascii-protocol/ch04-command-key-value.md, memcached.c, t/tlist/engine_default_b.txt, t/tlist/engine_default_s.txt, t/touch.t
- #487 
- #782 
- touch 기능 리뷰를 위한 PR입니다.
=> FEATURE: Add touch command

docs/ascii-protocol/ch04-command-key-value.md, memcached.c, t/gat.t
add get and touch command
- #781 
- #487
- gat 리뷰를 위한 PR입니다.
=> FEATURE: Add gat command

docs/administration/userlog.md
- jam2in/arcus-works#54
- userlog 사용법 및 기능에 대한 문서를 추가합니다.
=> DOC: Add a document for Userlog

README.md
N/A
캐시 서버 configure 시, 문서 설명 보충
=> DOCS: clarify lib install path in compilation guide.

.github/workflows/CI.yml
- jam2in/arcus-works#634
- CI 테스트 시 `--enable-sasl` 플래그 사용하도록 합니다.
=> TEST: Add `--enable-sasl` to configure option

userlog_logger.c
- #852 
- userlog 기능을 리팩터링했습니다.
- Log Reduction 관련 공통 로직을 do_log_reduction() 함수로 분리했습니다.
- ~기존 `userlog` 기능에서 Log Rate Limiting이 비활성화되고 Reduction 모드만 활성화된 경우, 압축된 로그 메시지에 시간이 제대로 출력되지 않던 버그를 수정했습니다.~
- 과거 시간 정보를 담는 `prevtime_str` 변수가 do_print_dup() 함수 내에서만 사용되어, 해당 함수의 지역 변수로 변경했습니다.
=> INTERNAL: Refactor do_userlog function in userlog_logger.c

userlog_logger.c
- #856
- 현재 용도에 맞게 prevtime_str 변수의 이름을 prefix_buf로 변경합니다.
=> INTERNAL: Rename prevtime_str variable to prefix_buf

userlog_logger.c
- N/A
- reduction_mode가 설정된 경우를 나누어 처리하던 조건문을 하나로 통합했습니다.
- 해당 PR이 리팩토링의 마지막 PR입니다.
- 꼭 필요한 변경은 아니지만, 이전에 코드를 살펴보던 중 의문이 들었던 코드입니다.
- 이번에 함께 정리하는 것이 좋겠다고 판단해 포함시켰습니다.
=> INTERNAL: Combine conditionals for reduction_mode setting

arcus_zk.c
- jam2in/arcus-works#741
- `strtok_r()` 수행 시 인자로 전달한 문자열이 변경되므로, 원본 대신 복사한 문자열을 사용하도록 합니다.
=> CLEANUP: Do not modify ensemble_list directly

docs/ascii-protocol/ch04-command-key-value.md
-
- gat/gats 명령어에 향후 릴리즈 예정이라는 키워드를 추가합니다.
=> DOCS: Add scheduled release keyword to the gat command

configure.ac, sasl_defs.c
- jam2in/arcus-works#743
- 빌드과정에서 getconf 탐색 실패를 수정합니다.
- OSS memcached와 동일하게 수정했습니다.
=> INTERNAL: Fix SASL_GETCONF(PATH) detection
