naver/arcus-memcached

- config/autorun.sh
Changed autorun.sh to run on dash (on debian distributions).
Refer to https://github.com/naver/arcus-memcached/pull/30
> Fix failing autorun.sh on dash

- config/autorun.sh
arcus 빌드가 진행되면서 submodule이 업데이트 될 때
arcus-memcached의 폴더에 있는 .git 이 폴더가 아니라 파일이어서
해당 명령어가 실행되지 않는 사항을 수정하였습니다.
> fix config/autorun.sh for arcus build

- assoc.h
- include/memcached/types.h
- items.c
- items.h
Long key support를 위한 사전작업으로 key, prefix를 2bytes로 늘리는 작업입니다.
First reviewer
Final reviewer
> LONG_KEY_SUPPORT: increase max key and prefix size 250 to 65530

- assoc.c
- items.c
- items.h
Long key support를 위한 사전작업으로 hash_item structure에 hash value를 추가하고,
hash function call을 줄이는 내용입니다.
First reviewer
Final reviewer
> LONG_KEY_SUPPORT: add hash value for reduce hash function call

- items.c
alpine linux 3.4 에서 빌드하려니 에러가 발생했습니다. 어떻게 에러 코드를 처리해야 할지 모르겠어서 일단 제너릭 오류로 처리했습니다.
```
items.c: In function 'set_elem_insert':
items.c:1971:15: error: 'hidx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
for (find = node->htab[hidx]; find != NULL; find = find->next) {
^
items.c:1958:9: note: 'hidx' was declared here
int hidx;
^
```
> Fix an uninitialized error in items.c

- engines/default/default_engine.c
- engines/demo/demo_engine.c
- include/memcached/engine.h
- include/memcached/types.h
- memcached.c
대표님께서 verbose value 는 memcached 코어에서 사용하므로 valid check를 해서 값만 engine에 넘겨주라고  말씀하셔서 코어에서 verbosity 만 따로 filtering하여 valid check하도록 수정하였습니다.
First reviewer
Final reviewer
> Add Config api

- engines/default/items.c
- include/memcached/engine.h
> Refactor: key can be NULL in do_item_alloc function

- engines/default/default_engine.c
- include/memcached/engine.h
- include/memcached/types.h
- memcached.c
First reviewer
Final reviewer
기존 engine set_config api는 그대로 두고 core에서 기존 코드를 사용하도록 수정 했습니다.
code tag는 SIMPLE_CONFIG_API이고, 기존 CONFIG_API tag와는 verbosity 추가로 인해
중복되는 코드가 있을 수 있습니다. 확인 요청 드립니다.
> Refactor: refactoring config api to simple

- engines/default/default_engine.c
- engines/default/default_engine.h
- engines/demo/demo_engine.c
- engines/demo/demo_engine.h
- memcached.c
- memcached.h
sticky에 대한 설정을 기존 sticky_ratio 설정으로 계산하는 것을 sticky_limit 그대로 적용되도록 하고 sticky_limit을 런타임에 변경할 수 있도록 하는 변경입니다.
첫 번째 커밋은 sticky_ratio로 sticky_limit을 계산하던 기존 코드를 sticky_limit 그대로 사용하도록 하는 변경입니다.
두 번째 커밋은 sticky_limit을 변경할 수 있도록 하는 api 추가입니다.
> Refactor: sticky_ratio -> sticky_limit

- arcus_zk.c
- engines/default/slabs.c
- memcached.c
print format에  대한 리팩토링입니다.
size_t 출력에 대해 %llu를, (C99에서는 size_t에 대해 %zu를 사용하기를 권고하지만 VC에서 지원하지 않는다고 하여 더 이식성 좋은 코드를 위해 llu를 사용합니다. 참고로, 현재 lu를 사용해도 되지만 현재 memcached 최신 코드도 llu를 사용하고 있어 이를 따라가려 합니다.)
uint64_t 출력에 대해 %PRIu64를 쓰도록 통일하였습니다.
> Refactor: print format

- README.md
- doc/arcus-ascii-protocol.md
- doc/arcus-basic-concept.md
- doc/arcus-collection-concept.md
- doc/arcus-item-attribute.md
- doc/command-list-collection.md
- doc/command-map-collection.md
- doc/command-set-collection.md
#95 를 develop 브랜치에 적용하였습니다.
It corrects several repeated typos found on the docs:
* colleciton -> collection
* 데이타, 데이티 -> 데이터
* And more
> Fix typos on docs: colleciton->collection etc

- arcus_zk.c
@jhpark816 
zinfo가 사용되어야하는 곳에서 main_zk로 잘못사용되어
DEBUG 모드에서 segment fault가 발생합니다.
> FIX: misuse of main_zk variable

- config/Doxyfile-api.in
- config/Doxyfile.in
- doc/protocol.txt
Corrected misspelled words, added periods, and fixed some grammatical errors.
> Typos fixed in /config

- engines/default/items.c
- include/memcached/types.h
Reviewer
long key일 때 last 250 character만 가지고
hash value를 계산하도록 hash 함수를 최적화 한 PR입니다.
확인 요청 드립니다.
> CLEANUP: hash function optimization for long keys.

- arcus_zk.c
- include/memcached/types.h
main reviewer:
final reviewer:
운영자 실수로 인한 ephemeral znode 삭제 대응 코드입니다.
cache_list가 지워졌을 시에는 항상 zk와 연결을 끊고 rejoin 가능한 상태로 대기합니다.
> FEATURE: cache_list ephemeral znode deleted action

- ChangeLog
I found some Typos while reading ChangeLog.
miscaculated -> miscalculated
cahe -> cache
elemeent -> element
Thanks.
> Found Typos

- ChangeLog-memcached
'mulitarget -> multitarget', 'incrememnt -> increment', 'apropriate -> appropriate'
> Fix Typo : line 122, 196, 308

- engines/default/items.c
- include/memcached/types.h
reviewer
btree count operation에서,
range bkey 일 때 최적화를 위한 PR입니다.
확인 요청 드립니다.
> ENHANCE: Optimize btree count operation when range conditions.

- lqdetect.c
I found a missing break.
if it is intended, it will run duplicated code.
for example
if LQCMD_LOP_DELETE and arg->delete_or_drop = 2
first below code will run.
```c
snprintf(bufptr, length, "%s %s %s\n", key, arg->range, "drop");
```
and below code will rerun.
```c
if (arg->delete_or_drop != 0) {
snprintf(bufptr, length, "%s %s %s\n", key, arg->range,
(arg->delete_or_drop == 2 ? "drop" : "delete"));
}
```
> fix missing break

- memcached.c
Collection value length checking 관련 PR 입니다.
value length max 값에 대한 확인 없이 ```\r\n```을 위해 length+2 해주는
로직으로 error가 발생하는 issue를 해결 합니다.
reviewer
> FIX: correction to value length checking of collection

- memcached.c
- t/issue_67.t
There is a issue by binidng udp port as default.
ref: https://blog.cloudflare.com/memcrashed-major-amplification-attacks-from-port-11211/
Arcus also will be affected.
and this is the same patch with original memcached https://github.com/memcached/memcached/commit/dbb7a8af90054bf4ef51f5814ef7ceb17d83d974
I tested after applying this patch, Binding udp port is disabled.
> disable udp by default

- arcus_zk.c
- arcus_zk.h
- include/memcached/types.h
- memcached.c
proxy server 지원에 관한 PR입니다.
znode_name과 mc_ipport에 proxy 정보를 입력시켜 실제 ipport는 자신의 것을 사용하지만
proxy의 ipport를 사용하는 것처럼 동작합니다.
실행시에는 -x옵션에 proxy 서버의 ip:port를 넣으면 됩니다. hostname도 사용가능하도록 구현했습니다.
현재 구현이 복잡한지를 따져보고, arcus_zk_init에 proxy를 파라미터로 넣는 현재 구현이 이상하면,
proxy_zk_init 처럼 따로 initial 함수를 떼어내서 구현하는 방법도 있을 것 같습니다.
@jhpark816 
리뷰 부탁드립니다.
> FEATURE: proxy server support

- t/cas.t
- t/udp.t
squall, gust engine 테스트를 위한 테스트 스크립트 수정 PR입니다.
t/cas.t
- 한 테스트 내에서 get_memcached를 연속해서 호출하게되면 db 1개를 여러 memcached process에서 공유하게 되는 형태가되어서 원하는 테스트 동작이 이루어 지지않음.
t/udp.t
- release_memcached를 필요한 스크립트내의 마지막 줄에 일괄적으로 추가하였는데 해당 테스트의 경우 그 부분이 주석처리되어 있어서 위치변경.
> TEST : correction of some test script for ee version testing

- t/coll_bop_mget_1.t
- t/lib/MemcachedTest.pm
@jhpark816
jam2in/arcus-memcached-EE#557
에 대한 PR입니다. 임시로 비교를 위해 테스트 파일 일부분만 수정하였습니다.
---
참고용으로 
각 케이스별로 10만건에 대한 테스트 수행속도를 측정.
case 1(변경된 형태)
```
mem_cmd_is($sock, $cmd, $rst);
```
case 2(변경전 형태)
```
print $sock "$cmd\r\n"; is(scalar <$sock>, "$rst\r\n", "$cmd: $rst");
or
mem_cmd_val_is($sock, $cmd, $val, $rst);
```
testcase1.pl : 변경된 형태로 작성 simple kv response 속도
testcase2.pl : 변경 후 형태로 작성 simple kv response 속도
testcase3.pl : 변경된 형태로 작성 bop mget response 속도
testcase4.pl : 변경 후 형태로 작성 bop mget response 속도
수행속도는 비슷한 것 같습니다.
> TEST : add common function for test

- t/arcus_ping_test.t
- t/ascii_ext_protocol.t
- t/binary-get.t
- t/bogus-commands.t
- t/cas.t
- t/cmd_extensions.t
- t/coll_bkeymismatch_test.t
- t/coll_bkeyoor_test.t
- t/coll_bop_attr_min_max_bkey.t
- t/coll_bop_count.t
- t/coll_bop_delete.t
- t/coll_bop_eflag.t
- t/coll_bop_get.t
- t/coll_bop_incrdecr.t
- t/lib/MemcachedTest.pm
@jhpark816 
common function 1차 부분적용 PR입니다. 한번에하게되면 너무 많을 것 같아 부분적으로 나눠서 PR보내겠습니다.
참고로 test case 갯수가 달라진 테스트가 있는데 이유는 아래와 같습니다.
- 기존
```
getattr_is($sock, "minbkey1 minbkey", "minbkey=10");
getattr_is($sock, "minbkey1 maxbkey", "maxbkey=90");
```
- 변경
```
$cmd = "getattr minbkey1 minbkey maxbkey";
"ATTR minbkey=-1
ATTR maxbkey=-1
END";
mem_cmd_is($sock, $cmd, "", $rst);
```
과 같이 여러개로 나뉘어진 테스트를 합칠 수 있는 건은 합쳐서 수행하다보니 변경되었습니다.
적용하다보니
```
bop count ......
COUNT=<number>
```
```
set kv 1 0 1
1
STORED
incr kv 1
2
```
와 같은 command들도 mem_cmd_is subroutine을 사용할 수 있게 수정되었습니다.
> TEST : apply common function 1

- engines/default/slabs.c
- t/issue_ee_599.t
- t/tlist/engine_default_b.txt
- t/tlist/engine_default_s.txt
@jhpark816 
move_left할 때에
```
static void do_smmgr_01pct_check_and_move_left(void)
{
uint64_t space_standard = sm_anchor.used_total_space/100; /* 1% of total_used_space */
int smid, i;
if (sm_anchor.used_slist[sm_anchor.used_01pct_clsid].space == 0) {
if (sm_anchor.used_01pct_clsid < sm_anchor.used_maxid) {
smid = sm_anchor.used_01pct_clsid+1;
for ( ; smid <= sm_anchor.used_maxid; smid++) {
if (sm_anchor.used_slist[smid].space > 0) break;
}
assert(smid <= sm_anchor.used_maxid);
sm_anchor.used_01pct_clsid = smid;
} else {
assert(sm_anchor.used_01pct_space == 0);
sm_anchor.used_01pct_clsid = sm_anchor.used_maxid;
sm_anchor.used_01pct_space = sm_anchor.used_slist[sm_anchor.used_maxid].space;
}
}
if (sm_anchor.used_01pct_space < space_standard) {
int old_used_01pct_clsid = …
```
> FIX : slab free_small_space overflow

- t/issue_ee_599.t
기존 테스트에서 slab의 maxid, minid등을 확인했었습니다.
Enterprise 기능에서 hash_item의 크기가 migration등의 기능 추가로 community version에서의 slab id가 12였던게 ee version에서는 slab id가 13으로 변하는 상황 때문에 ee version의 테스트가 실패하네요.
해당 dependency를 제거한 테스트로 변경하였습니다.
> TEST : modified issue_ee_599.t test

- t/coll_bop_random_insert.bt
default engine 테스트에서는 release_memcached 함수를 사용하지 않아서 통과됐었는데
누락 됐었습니다.
> FIX : coll_bop_random_insert.bt fix few code

- engines/default/slabs.c
used_01pct_cslid의 used space 가 0 일 때
used space가 0이 아닌 class id를 used_01pct_clsid로 세팅하는 부분에서
free space 계산하는 로직이 빠져있어서 free space에 대한 계산이 잘못 되어 있었습니다.
reviewer
확인 요청 드립니다.
> FIX: miscalculate free space

- engines/default/items.c
- engines/default/slabs.c
no more small memory chunk log의 출력을 줄이기 위한 PR 입니다.
item eviction을 수행 하면서 재시도에 성공 할 경우 log는 출력하지 않고,
eviction을 수행 했지만 메모리가 부족할 경우에만 log message를
출력하도록 변경 했습니다.
> CLEANUP: reduce print of no more small memory chunk log

- engines/default/default_engine.c
- engines/default/default_engine.h
- engines/default/items.c
1. slabs class 별로 있는 outofmemory 지표를 통합하여 보여줄 수 있도록
```outofmemorys``` 지표를 추가 했습니다. ```stats```명령어를 통해 확인할 수 있습니다.
2. allocation failure로 인해 retry 할 경우 retry 완료 후 verbose level
설정에 따라 retry count를 출력하도록 추가 했습니다.
> CLEANUP: add outofmemorys stats and allocation retry log

- cmdlog.h
- memcached.c
cmdlog file 생성 시 directory path length check를 추가 했습니다.
> CLEANUP: add a directory path length check of the cmdlog file

- arcus_zk.c
- include/memcached/types.h
arcus_zk module의 main thread인
sm_state_thread() 내부 동작의 readability 향상을 위한 refactoring 입니다.
sm_state_thread 는 request or sm_info 상태에 따라서 함수만 호출하고
각각의 request나 상태에 따른 동작은 함수에서 수행하도록 수정 했습니다.
@jhpark816 
확인 요청 드립니다.
> CLEANUP: refactoring arcus_zk for readability

- doc/command-btree-collection.md
- memcached.c
bop smget spec 변경으로, ATTR_MISMATCH response를
return하지 않게 되었습니다. 관련 코드와 document를 제거하기 위한 PR입니다.
@jhpark816 
확인요청 드립니다.
> CLEANUP: remove ATTR_MISMATCH with bop smget specification change

- memcached.c
bind 시에 해당 address 가 사용중이어서 실패하면
warning 레벨의 로그를 남기도록 하는 PR입니다.
만약 ipv4, ipv6 모두 사용중일 시에 아래와 같이 로깅됩니다.
May 30 17:25:40 jam2in-s001 memcached[32527]: 0.0.0.0:11211 already in use
May 30 17:25:40 jam2in-s001 memcached[32527]: :::11211 already in use
> CLEANUP: add bind error warning message

- t/udp.t
perl version에 따라서 deprecated 된 syntax를 제거하기 위한 PR입니다.
travis-ci test 실패의 원인이었고,
perl 5.22.0 version 이후에서 실행 시 error가 발생합니다.
@jhpark816 
확인 요청 드립니다.
> FIX: remove deprecated syntax by perl version

- arcus_zk.c
arcus_zk에서 gethostbyaddr 호출 시 발생되는 메모리 leak을 수정한 코드입니다.
> FIX: memory leak when getting hostname by address

- engines/default/default_engine.conf
default_engine의 설정값 파일로 관리하기 위해,
default_engine.conf 파일을 추가 했습니다.
collection max size의 경우 duplicate entry warning 이 출력되서 제거했고,
item_size_max 설정만 추가 했습니다.
모든 설정을 확인해보지 않았지만,
item_size_max의 경우 conf 파일에 있는 설정값으로 설정됩니다.
@jhpark816 
확인 요청 드립니다.
> [persistence] add config file for default engine config

- engines/default/default_engine.c
- engines/default/default_engine.conf
#219 persistence 기능 on/off를 위한 옵션추가 PR 입니다.
defualt_engine.conf 파일 내부에 use_persistence로 구동 시 on/off 할 수 있습니다.
기본값은 off 상태입니다.
@jhpark816 
확인 요청 드립니다.
> [persistence] added use_persistence config in default_engine.conf file

- t/whitespace.t
whitespace test에서, file open이 실패했을 때
error message 추가 PR 입니다.
whitespace 를 발견해서 테스트가 실패 할 경우 해당 file name을 출력 해주지만,
file open 이 실패할 경우 출력해주지 않고 종료되어서 원인을 찾기 어려운 문제가 있었습니다.
@jhpark816 
확인 요청 드립니다.
> TEST: add error message when file open fails

- engines/default/cmdlogrec.c
배열 크기가 작은 문제
- MAX_BKEY_LENG => MAX_BKEY_LENG*2 + 2
nbkey==0 일 때 uint64_t bkey 값을 memcpy하지 않고 출력
Reviwer
> [persistence] FIX: lrec_bkey_print

- engines/default/cmdlogrec.c
persistence 에서 overflow action text array가 잘못되어 수정 했습니다.
ENGINE_OVFL_ACTION enum이 1부터 시작하는데, text array는 0부터 error인 상태입니다.
@jhpark816 
확인 요청 드립니다.
> [persistence] fix ovflact text

- engines/default/item_clog.c
item change log module 에서 engine config를 사용하기 위한 PR 입니다.
@jhpark816 
확인 요청 드립니다.
> CLEANUP: use engine config in item change log module

- engines/default/cmdlogrec.c
cmdlogrec.c 버그 수정
- 헤더 부분 길이 포함
- 구조체 타입 memcpy 시 void * 캐스팅
Reviewer
> FIX: fix the length of a log record.

- engines/default/cmdlogrec.c
eflag 출력을 위한 lrec_eflag_print() 함수 정의
Reviewer
> [persistence] added lrec_eflag_print() function for print eflag.

- engines/default/checkpoint.c
모든 캐시 데이터를 덤프하도록 nprefix 값은 -1로 넘겨주어야 함.
Reviewer
> [persistence] fix passing nprefix value with -1 to dump all cache items.

- engines/default/items.c
- testapp.c
cppcheck 검사 결과 error로 뜨는 것을 고쳤습니다.
에러 메세지는 다음과 같습니다.
[engines/default/items.c:4900]: (error) Uninitialized struct member: posi.bkeq
[testapp.c:1956]: (error) Memory leak: buffer
[testapp.c:701]: (error) Resource leak: error
[testapp.c:604]: (error) Possible null pointer dereference: string_val
> CLEANUP: fixed cppcheck's error

- basic_engine_testsuite.c
- cluster_config.c
- memcached.c
- sasl_defs.c
- testapp.c
- thread.c
cppcheck에서 warning 띄우는 부분을 수정했습니다.
argument는 int인데 type specifier는 unsigned int일 경우에는 type specifier를 고쳤습니다.  단 cluster_config.c:146 의 경우 hh, nn, pp가 모두 for문의 인덱스로 쓰이는 변수들이라 unsigned로 고쳤습니다.  
```
[basic_engine_testsuite.c:55]: (warning) Assert statement modifies 'fi'.
[cluster_config.c:146]: (warning) %u in format string (no. 2) requires 'unsigned int' but the argument type is 'int'.
[memcached.c:9290]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'int'.
[memcached.c:15287]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'int'.
[sasl_defs.c:33]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
[testapp.c:318]: (warning) %u in format string (no. 1) requires …
```
> CLEANUP: fixed cppcheck's warning

- engines/default/default_engine.c
- engines/default/default_engine.conf
- engines/default/default_engine.h
issue : https://github.com/naver/arcus-memcached/issues/268
data_path, log_path, async_logging 설정 값을 받을 수 있도록 처리.
> [persistence] get file path and async_logging from engine conf file.

- config_parser.c
key=value 형태로 이루어진 config file 을 line 별로 읽을 때 
trim_copy() 를 통해 key와 value 를 parsing 한다.
현재 value 가 없는 line을 parsing 할 때 포인터가 invalid 한 곳을 가리키는 문제가 있다.
예를들어 data_path= 와 같이 value 가 주어지지 않은 line 은 파일에는 data_path=LF 기록이 되어 있고,
fget 으로 인해 받은 문자열은 (data_path=LF'\0') 을 받는다.
key 파싱 이후에 src 는 LF 를 가리키고 있고, value 파싱 시에
isspace 와 do~while 쪽에서 src 포인터를 각각 증가시켜 유효 메모리 범위를 넘어서게 된다. 
Reviewer
> FIX: could refer invalid memory space in trim_copy().

- engines/default/checkpoint.c
없는 파일을 unlink 할 때 발생하는 실패에 대해선 에러 핸들링을 하지 않도록 한다.
> [persistence] unlink error handling about missing file.

- .travis.yml
- Makefile.am
커버리지 테스트를 위해 travisl.yml에서 coveralls 관련 동작을 추가했습니다.
gcc + 커버리지 측정, clang + 커버리지 측정, gcc 커버리지 없음, clang 커버리지 없음 이렇게 네 가지가 동시에 빌드됩니다.
커버리지 플래그가 있을 때에만 관련한 스크립트가 동작하도록 작성했습니다.
커버리지 측정 조건을 넣어서 clang으로 컴파일하면 default.profraw 라는 파일이 생기는데 이게 whitespace.t 테스트에 자꾸 걸려서 예외 조건에 추가했습니다.
> FEATURE: add coverage test

- .travis.yml
travis ci test 환경 구축 중 package 설치 실패를 방지하기 위해
apt-get update를 수행하고 package 설치하도록 수정 했습니다.
Error log
```
E: Package 'libcppunit-dev' has no installation candidate
```
@jhpark816 
확인 요청 드립니다.
> TEST: add apt-get update to prevent package installation from failing

- engines/default/cmdlogrec.c
setattr 명령 시 아이템 타입이 simple kv 인 경우에 maxbkeyrange value copy 가 일어나는 버그를 수정.
```
static void lrec_it_setattr_write(LogRec *logrec, char *bufptr)
{
ITSetAttrLog *log = (ITSetAttrLog*)logrec;
int offset = sizeof(LogHdr) + offsetof(ITSetAttrData, data);
memcpy(bufptr, (void*)logrec, offset);
if (log->body.maxbkrlen != BKEY_NULL) { //simple kv 인 경우 이 값을 초기화시키지 않아서 실행됨.
/* maxbkeyrange value copy */
memcpy(bufptr + offset, log->maxbkrptr, BTREE_REAL_NBKEY(log->body.maxbkrlen));
offset += BTREE_REAL_NBKEY(log->body.maxbkrlen);
}
```
> [persistence] fix to write maxbkeyrange value if item type is simple kv.

- engines/default/checkpoint.c
- engines/default/mc_snapshot.c
- engines/default/mc_snapshot.h
issue : https://github.com/naver/arcus-memcached/issues/295 을 해결하기 위한 PR.
checkpoint 식별자인 checkpoint time 을 unique 한 값으로 만들기 위해 
tm_mday(일, 1 ~ 31) 와 tm_mon(월, 0 ~ 11) 를 추가로 더 해줌.
> [persistence] make checkpoint time unique.

- engines/default/cmdlogmgr.c
- engines/default/item_clog.c
recovery 때 redo 된 명령어들이 로그파일에 반영되지 않도록
recovery 가 끝난 후에 item_clog 가 enable 되도록 수정.
*즉시 재시작을 고려하지 않은 구현
> [persistence] set enable change log after recovery.

- run_test.pl
travis 환경에서 unit test 수행 시 동시성 문제로 인해
used port로 구동 실패하는 에러가 가끔 발생하는 상태입니다.
이러한 문제를 방지하기 위해 기존 5개 씩 병렬로 진행하는 현재 상태에서 3으로 변경 했습니다.
@jhpark816 
확인 요청 드립니다.
> TEST: reduce parallel jobs to 3 for prevent concurrency problems

- engines/default/checkpoint.c
int64_t 가 시스템 종속적인 타입이어서 포맷이 일치하지 않는 경우가 있어 에러가 발생합니다.
PRId64 매크로를 사용하도록 변경하였습니다.
> [persistence] fix gcc int type error. use macro not dependent on system.

- engines/default/checkpoint.c
- engines/default/mc_snapshot.c
- engines/default/mc_snapshot.h
snapshot backup file 이 있는 경우 다음 체크포인트는 이 파일의 size 기반으로 동작해야하므로
cs->lastsize 를 세팅합니다.
```
static bool do_checkpoint_needed(chkpt_st *cs)
{
struct engine_config *config = cs->config;
size_t snapshot_file_size = cs->lastsize;
size_t cmdlog_file_size   = cmdlog_file_getsize();
size_t min_logsize        = config->chkpt_interval_min_logsize;
int    pct_snapshot       = config->chkpt_interval_pct_snapshot;
if ((cmdlog_file_size < min_logsize) ||
(cmdlog_file_size < (snapshot_file_size + (snapshot_file_size*(pct_snapshot*0.01))))) {
return false;
}
return true;
}
```
> [persistence] set last size of snapshot file.

- engines/default/cmdlogrec.h
update, arithmetic 명령은 복구 시에 insert 명령으로 재수행하므로 필요 없어진 upd type 들을 제거하였습니다. 
> [persistence] remove not needed updtype.

- engines/default/default_engine.c
- engines/default/items.c
- engines/default/items.h
- engines/demo/demo_engine.c
- include/memcached/engine.h
- include/memcached/types.h
- memcached.c
- List에 element를 삽입 할 때 refcount를 증가시키는 부분은 필요하지 않아 증가/감소하지 않도록 하였습니다.
- Element 삽입 수행 실패 시, 또는 client로부터 데이터를 제대로 읽지 못한 경우 list_elem_free()를 호출하여 할당해두었던 element를 반환하게끔 수정했습니다.
list_elem_alloc() 다음에 list_elem_free()가 위치하도록 하였고,
process_lop_insert_complete()와 process_bin_lop_insert_complete() 모두에서 list_elem_free()를 호출하도록 하였습니다.
> FEATURE: List element free

- engines/default/cmdlogrec.c
map element insert 함수에서 map element delete struct type 을 사용하는 부분을 수정했습니다.
> [persistence] fixed passing improper struct type.

- engines/default/default_engine.c
- engines/default/items.c
- engines/default/items.h
- engines/demo/demo_engine.c
- include/memcached/engine.h
- include/memcached/types.h
- memcached.c
Collection에 element 삽입할 때 release()함수 대신 free()함수를 새로 구현하였습니다.
- 할당하는 과정에서 refcount는 불필요하므로 refcount = 0으로 지정했습니다.
- insert 실패 후 elem_free 함수를 호출하도록 하였습니다. (refcount 감소 안함)
추가적으로  btree는 getrim 옵션이 있으면 기존의 element를 조회하고 refcount가 증가할 수 있기 때문에 elem_free 내에서 refcount가 0이 아닐 때 감소하도록 구현했습니다. 
reviewer
> FEATURE:Element Free

- memcached.c
bop insert후 trimmed_element를 release가 아닌 free()로 해제하도록 수정하였습니다.
reviewer
> CLEANUP:Element Free

- memcached.c
issue : https://github.com/naver/arcus-memcached/issues/342
- engine clock 을 먼저 초기화하기 위해 모듈 호출 순서를 변경
- 오타 수정 및 주변 주석 스타일에 맞게 소문자로 변경
> CLEANUP: initialized stats and clock handler before loading engine.

- engines/default/default_engine.c
- engines/default/items.c
- engines/default/items.h
- engines/demo/demo_engine.c
- include/memcached/engine.h
- include/memcached/types.h
- memcached.c
1. collection get interface에서 조회할 element 배열 크기를 engine 내부에서 결정하도록 수정
기존 코드는 memcache core에서 결정했는데, engine 내부에서 해당 collectionn의 크기만큼만 배열을 할당하도록 하였습니다.
2. element 조회 관련하여 공통적인 구조체를 정의
구조체 포함 내용은 element 배열, element 수, 공통정보(flag, dropped, trimmed 여부) 입니다.
3. 공통 구조체에 맞게 collection get interface 변경
reviewer
> CLEANUP: Collection Get Interface

- memcached.c
매크로의 위치 때문에 아래와 같은 컴파일 에러가 발생합니다.
```
memcached.c:2186:2: error: embedding a directive within macro arguments has undefined behavior [-Werror,-Wembedded-directive]
#ifdef COLLGET_RESULT
```
> FIX: compile error occur because of macro location

- engines/default/cmdlogbuf.c
cmdlog_buf_final() 에서 pthread_mutex_destroy() 가 필요합니다.
> [persistence] Destroyed log global mutex.

- engines/default/checkpoint.c
- engines/default/cmdlogbuf.c
- engines/default/cmdlogmgr.c
- engines/default/mc_snapshot.c
issue : https://github.com/naver/arcus-memcached/issues/356
각 modul_final() 수행은 module_initialized 여부를 확인하고 진행하도록 수정하였습니다.
@jhpark816 리뷰 부탁드립니다.
> [persistence] do module_final() only if the module is initialized.

- engines/default/checkpoint.c
- engines/default/mc_snapshot.c
엔진 종료 시에 checkpoint 와 snapshot 동작 종료는 checkpoint -> snapshot 순으로 종료되야 한다.
checkpoint 스레드가 snapshot 동작을 수행하고 있을 때 snapshot 스레드가 engine->initialized 를 먼저 확인하여 중단되면, 전체 데이터를 스냅샷 하지 못한 채 스냅샷이 중단되고, 체크포인트 모듈에서 에러 메세지를 출력하게 된다. ("Failed in checkpoint. Retry checkpoint in 5 seconds.")
따라서 두 모듈은 engine->initialized 가 아닌 각 모듈의 종료 요청(reqstop)을 받은 경우에 동작을 끝내도록 한다.
> [persistence] Keeped the termination order of module.

- engines/default/mc_snapshot.c
issue : https://github.com/naver/arcus-memcached/issues/362 해결을 위한 PR 입니다.
체크포인트에 의한 스냅샷인 경우 stop 되지 않도록 합니다.
> [persistence] checkpoint must be not stopped by snapshot stop command.

- engines/default/checkpoint.c
- engines/default/cmdlogbuf.c
리팩토링 성격의 작업이며, 
command log flush thread state 변수를 volatile 로 선언하여
해당 변수들을 접근시에 별도의 락을 잡지 않도록 합니다.
> [persistence] Declared command log flush thread state as volatile

- engines/default/cmdlogrec.c
- engines/default/mc_snapshot.c
스냅샷 복구 모듈에서 엘리먼트 삽입 명령을 수행하기 위해 복구된 콜렉션 아이템을 얻어옵니다.
해당 아이템이 expired 된 경우, NULL 을 반환할 수 있습니다.
그렇기 때문에 NULL 을 확인하는 assert 문을 제거하고,
이 아이템에 삽입할 엘리먼트 명령 수행은 skip 하도록 합니다.
@jhpark816  리뷰 요청드립니다.
> [persistence] snapshot item was restored could be NULL.

- engines/default/slabs.c
주석과 실제 코드 내용이 맞지 않아 PR 합니다.
```
sm class info
index  sunit_len  sunit_cnt  total_len  total_cnt
-------------------------------------------------
0          8        128          0          0
1         16        128       1024        128
2         32        128       3072        256
3         64        128       7168        384
4        128        128      15360        512
5        256         68      31744        640
6          0          0      49152        708
-------------------------------------------------
```
위 내용이 실제 smmgr 상태입니다.
> CLEANUP: fixed do_smmgr_memid comment

- engines/default/mc_snapshot.c
스냅샷을 데이터 모드로 동작시켰을 때 스냅샷된 캐시 아이템 개수를 증가시키지 않아서
stats snapshot 에서 snapped 정보가 0으로 나오는 문제가 있습니다.
> [persistence] incremented snapped item count.

- engines/default/assoc.h
> CLEANUP: fixed bucket_info comment's typo

- engines/default/default_engine.conf
default_engine.conf 파일의 기본 설정이 false 인데,
이전에 다른 commit에 의해 true로 설정된 상태로 merge 되었습니다.
false로 원복 시키기 위한 commit 입니다.
@jhpark816 
확인 요청 드립니다.
> [persistence] reset the default value of use_persistence to false

- engines/default/assoc.c
assoc_scan_init() 직후에 snapshot stop 명령이나 scrub 명령이 들어온 경우 assoc_scan_final()에서 버켓 참조카운트를 증가시키지 않았음에도 감소시켜 언더플로우를 발생시킵니다. 
-scrub code
```
while (engine->initialized && !scrubber->restart) {
/* scan and scrub cache items */
/* NOTE: scrub_count can be changed while scrubbing */
item_count = assoc_scan_next(&scan, item_array, config->scrub_count, 0);
if (item_count < 0) { /* reached to the end */
break;
}
/* Currently, item_count > 0.
* See the internals of assoc_scan_next(). It does not return 0.
*/
for (int i = 0; i < item_count; i++) {
scrubber->visited++;
if (do_item_isvalid(item_array[i], current_time) == false) {
do_item_unlink(item_array[i], ITEM_UNLINK_INVALID);
scrubber->cleaned++;
}
else if (scrubber->runmode == SCRUB_MODE_STALE &&
do_item_isstale(item_array[i]) == true) { …
```
> CLEANUP: Amended condition to decrease bucket refcount after finishing scan.

- engines/default/items.c
persistence에서 link log record를 생성하지 않도록 하기 위한 flag 설정 위치를
실제 item link 시키기 전으로 변경 했습니다.
attribute를 포함하여 요청 하는 경우 항상 log record를 attribute 정보를 포함하지 않도록 하고,
기존의 오류 처리(create == true인데, item이 있으면 실패)를 만족시키기 위함 입니다.
@jhpark816 
확인 요청 드립니다.
> [persistence] change the location of no create lrec flag

- engines/default/slabs.c
- isasl.c
- lqdetect.c
- testapp.c
codacy 검사 결과 type specifer가 잘못 지정된 코드가 발견되어 수정합니다.
testapp.c: signed long이 unsigned long으로 잘못 표기
나머지: unsignged int가 signed int로 잘못 표기
> CLEANUP: fix improper type specifiers

- memcached.c
"CLIENT_ERROR bad command line format" 으로 응답해야 할 상황에, format을 빼먹고 "CLIENT_ERROR bad command line" 으로 응답하고 있어 수정합니다.
코드 전체에서 format을 빼고 응답하는 부분은 이 곳 밖에 없고, 토큰 개수를 검사하는 부분에서는 모두 bad command line format으로 응답하고 있어 오타로 보는게 합당할 것 같습니다.
> CLEANUP: fix wrong response

- doc/command-key-value.md
delete command 에서 delay delete를 지원하는
time option을 사용할 수 있는 것처럼 되어 있습니다.
실제로는 지원하지 않고 있고, 아마 기존 memcached 버전의 backward compatibility 때문에
남겨둔 값으로 보입니다. 실제 코드를 보면 delete 에 time option을 줄 순 있지만, `0`이 아니면 error 처리 됩니다.
현재 최신 memcached도 같은 코드로 동작하는 상태로, time option을 노출시키지 않는게 좋을 것 같습니다.
@jhpark816 
확인 요청 드립니다.
> DOC: remove time option of delete command

- arcus_zk.c
노드 추가에 따른 auto scrub 동작 실패 시 에러 처리 코드를 추가했습니다.
auto scrub 수행이 실패하는 경우는 scrub thread 생성에 실패하는 경우밖에 없습니다.
> CLEANUP: add error handling for auto_scrub

- doc/arcus-basic-concept.md
- doc/command-administration.md
- include/memcached/types.h
- memcached.c
- memcached.h
- t/coll_max_elembytes_test.t
- t/tlist/engine_default_b.txt
- t/tlist/engine_default_s.txt
최대 element 크기를 조절할 수 있도록 기능을 추가하였습니다.
기존에 이 크기에 대한 설정은 memcached.h에 매크로로 설정되어있었는데
collection size에 대한 설정들이 memcached.c 쪽에 있어서
해당 위치로 element 크기 설정도 옮기고 변수 이름도 비슷한 모습으로 만들어두었습니다.
> FEATURE: add max_element_bytes config

- doc/arcus-ascii-protocol.md
- doc/arcus-telnet-interface.md
- doc/command-btree-collection.md
- doc/command-item-attribute.md
- doc/command-list-collection.md
- doc/command-map-collection.md
- doc/command-set-collection.md
docsify와 github의 링크 호환을 위해 제목에서 하이픈을 지우고 자연스러운 형태로 바꿨습니다.
> DOC: remove hyphen in documents chapter title

- doc/arcus-ascii-protocol.md
- doc/command-btree-collection.md
- doc/command-list-collection.md
- doc/command-map-collection.md
- doc/command-set-collection.md
- 절대 주소 링크를 상대 주소로 변경
- 변경된 제목(하이픈 제거)에 맞게 링크 수정
링크 작동 여부는 모두 수작업으로 확인했습니다.
> DOC: fix wrong header link

- engines/default/cmdlogbuf.c
- engines/default/cmdlogbuf.h
- engines/default/cmdlogmgr.c
issue https://github.com/naver/arcus-memcached/issues/410 와 관련한 PR입니다. 함수 명 변경부터 반영하겠습니다. 간단한 PR이므로 코드 태그는 생략하였습니다.
내부 함수와 용어를 맞추기 위해 cmdlog_buf_write, cmdlog_buf_flush 대신 cmdlog_buff_write, cmdlog_buff_flush 로 변경하였습니다.
@MinWooJin 리뷰 요청드립니다.
> [persistence] rename functions.

- engines/default/cmdlogrec.c
issue https://github.com/naver/arcus-memcached/issues/407 대한 PR입니다.
- value 출력 시 \r\n을 출력하도록 변경하였습니다. value 크기가 250자 이상이면 \r\n문자가 출력되지 않아 연산 요청 완료 메세지가 value string에 붙기 때문입니다.
기존
```
/* vallen >= 2, valstr = ...\r\n */
fprintf(stderr, "[BODY]   keylen=%u | keystr=%.*s | ittype=%s | "
"flags=%u | exptime=%u | %s | vallen=%u | valstr=%.*s",
```
변경
```
fprintf(stderr, "[BODY  ] keylen=%u | keystr=%.*s | ittype=%s | "
"flags=%u | exptime=%u | %s | vallen=%u | valstr=%.*s\r\n",
```
@MinWooJin 리뷰 요청 드립니다.
> [persistence] unified log record print format.

- engines/default/cmdlogbuf.c
- engines/default/cmdlogrec.c
- cmdlog_file_apply 함수 리팩토링
- lrec_redo_from_record 함수에서 redo=NULL 인 경우 ENGINE_SUCCESS 반환 
- 현재 snapshotDoneLog 읽으면 redo=NULL이여서 에러 메세지 출력하고 있었네요.
> [persistence] refactoring cmdlog_file_apply.

- Makefile.am
- memcached.c
- memcached.h
- thread.c
- thread.h
thread.h 만들고 관련 함수들 이동시켰습니다.
사용되지 않는 함수들도 있는데 일단은 헤더에 함께 포함시켰습니다.
> CLEANUP: move thread function declarations to thread.h

- memcached.c
#437 관련 PR 입니다.
기존 collection get 처리 로직 중 collection_get_complete() 함수들은
`ENGINE_ENOMEM` error code 관련 처리가 되어있던 상태인데,
collection_get() 함수들은 처리가 되지 않은 상태로
`SERVER_ERROR internal`로 response string을 보내고 있었습니다.
arcus-java-client/arcus-c-client의 response parsing 로직은 `SERVER_ERROR`를 기준으로 parsing하여
server error로 처리하기 때문에 기존에도 처리에 문제는 없었지만 정확한 response string을
출력하기 위하여 `ENGINE_ENOMEM` 처리를 출력하고 `SERVER_ERROR out of memory`로
response를 보내도록 수정 하였습니다.
실제 빠져있던 부분은 `process_lop_get(), process_sop_get(), process_bop_get()` 세 부분 입니다.
추가로, error code 처리하는 부분의 indentation 이 일부 달라 같이 처리했습니다.
@jhpark816 
확인 요청 드립니다.
> FIX: add ENGINE_ENOMEM error code handling

- .travis.yml
forked된 저장소에서 이메일 알림이 가지 않도록 설정을 수정했습니다. 
travis ci에는 빌드가 성공, 실패할 때 지정된 이메일로 알림을 주는 기능이 있는데, 이것이 forked된 저장소에서도 작동해 불필요한 noti가 발생하는 상황입니다. 
travis.yml 에 if문을 통해 다양한 조건을 걸 수 있는데, 조건중에 fork 여부도 포함되어 있습니다. ([링크](https://docs.travis-ci.com/user/notifications/)의 conditional notification 파트 참조) 이 기능을 이용해 포크된 저장소가 아닐 때에만 이메일이 가도록 했습니다.
if문의 정상 작동 여부는 개인 저장소에서 이메일 주소를 제 것으로 바꾸어 테스트 했습니다.
> FIX: disable travis_ci notification in forked repo

- arcus_zk.c
- arcus_zk.h
- memcached.c
이슈([링크](https://github.com/jam2in/arcus-memcached-EE/issues/389))에서 전달 받은 스탯을 stat settings로 옮겼습니다.
그외 stats 에서 stats settings으로 옮길만한 항목이 있는지 검토해봤는데 나머지는 수정이 필요 없을 듯 합니다.
stats는 사용자의 설정과 무관한 단순 통계, stats settings는 사용자가 실행 도중 명령을 통해 바꿀 수 있는 설정값을 보여주는게 적합하다고 생각해,  stats에 설정이 가능한 항목이 있는지 봤습니다. 이번 PR에 포함된 항목을 제외하면 다음과 같습니다. 
- limit_maxbytes (config memlimit 명령을 통해 변경)
- sticky_limit 
- engine_maxbytes (config memlimit 명령을 통해 변경)
maxbytes와 sticky_limit이 stats settings에도 포함되어 있어 수정이 필요없다고 봤습니다.
> CLEANUP: show zk config in stats settings.

- .travis.yml
noti 조건을 변경했습니다.
기존의 조건: forked repo가 아닐 때에만 noti
변경된 조건: forked repo가 아니거나, PR을 했을 때에만 noti
포크된 저장소에서 먼저 테스트 해보려 했지만, 같은 저장소에서 PR을 하면 빌드가 유도되지 않아 우선 PR 부터 하고 결과를 보겠습니다
> FIX: enable email notification for pull request

- engines/default/checkpoint.c
- engines/default/cmdlogbuf.c
- engines/default/cmdlogbuf.h
issue : cmdlog_file_open과 cmdlog_file_close의 구동 실패 동작 점검 https://github.com/naver/arcus-memcached/issues/436
- cmdlog_file_close() 에서 fd 를 close 하는 조건을 변경하였습니다. 
- shutdown 에 대한 동작은 cmdlog_file_final()에서 처리합니다.
@MinWooJin 리뷰 요청드립니다.
> [persistence] amended condition of closing fd in cmdlog_file_close().

- engines/default/cmdlogmgr.h
#460 관련 PR 입니다.
기존에 cmdlog record의 offset을 표현하던 LogSN.roffset 의 type이
uint32_t로 4GB 까지밖에 표현하지 못하는 문제가 있어 checkpoint 실패로 재시도 하거나
memlimit이 클 경우 에러가 발생할 수 있어서 uint64_t type으로 변경 했습니다.
@jhpark816 
확인 요청 드립니다.
> [persistence] change the type of roffset in LogSN

- arcus_zk.c
azk_count는 zookeeper의 async operation을 sync 하기 위해 사용하는 값으로,
sync가 필요한 부분에서 azk_count가 `<= 0`이 될 때 까지 timed wait 하는 형태로 동작합니다.
현재 arcus-memcached에서 timed wait가 필요한 부분은 아래 두 가지 동작 입니다.
- 처음 구동 시 zookeeper_init
- rejoin 동작에서 zookeeper_init
처음 구동 시 zookeeper_init은 azk_count 값이 0으로 의도한 대로 동작하지만,
rejoin 동작에서 zookeeper_init은 azk_count 값이 이미 `< 0`일 가능성이 있어
0으로 초기화 한 뒤 rejoin 동작을 수행해야 합니다.
`< 0`일 가능성은, 기존에 연결되어있던 zookeeper의 session state가
네트워크 상황에 따라 "CONNECTED -> CONNECTING -> CONNECTED"로 상태 변이가 가능하며
CONNECTED session event를 받을 때 마다 `inc_count(-1)`을 수행해주기 때문에 `< 0`일 수 있습니다.
CONNECTED session event 처리에서 현재 연결이 완료된 상태에서 상태 변이인지,
새롭게 연결을 요청한 상태에서 상태 변이인지 구분해서 새롭게 연결을 요청한 상태에서만
`inc_count(-1)`을 수행해도 되지만 구분을 위해 별도로 변수가 필요하고,
평소에는 정확하게 유지할 필요가 없는 값이므로 rejoin 동작에서 clear 하고 수행하는 방식으로 수정 했습니다.
@jhpark816 …
> FIX: clear azk_count during zookeeper rejoin process

- engines/default/items.c
snprintf 시에 널문자까지 계산하여 size를 계산해야합니다. 문자열 크기가 최대일 때 개행문자가 제대로 버퍼에 들어가지 않는 문제가 발생할 수 있어서 수정하였습니다.
> FIX: miscalculation of snprintf string size

- engines/default/cmdlogbuf.c
#471 관련 PR 입니다.
checkpoint 실패 후 dual_write 설정되더있던 모든 flush request에 대해 cleanup하는 로직에서,
flush queue가 가득 차 있을 경우 fque 모든 index의 `nflush > 0`이므로 무한 루프 버그가 있습니다.
모든 index를 체크한 뒤 break하는 방식으로 버그 해결 했습니다.
@SuhwanJang 
@jhpark816 
확인 요청 드립니다.
> [persistence] fix an infinite loop bug when flush queue was full

- memcached.c
- t/getset.t
- t/lru.t
- t/set_with_largest_slab.t
E2BIG 에러는 (1) 엘리먼트 크기가 제한(16K)보다 큰 경우 (2) 아이템 크기가 slab largest class 보다 큰 경우 발생합니다.
(1)은 CLIENT_ERROR로 반환하고 있는데,
```
static void process_sop_prepare_nread(conn *c, int cmd, size_t vlen, char *key, size_t nkey)
{
if (vlen > MAX_ELEMENT_BYTES) {
ret = ENGINE_E2BIG;
...
if (ret == ENGINE_E2BIG)       out_string(c, "CLIENT_ERROR too large value");
}
```
(2)는 PR 코드에서 보듯이 SERVER_ERROR로 반환하고 있습니다.
(2)도 (1)과 같이 요청 데이터가 적절하지 않아 발생한 에러이므로, CLIENT_ERROR로 리턴해야 한다고 봅니다.
```
static ENGINE_ERROR_CODE
default_item_allocate(ENGINE_HANDLE* handle, const void* cookie,
item **item,
const void* key, const size_t nkey,
const size_t nbytes,
const int flags, const rel_time_t exptime,
const uint64_t cas)
{
struct default_engine* engine = get_handle(handle);
size_t ntotal = sizeof(hash_item) + nkey + nbytes;
if …
```
> FIX: appropriate to set E2BIG error as a CLIENT_ERROR

- engines/default/items.c
Issue : https://github.com/naver/arcus-memcached/issues/477
```
추가된 3개 문자 포함하여 출력하는 전체 길이가 MAX_HKEY_LEN이었으면 합니다.
```
위 요구사항에 대해 null character를 고려(포함)하여 처리하였습니다.
> FIX: prevent memory out-of-range while printing out key on log.

- engines/default/items.c
- engines/demo/dm_items.c
- t/item_size_max.t
#490 관련 PR 입니다.
ARCUS-memcached는 구동 옵션(-I)으로 item의 최대 크기 제한을 변경할 수 있지만,
기존 default engine과 demo engine에서 value의 최대 크기를 1MB로 제한하는 버그가 있었습니다.
do_item_link에서 value size는 이미 item allocate 에서 item_size_max보다 작음이 확인된 값으로,
중복으로 확인할 필요가 없을 것으로 판단되어 제거 했습니다.
@jhpark816 
확인 요청 드립니다.
> FIX: reflect item_size_max setting

- doc/arcus-ascii-protocol.md
- doc/arcus-basic-concept.md
- doc/arcus-collection-concept.md
- doc/arcus-item-attribute.md
- doc/arcus-telnet-interface.md
- doc/command-administration.md
- doc/command-btree-collection.md
- doc/command-item-attribute.md
- doc/command-key-value.md
- doc/command-list-collection.md
- doc/command-map-collection.md
- doc/command-pipelining.md
- doc/command-set-collection.md
문서 시스템과의 양식을 맞추기 위해 PR 합니다.
- 수정 내용
- 목차에서 최상위 제목을 제외시키기 위해 h1(#)으로 설정
- 제목에 챕터 번호 부여
- 굵은 글씨(**) 였던 부분을 제목(###)으로 변경(목차에 노출시키기 위함)
챕터 번호는 관련 이슈에서 지정한 대로([링크](https://github.com/jam2in/arcus-memcached-EE/issues/854#issuecomment-545372695)) 붙인 것인데 arcus-ascii-protocol과 arcus-collection-concept는 챕터 구성에서 빠진 상태 입니다. (문서시스템에도 노출하지 않고 있음.) 그래서 일단 챕터 번호를 붙이지 않고 PR합니다.
arcus-ascii-protocol의 경우 문서간 navigation용으로 제공되는 문서로 보여서 사이드바로 전체 목차가 제공되는 문서시스템에는 노출할 필요가 별로 없다고 생각합니다.
반면 arcus-collection-concept 에는 꽤 중요한 내용이 있습니다. bkey가 hex형과 정수형으로 나누어진다는 정보는 btree 문서에는 없고 여기에만 있습니다. 관련 내용을 btree로 옮기던지 정식 챕터로 편입하던지 하는 것이 좋을 듯 합니다.
> DOC: fix document style to sync with the document system

- README.md
- doc/ch04-command-key-value.md
- README의 링크가 작동하도록 수정
- 문서시스템에서 memcached protocol을 볼 수 있도록 깃허브 링크로 수정
- 문서 시스템은 markdown 파일로 웹페이지를 생성하므로 txt 파일은 접근 불가 (github repo에 넣어놔도 페이지가 생성되지 않음)
> DOC: fix wrong link

- doc/ap01-arcus-telnet-interface.md
- doc/ch00-arcus-ascii-protocol.md
- doc/ch01-arcus-basic-concept.md
- doc/ch02-collection-items.md
- doc/ch03-item-attributes.md
- doc/ch04-command-key-value.md
- doc/ch05-command-list-collection.md
- doc/ch06-command-set-collection.md
- doc/ch07-command-map-collection.md
- doc/ch08-command-btree-collection.md
- doc/ch09-command-pipelining.md
- doc/ch10-command-item-attribute.md
- doc/ch11-command-administration.md
github markdown에서 H1(#) 수준의 제목은 자동으로 구분선이 생기기 때문에 별도로 그어져 있던 구분선을 제거하였습니다.
> DOC: remove unnecessary line

- doc/ch05-command-list-collection.md
- doc/ch06-command-set-collection.md
- doc/ch07-command-map-collection.md
- doc/ch08-command-btree-collection.md
list item 표기 도중 들여쓰기를 할 경우, 문서시스템에서는 인용문으로 처리되는 문제가 있어 들여쓰기를 제거하였고, develop 브랜치와의
참고로 들여쓰기를 제거해도 github에서 보이는 문서의 view는 그대로 입니다. 기존 문서도 raw 파일 상에서는 들여쓰기가 되어있지만 한 줄로 붙어나오고 있습니다. 수정한 결과도 마찬가지입니다. 한 줄로 쭉 붙여써도 되지만, 라인이 너무 길어지면 raw file을 볼 때 불편한 점이 있으므로 개행은 유지했습니다. 
merge되면 문서시스템에 반영하겠습니다.
> DOC: fix indentation of list items

- doc/ch02-collection-items.md
- doc/ch07-command-map-collection.md
- doc/ch11-command-administration.md
수정 사항
- 불필요한 공백 제거
- \<\> 사이에 공백을 넣는 것은 이전에 쓰던 툴에서 부등호 사이의 문자가 보이지 않는 현상이 있었기 때문인데, 현재 툴에선 공백을 넣지 않아도 escape만 하면 잘 보임.
- escape 문자 추가
- escape 없이 \<\>를 사용한 곳 수정(escape 문자 없을 시 표기되지 않음)  
- list item indentation 시 quote box 생기는 현상(이전 PR에서 누락됨)
> DOC: cleanup docs style and contents

- engines/default/assoc.c
- engines/default/assoc.h
- engines/default/items.c
- engines/default/prefix.c
do_item_replace() 함수를 최적화 하였습니다.
기존의 item_unlink(), item_link() 함수를 호출하는 방식에서
replace 함수 이름에 맞게 대체 해주는 방식으로 최적화 하였습니다.
- assoc_replace() 함수 생성 및 대체하는 과정에서 일어나는 불필요한 코드 제거
- prefix_replace() 함수 생성 및 대체하는 과정에서 일어나는 불필요한 코드 제거
- do_item_stat_replace() 함수를 생성 및 stotal 변경 사항을 한번에 적용함으로써 최적화
> ENHANCE: optimize do_item_replace()

- README.md
- arcus_zk.c
- configure.ac
ZooKeeper dynamic reconfiguration 기능 지원을 위한 PR 입니다.
arcus-memcached에서 zk reconfig 기능을 enable 하기 위해 `--with-zk-reconfig` 구동 옵션을 추가 했습니다.
reconfig code는 ENABLE_ZK_RECONFIG code tag로 관리하며 `--with-zk-reconfig` 옵션으로 컴파일 되도록 했습니다.
zookeeper 3.5 버전부터는 컴파일 옵션에 `THREADED` 를 추가해야 multi thread mode로 동작할 수 있어 컴파일 옵션을 추가 했습니다.
zookeeper initialize 시점에 `/zookeeper/config` znode와 data를 조회하고
reconfig watcher를 enable/disable 합니다.
조회한 configuration data는 필요한 정보들을 parsing 하고 현재 version과 비교하여,
변경이 필요한 경우만 ZK server list를 업데이트 하도록 했습니다.
config data가 잘못되었을 때 에러 핸들링은,
watcher는 유지하는 상태에서 ZK server list에 반영하지 않도록 했습니다.
@minkikim89 @jhpark816 
확인 요청 드립니다.
> FEATURE: support zookeeper dynamic reconfiguration

- arcus_zk.c
zkreconfig 기능 추가 commit의 리뷰 과정에서 도입된
zkconfig buffer를 zk destroy 할 때 free 해주도록 추가 했습니다.
@jhpark816 
확인 요청 드립니다.
> FIX: free zkconfig buffers when zk is destroyed

- Makefile.am
- engines/default/checkpoint.c
- engines/default/cmdlogbuf.c
- engines/default/cmdlogbuf.h
- engines/default/cmdlogfile.c
- engines/default/cmdlogfile.h
- engines/default/cmdlogmgr.c
#410 관련 PR 입니다.
아래와 같은 부분이 수정되었습니다.
- Log buffer 및 log flusher 모듈을 cmdlogbuf 모듈로 분리
- cmdlogbuf.c, cmdlogbuf.h
- Log file write/sync 모듈을 cmdlogfile 모듈로 분리
- cmdlogfile.c, cmdlogfile.h
- Makefile.am에 cmdlogfile 모듈 관련 파일 추가
- cmdlogbuf.c 내 각 함수들의 기존 구현 방식은 유지하였으나, 모듈 분리로 인한 몇가지 수정 사항 아래 작성:
- 두 모듈이 `log_GLOBAL log_gl`을 공유해, 기존 static한 방식에서 포인터로 접근하도록 수정
- `cmdlog_buf_init`에서 `malloc` 실패해 `ENGINE_ENOMEM`을 return 해야하는 상황 발생 시, `free(log_gl)` 하도록 추가
- `cmdlog_buf_final` 시 `free(log_gl)` 추가
- cmdlogfile 모듈에서 logger 사용을 위해, `cmdlog_file_init` 시 `engine`도 파라미터로 전달
- cmdlogfile 모듈을 사용하는 checkpoint.c 및 cmdlogmgr.c에 헤더파일 추가
`make test` PASS 확인하였고, [Persistence Guide](https://github.com/naver/arcus-memcached/wiki/Persistence-Guide) 참고해 telnet으로 정상 동작 확인했습니다.
리뷰 요청 드립니다.
> [persistence] separate the cmdlogfile module from cmdlogbuf.c

- engines/default/checkpoint.c
- engines/default/cmdlogbuf.c
- engines/default/cmdlogbuf.h
- engines/default/cmdlogfile.c
- engines/default/cmdlogfile.h
checkpoint thread가 log file close 시에 대기하는 기능 제거 https://github.com/naver/arcus-memcached/issues/514 PR 입니다.
변경된 사항은 다음과 같습니다.
- cmdlog_file_close() 에서 chkpt_success 시 file_close wait 로직 제거
- next checkpoint 는 prev checkpoint 의 logfile close 이후 수행
- logfile close 확인 함수 정의 : cmdlog_file_dual_write_finished() (prev_fd == -1 && next_fd == -1)
- checkpoint main thread logic 에서 이를 확인
- do_checkpoint()에서 cmdlog_file_close() 이후 수행하는 remove_chkpt_files 조건 변경
- 스냅샷 실패 시에만 수행. 
- 스냅샷 성공한 경우는 prev_time(previous checkpoint time) 만 설정. 이 필드 사용 목적은 previous log file close 이후에 remove_chkpt_files 를 수행하기 위함임. checkpoint 주기에서 prev_time != -1 인 경우 cmdlog_file_dual_write_finished=true 인 경우 remove_chkpt_files(prev_time) 수행
> [persistence] removed logfile close wait in checkpoint

- engines/default/checkpoint.c
백업 파일이 없는 상태에서 엔진을 구동시킨 경우 redo 단계에서 수행하는 checkpoint 성공이 보장되어야 합니다. 
현재 조건 체크로는 CHKPT_ERROR_FILE_REMOVE 에러를 확인할 수 없습니다.
```
/* FIXME : Error handling(Disk I/O etc) */
static int do_checkpoint(chkpt_st *cs)
{
int ret;
int64_t newtime = getnowtime();
do {
if ((ret = do_chkpt_create_files(cs, newtime)) != 0) {
break;
}
if ((ret = cmdlog_file_open(cs->cmdlog_path)) != 0) {
if (do_chkpt_remove_files(cs, newtime) < 0) {
ret = CHKPT_ERROR_FILE_REMOVE;
}
break;
}
if (mc_snapshot_direct(MC_SNAPSHOT_MODE_CHKPT, NULL, -1,
cs->snapshot_path, &cs->lastsize) == ENGINE_SUCCESS) {
cs->prevtime = cs->lasttime;
cs->lasttime = newtime;
ret = CHKPT_SUCCESS;
} else {
ret = CHKPT_ERROR;
}
```
> [persistence] checked checkpoint success at chkpt_recovery_redo()

- engines/default/cmdlogbuf.c
- engines/default/cmdlogfile.c
파일 접근 동시성 보장 시 flush_lock 대신 별도 lock 사용 (https://github.com/naver/arcus-memcached/issues/515) PR 입니다.
파일 접근 동시성 보장을 log_flush_lock 대신 file_access_lock 을 사용하도록 변경하였습니다. 
- 파일 접근 동시성을 주의해야 하는 모듈은
- fsync 모듈의 cmdlog_file_sync()
- flush 모듈에서 dw_end 까지 flush 완료하고 fd를 변경하는 cmdlog_file_complete_dual_write()
- checkpoint 모듈에서 snapshot 실패 시 호출하는 cmdlog_file_close() 인데,
- file_access_lock 으로 변경해도 함수 호출 시점과 fd 변경 시점을 따져봤을 때 문제 없다고 판단했습니다.
cmdlogbuf 모듈에서의 log_flush_lock 사용 코드 변경은 현재 커밋 검토가 끝난 후 변경하겠습니다.
- log_flush_lock 정의 위치를 log_buffer 구조체로 
- extern 제거
> [persistence] added file_access_lock to guarantee logfile concurrency

- engines/default/cmdlogbuf.c
- engines/default/cmdlogbuf.h
file_access_lock 이 추가되었으므로 log_flush_lock 은 logbuffer 모듈에서만 사용하도록 변경하였습니다.
- logfile init/final 수행 위치를 cmdlogmgr 모듈로의 변경은 다른 PR 로 하겠습니다.
> [persistence] used log_flush_lock as a field of log_buff_gl

- engines/default/cmdlogbuf.c
- engines/default/cmdlogmgr.c
logfile 은 logbuffer 모듈과 decoupling 되었으므로 logfile init/final 을 cmdlogmgr 에서 수행합니다.
> [persistence] init/final cmdlogfile in cmdlogmgr module

- engines/default/checkpoint.c
- engines/default/cmdlogbuf.c
- engines/default/cmdlogbuf.h
- engines/default/cmdlogfile.c
- engines/default/cmdlogfile.h
cmdlog_get_file_size() 함수 재검토 (issue: https://github.com/naver/arcus-memcached/issues/522) PR 입니다.
- logbuffer 모듈의 cmdlog_get_file_size() 함수를 제거하였습니다.
- cmdlog_file_dual_write_finished()==true 이후에 해당 함수가 호출되므로, dw_end == -1 인 상태이어서 해당 값을 확인할 필요가 없음.
- logfile 모듈의 cmdlog_get_current_file_size() 함수명을 cmdlog_file_getsize() 로 변경하였습니다.
- 이전 함수 명이 낫다면 roll back 하겠습니다.
> [persistence] removed cmdlog_get_file_size()

- engines/default/checkpoint.c
- engines/default/checkpoint.h
- engines/default/cmdlogbuf.c
- engines/default/cmdlogbuf.h
- engines/default/cmdlogfile.c
- engines/default/cmdlogfile.h
- engines/default/cmdlogmgr.c
cmdlog_complete_dual_write() 함수 재검토.https://github.com/naver/arcus-memcached/issues/521 PR 입니다.
complete_dual_write 는 checkpoint 스레드에 의한 checkpoint 일 때만 수행하도록 다음과 같이 변경하였습니다.
- checkpoint lasttime 값을 확인하여 -1 이 아닐 때 chkpt_scanp 를 set.
- chkpt_scanp 가 set 되지 않았다면, chkpt_scanp_close() 호출되지 않으므로 complete_dual_write() 수행하지 않음.
> [persistence] set chkpt_scanp when checkpoint lasttime is set

- Makefile.am
- engines/default/default_engine.conf
Nushaba 리뷰 받아서 엔진 설정 파일(default_engine.conf) 를 추가하였습니다. (https://github.com/jam2in/arcus-works/issues/252)
- default_engine.conf 경로는 engines/default/default_engine.conf
- make 명령에 따른 default_engine.conf 처리 (tested) :
- make install : $(prefix)/conf 디렉토리로 복사됨 (conf 디렉토리 없으면 생성). 
- make uninstall : $(prefix)conf 디렉토리에 있는 only default_engine.conf 삭제. 
- make dist : tar 파일에 default_engine.conf 가 기존 경로 그대로 포함되어 있음.
- Makefile.am 수정 사항 설명
```
engineconfdir=$(prefix)/conf
dist_engineconf_DATA=
```
**engineconfdir** 은 make install/uninstall 시에 생성/제거할 engineconf 파일의 directory path입니다.
**dist_engineconf_DATA** 는 `${prefix}_XX_${primary}` 와 같은 형태로, XX는 파일이 설치될 경로(lookup XXdir)를 의미하고 prefix 와 primary 아래와 같은 역할을 하는 symbol입니다.
- primary : primary 는  _PROGRAMS, _SCRIPTS, _DATA, _LIBRARIES 등으로 명시할 수 있고 …
> FEATURE: added default_engine.conf file to set engine settings on file.

- engines/default/items.c
scan loop 에서 erst_array 를 재사용하므로 elem_count=0 초기화가 필요합니다.
다음 스캔에서 kv item 이 item_array 에 들어간다면 문제가 됩니다.
first scan :
item_array : [coll]
erst_array.elem_count : [10]
second scan :
item_array : [kv]
erst_array.elem_count : [10] //coll_elem_get_all() 수행 안되어 이전 데이터가 남아있는 상태.
=> item_scan_release 에서 assert(IS_COLL_ITEM(it)) 발생.
> FIX: reset elem_count of erst_array in item_scan_release().

- engines/default/items.c
coll_elem_get_all() 에서 element 가 없는 경우 ENGINE_ELEM_ENOENT 가 리턴될 수 있는데,
`ret != ENGINE_SUCCES ` 로 확인하면  ENGINE_ELEM_ENOENT 도 OUT OF MEMORY 로 처리하는 문제가 잇습니다.
```
ENGINE_ERROR_CODE coll_elem_get_all(hash_item *it, elems_result_t *eresult, bool lock_hold)
{
coll_meta_info *info;
ENGINE_ERROR_CODE ret = ENGINE_SUCCESS;
if (lock_hold) LOCK_CACHE();
do {
if (!IS_COLL_ITEM(it)) {
ret = ENGINE_EBADTYPE; break;
}
info = (coll_meta_info*)item_get_meta(it);
if (info->ccnt <= 0) {
ret = ENGINE_ELEM_ENOENT; break;
}
/* init and check result */
if (eresult->elem_arrsz < info->ccnt) {
uint32_t new_size = GET_ALIGN_SIZE(info->ccnt, 100);
if (do_coll_eresult_realloc(eresult, new_size) < 0) {
ret = ENGINE_ENOMEM; break;
}
```
> FIX: set item_count to -2 only ENGINE_ENOMEM in item_scan_getnext().

- engines/default/cmdlogrec.c
issue : log record debug print 에서 exptime 을 (absolute -> relative) 로 변환하여 출력 https://github.com/naver/arcus-memcached/issues/544
lrec_XXX_print() 에서 exptime 을 relative 형태로 출력하도록 수정하였습니다.
> [persistence] printed exptime with relative form in lrec_XXX_print().

- _run_memcached_solo.sh
- 기존 _run_memcached_solo.sh script에 현재 script가 실행되는 경로를 획득하여 상대 경로를 절대 경로로 실행하도록 변경하였습니다.
> FIX: update _run_memcached_solo.sh script

- engines/default/assoc.c
- engines/default/assoc.h
#546 관련 PR입니다. 
해쉬 테이블 확장/재분배 시 다음과 같이 로그를 남깁니다.
1. 재분배를 위해 assoc_expand를 실행했을 때 (전/후 rootsize 기록)
2. 재분배가 50% 진행되었을 때
3. 재분배가 종료되었을 때 
확장의 진행 정도와 종료 여부를 알 수 있으려면 재분배된 버켓이 몇 개인지 셀 필요가 있으므로 관련 변수를 추가 했습니다.(assocp->redistributed_bucket_cnt)
> FEATURE: add redistribution logs

- engines/default/item_base.c
macOS mojave(10.14.5), LLVM 10.0.1 환경에서 develop 브랜치를 컴파일 했을 때 implicit-function-declaration warning이 발생합니다.
```
engines/default/item_base.c:307:5: error: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Werror,-Wimplicit-function-declaration]
memset(itemsp->itemstats, 0, sizeof(itemsp->itemstats));
^
engines/default/item_base.c:307:5: note: include the header <string.h> or explicitly provide a declaration for 'memset'
engines/default/item_base.c:956:9: error: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
memcpy((void*)item_get_key(it), key, nkey);
^
engines/default/item_base.c:956:9: note: include the header <string.h> or explicitly provide a …
```
> FIX: add header

- memcached.c
- 기존 exptime 값을 처리하는 realtime 함수에서 exptime 값이 -1 보다 더 작은 음수 값에 대한 예외 처리를 추가하였습니다.
> CLEANUP: fix realtime function

- engines/default/items.c
- engines/default/prefix.c
- engines/default/prefix.h
- include/memcached/types.h
- stats.c
- t/nested_prefix.t
- t/tlist/engine_default_b.txt
- t/tlist/engine_default_s.txt
Nested prefix 기능 지원을 위한 PR입니다.
types.h에 NESTED_PREFIX 추가하여, 수정한 부분은 태그로 처리했습니다.
기능 검증을 위해, issue_486.t 파일을 추가하였습니다.
해당 파일에서는 prefix 3개 child prefix 4개를 각각 만들어. prefix 3개를 flush하면 child prefix 또한 사라지는지 확인하였습니다.
-> 총 12개 prefix 생성. prefix 3개만 flush 시, 모든 child prefix들도 flush되는지 확인.
prefix.c
"stats prefixes" 수행 시, prefix 개수만 나오도록 추가했습니다.
그리고 prefix_link(), prefix_unlink(), perfix_bytes_infr(), prefix_bytes_decr(), prefix_isvalid()부분의 주석을 해제하였습니다.
stats.c
stats_prefix_find()에서 nested prefix로 key값을 주었을 때에, 기존 코드로 실행 시에는, 
if(!mc_isvalidname(key, length))로 실행이 넘어가 적절한 실행이 되지 않았지만,
if(length > 0) 부분을 if (length > 0 && prefix_depth == 1) 부분으로 바꾸어 nested prefix로 key값을 주었을 때에도 정상동작하도록 수정하였습니다.
@minkikim89
확인 요청 드립니다.
> FEATURE : support nested prefix

- engines/default/checkpoint.c
- engines/default/checkpoint.h
- engines/default/default_engine.c
- memcached.c
ARCUS의 default 엔진에는 엔진 동작에 관한 설정들을 가지는 default_engine.conf 파일이 있으며, 그 파일에서 아래와 같은 Persistence 관련 설정을 할 수 있습니다.
```
#
use_persistence=true
#
data_path=/home/hyeong/arcus/ARCUS_DB
#
logs_path=/home/hyeong/arcus/ARCUS_DB
#
async_logging=false
#
chkpt_interval_pct_snapshot=100
#
chkpt_interval_min_logsize=256
```
stats persistence 명령의 수행 결과는 use_persistence 값(on or off)에 따라 달라집니다.
use_persistence on 이면, 응답은 다음과 같습니다.
( STAT chkpt_interval_min_logsize (unit: B))
```
STAT use_persistence on
STAT data_path /home/hyeong/ARCUS_DB
STAT logs_path /home/hyeong/ARCUS_DB
STAT async_logging false
STAT chkpt_interval_pct_snapshot 100
STAT chkpt_interval_min_logsize 268435456
STAT recovery_elapsed_time_sec 0.000047
STAT last_chkpt_in_progress false
STAT last_chkpt_failure_count 0
STAT …
```
> FEATURE: added stats persistence command.

- engines/default/checkpoint.c
stats persistence 명령의 수행 결과 중 STAT chkpt_interval_min_logsize와 관련하여 
unit: B에서 unit:MB로 출력되도록 변환하였습니다.
STAT use_persistence on
STAT data_path /home/hyeong/ARCUS_DB
STAT logs_path /home/hyeong/ARCUS_DB
STAT async_logging false
STAT chkpt_interval_pct_snapshot 100
STAT chkpt_interval_min_logsize 256
STAT recovery_elapsed_time_sec 0.000047
STAT last_chkpt_in_progress false
STAT last_chkpt_failure_count 0
STAT last_chkpt_start_time 0
STAT last_chkpt_elapsed_time_sec 0.000000
STAT last_chkpt_snapshot_filesize_bytes 321600208
STAT current_command_log_filesize_bytes 0
> FEATURE: changed the unit of chkpt_interval_min_logsize. 

- engines/default/default_engine.c
- include/memcached/types.h
- memcached.c
체크포인트 수행 조건과 명령 로깅 모드 설정은 use_persistence 값(on or off)에 따라 달라집니다.   
use_persistence off 이면, 응답은 다음과 같습니다.
```
config chkpt_interval_min_logsize
ERROR not using Persistence
config chkpt_interval_pct_snapshot
ERROR not using Persistence
config async_logging
ERROR not using Persistence
```
use_persistence on 이면, 응답은 다음과 같습니다.
( chkpt_interval_pct_snapshot의 경우 0 < chkpt_interval_pct_snapshot <= 100의 범위를 설정하였습니다.)
```
config chkpt_interval_pct_snapshot
chkpt_interval_pct_snapshot 100
END
config chkpt_interval_pct_snapshot 200
CLIENT_ERROR bad value
config chkpt_interval_pct_snapshot 40
END
config chkpt_interval_pct_snapshot
chkpt_interval_pct_snapshot 40
END
```
stats persistence 명령어를 통해서도 다음과 같이 변경된 값을 조회할 수 있습니다.
```
stats persistence
STAT use_persistence on
STAT data_path …
```
> FEATURE: added config command for changing the persistence setting

- engines/default/chkpt_snapshot.c
compile시 format-overflow warning 발생시키는 코드를 수정하였습니다.
- do_snapshot_stats() 함수에서 val 버퍼 크기를 256 => 4096으로 증가.
> INTERNAL: increased val buffer size in do_snapshot_stats().

- engines/default/assoc.c
exp_bucket 의 값은 hashsize-1 으로 설정해야 맞는 것 같습니다.
> FIX: set exp_bucket to hashsize-1.

- arcus_zk.c
arcus_zk_client_init() 에서는 main_zk 가 아직 설정되지 않은 상태이므로 zinfo 사용하도록 수정하엿습니다.
```
rc = arcus_zk_client_init(zinfo);
if (rc != 0) {
arcus_conf.logger->log(EXTENSION_LOG_WARNING, NULL,
"Failed to initialize zk client\n");
arcus_exit(NULL, rc);
}
/* setting main zk */
main_zk = zinfo;
```
> FIX: main_zk is not set yet in arcus_zk_client_init()

- engines/default/cmdlogbuf.c
async mode 에서는 32KB 단위로 log records flush 를 수행하기 때문에 이 단위만큼 채워지지 않은 경우 일부 log records 가 디스크에 쓰여지지 않은 채로 서버가 종료될 수 있는 문제를 수정하였습니다.
> FIX: in async mode, log records may remain in flush size.

- engines/default/checkpoint.c
체크포인트 파일 사이즈를 64bit 로 출력하도록 수정하였습니다.
> FIX: print checkpoint file size stat in 64bit.

- arcus_zk.c
이슈 : https://github.com/jam2in/arcus-works/issues/277#issuecomment-770499451 zoo.cfg 3.4 포맷 사용 관련 PR 입니다.
client port 를 zoo.cfg.dynamic 이 아닌 zoo.cfg 에 넣어서 사용하면 ZK config data 에 client port 가 없어 zoo_set_servers() 를 수행할 수 없습니다.
운영자가 zoo.cfg 와 zoo.cfg.dynamic 파일을 확인하여 조치하도록 invalid ZK config data message 를 보강하였습니다.
> CLEANUP: invalid ZK config data message more specifically.

- arcus_hb.c
arcus_zk.c 에서 hb 모듈이 분리된 후 수정되지 않은 주석이 있어 수정하였습니다.
> CLEANUP: fixed typo in arcus_hb.c

- arcus_zk.c
- arcus_zk.h
- memcached.c
zookeeper 상태 조회 전용 명령을 추가하였습니다. (issue : https://github.com/jam2in/arcus-works/issues/277#issuecomment-819324187)
해당 명령에서 zk reconfig 상태도 조회할 수 있습니다.
```
stats zookeeper 
STAT zk_connected true
STAT zk_failstop on
STAT zk_timeout 30000
STAT zk_reconfig on
STAT zk_reconfig_version 100000000
```
두 개의 커밋으로 PR 하였습니다. 
첫번째는 zookeeper 상태 조회 전용 명령 추가 두번째는 zk reconfig 상태 조회를 추가하였습니다.
>  FEATURE: added stats zookeeper command.

- doc/ch11-command-administration.md
stats zookeeper 명령 설명 문서를 추가하였습니다.
코드 적용된 모습은 https://github.com/SuhwanJang/arcus-memcached/blob/develop/doc/ch11-command-administration.md 에서 확인하실 수 있습니다.
> DOC: added stats zookeeper document.

- arcus_zk.c
gcc 상위버전으로 컴파일하면 다음 에러가 발생합니다.
```
arcus_zk.c: In function ‘arcus_create_ephemeral_znode.part.1’:
arcus_zk.c:645:43: error: ‘%s’ directive output may be truncated writing up to 199 bytes into a region of size 182 [-Werror=format-truncation=]
snprintf(zpath, sizeof(zpath), "%s/%s/%s", zk_root, zk_log_dir, sbuf);
^~                        ~~~~
arcus_zk.c:645:5: note: ‘snprintf’ output 19 or more bytes (assuming 218) into a destination of size 200
snprintf(zpath, sizeof(zpath), "%s/%s/%s", zk_root, zk_log_dir, sbuf);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arcus_zk.c:659:47: error: ‘%s’ directive output may be truncated writing up to 199 bytes into a region of size 182 [-Werror=format-truncation=]
snprintf(zpath, sizeof(zpath), "%s/%s/%s/%s-",
^~
zk_root, …
```
> FIX: fixed format-truncation compile error in arcus_zk.c

- Makefile.am
CentOS8 환경에서 make 시 libarcuszk.a : No such file or directory 에러 https://github.com/jam2in/arcus-works/issues/296
상위 빌드 툴에서는 PROGRAMS가 LIBRARIES 보다 먼저 compile 되므로 
```
all-am: Makefile $(PROGRAMS) $(LIBRARIES) $(LTLIBRARIES) $(DATA) \
$(HEADERS) config.h
```
libarcuszk.a 를 DEPENDENCIES 에 추가하여 먼저 컴파일 되도록 하였습니다.
참고로, CentOS7에서는 아래 순서로 만들어집니다.
```
all-am: Makefile $(LIBRARIES) $(LTLIBRARIES) $(PROGRAMS) $(DATA) \
$(HEADERS) config.h
```
> FIX: libarcuszk.a sets memcached_DEPENDENCIES for compile ahead.

- thread.c
cqi_new() 에서 malloc 실패하면 item 은 NULL 이 됩니다.
이후 수행하는 item access 시에 segfault 발생할 수 있는 문제가 있습니다.
참고) memcached.c open source code :
- thread.c : https://github.com/memcached/memcached/blob/master/thread.c#L670
> FIX: handled memory allocation failure for connection object.

- lqdetect.c
- lqdetect.h
- memcached.c
lqdetect 모듈에서 mc_logger 설정하지 않고 사용하는 문제가 있습니다.
> FIX: missing to set logger in lqdetect.

- engines/default/coll_list.c
- engines/default/coll_list.h
- engines/default/default_engine.c
- engines/default/default_engine.h
- engines/default/item_base.c
- engines/default/item_base.h
- engines/default/items.c
Large value item 저장 기능을 추가하였습니다.
- large value 요청으로 최소 64KB 이상, 최대 64MB 이하 크기의 item 까지 지원하도록 설계하였습니다.
- large value를 저장할 때 내부 구현체는 list를 활용하였기 때문에 기존 list 함수들을 응용할 수 있도록 수정하였습니다.
기존 key value item에 대한 기능(set, get, delete, add, relace, attach, cas)들을 지원하도록 구현하였습니다.
- large item의 element에 대한 삭제 요청은 일반 collection item과 동일하게 collection_delete_thread()에서 처리하도록 구현하였습니다.
- large item의 hash item은 기존 list의 hash item 구조에서 CRLF 정보(value_item 타입)를 추가한 구조로 설계하였습니다.
large item의 저장 구조입니다.
관련 추가 기능에 대한 진행은 아래와 같습니다.
- CLOG 관련 동작은 다른 pr에서 요청할 예정입니다. 현재 large item일 때는 CLOG 동작 수행하지 않도록 구현하였습니다.
- large value 의 값을 임시 저장할 버퍼에 대한 pointer array pool 관련 코드는 다른 pr에서 요청할 예정입니다. 현재 임시로 구동할 수 있게 구현하였습니다.
> FEATURE: supported large value set feature

- memcached.c
- thread.c
event_init()은 deprecated 될 API 이므로, event_base_new() 로 변경하였습니다.
```
/**
Initialize the event API.
The event API needs to be initialized with event_init() before it can be
used.  Sets the global current base that gets used for events that have no
base associated with them.
@deprecated This function is deprecated because it replaces the "current"
event_base, and is totally unsafe for multithreaded use.  The replacement
is event_base_new().
@see event_base_set(), event_base_new()
*/
EVENT2_EXPORT_SYMBOL
struct event_base *event_init(void);
```
동작 테스트 확인하였습니다.
> INTERNAL: replaced event_init() to event_base_new().

- engines/default/mem_pool.c
- engines/default/mem_pool.h
Large item 저장 과정에서 필요한 memory pool 코드를 추가하였습니다.
- memory pool 은 한번에 최대 16MB 크기의 large item을 담을 수 있습니다.
- pool 은 한번에 1000개까지 동시에 사용될 수 있습니다.
- pool 의 각 pointer array에 대한 할당 상태 확인은 pool_id 값을 통해 확인합니다.
- pool_id 가 -1 이면 할당되지 않은 상태, 0 이면 pool 외에 새로 malloc 한 상태, 양수이면 pool 에서 사용중이지 않은 메모리를 할당 받은 상태입니다.
- pool 의 공간이 모두 사용되었거나 pool 에서 제공하는 공간보다 큰(16MB 이상) large item 이 요청되면 새로 malloc을 해서 공간을 할당해줍니다.
> INTERNAL: Added memory pool function as example code

- cmdlog.c
- engines/default/checkpoint.c
- include/memcached/util.h
- lqdetect.c
- util.c
getnowtime(), getnowdate() 를 lqdetect, cmdlog 모듈에서 중복으로 정의하여 사용하고 있습니다.
향후에 다른 모듈에서도 사용할 가능성이 높은 성격의 함수라서 util.c 에 구현해두고, 이를 사용하도록 리팩토링하였습니다.
> CLEANUP: use getnowtime(), getnowdate() as a util function.

- cmdlog.c
- cmdlog.h
command log file rotation 은 128MB 단위로 수행하도록 수정하였습니다.
그리고 이전 커밋에서 수정하지 않았던 일부 리팩토링 코드도 포함되어있습니다.
> CLEANUP: rotate command log file based on a set file size.

- util.c
util.c 파일에 getnowxxx_int() 함수 추가할 때 #endif 위치를 잘못 넣어서 수정하였습니다.
> FIX: fix the incorrect position of #endif.

- engines/default/default_engine.c
persistence enable compile 하고, engine->config.use_persistence == false 인 경우에 config 명령을 수행하면
ENOTSUP 에러 코드를 반환하는 버그를 수정하였습니다.
> FIX: fix a persistence code bug in config command.

- engines/default/assoc.c
- engines/default/assoc.h
- engines/default/default_engine.c
- engines/default/items.c
- engines/default/items.h
- include/memcached/engine.h
- include/memcached/types.h
- include/memcached/util.h
- memcached.c
- util.c
keyscan 명령을 개발하였습니다.
keyscan command protocol (request) :
`keyscan <cursor> [count <count>] [match <pattern>] [type <type>]`
- cursor :  default engine - 32비트 정수 :상위16비트(tabidx)/하위16비트(bucket)
- count : 1~2000 설정, 생략 시 20개.
- match : 패턴은 '\\', '*', '?' 지원, 지정하지 않을 시 모든 아이템 스캔. 패턴 매칭 비교 수행시간이 오래 걸릴 수 있으므로 아래 제약을 둠.
- 최대 패턴문자열 길이는 64자
- '*' 지정 최대 개수는 4개 
- type : 아이템 타입 지정, 지정하지 않을 시 'A' 로 설정되며 이는 모든 아이템 타입을 의미함.
keyscan command protocol (response) :
`KEYS <key count> <cursor>\r\n<line separated keys>END\r\n`
- key count
- physical bucket 단위로 스캔을 하기 때문에 주어진 count 보다 조금 클 수 있음.
- 패턴 지정 시 아이템 스캔 수행시간이 10msec 넘어가면 스캔 종료하므로 count 보다 작을 수 있음.
- cursor : 스캔 끝난 위치. 0을 응답하면 전체 해시테이블을 스캔했음을 의미함.
internal :
- 버켓 참조카운트는 하나의 명령 처리가 끝나면 반드시 해제되어 있어야 한다. 엔진 내부에서 수행하는 풀스캔과 달리 스캔 요청이 더 오지 않을 수 있다.
- 비트를 상위 …
> FEATURE: added keyscan command

- lqdetect.c
- lqdetect.h
- memcached.c
- memcached.h
lqdetect show command 코드를 리팩토링하였습니다.
- 보여줄 각 커맨드의 결과는 헤더와 바디로 구성하고, lqdetect 모듈에서 헤더 메모리 공간을 미리 만들어둡니다.
- core 모듈에서 field_t array 를 전달하면 lqdetect 모듈에서 헤더와 바디를 각각 가리키도록 하여 malloc & memcpy 없이 구현하였습니다.
> CLEANUP: refactored code of processing lqdetect show command

- lqdetect.c
- t/long_query_detect_issue.t
bkey range check 가 `to_bkey != NULL` 조건으로 잘못되어 있습니다.
to_bkey 는 static array 를 넘겨주기 때문에 NULL 이 아니므로, bkey single index 인 경우에도 항상 참입니다.
이 경우에 to_nbkey 는 BKEY_NULL(255자) 이므로 to_bkey array 의 최대 범위를 넘어서 write 하여 segfault 가 발생합니다.
> FIX: wrong bkey range check in lqdetect_make_bkeystring().

- engines/default/coll_btree.c
do_btree_elem_count() 에서 BOP_COUNT_OPTIMIZE 로직을 수행하는 경우 opcost 변수에 값 설정을 하지 않음.
이로 인해 short query 가 long query 로 분류되는 문제가 있어 처음에 0으로 초기화하여 사용하도록 수정
> FIX: use uninitialized opcost variable when lqdetect bop count.

- doc/compilation_faq.md
Install tools 항목 수정은 CentOS 8 환경에서는 하위 버전과 다르게 기본적으로 설치가 되지 않는 지 사용자가 직접 설치가 필요하여 추가하였습니다.
- perl-Test-Harness : `make test` 시 `sh: prove: command not found` 해결에 필요한 모듈
- perl-Test-Simple : `make test` 시 `Can't locate Test/More.pm in @INC (you may need to install the Test::More module)` 해결에 필요한 모듈
libevent 2.x 부터 autogen.sh 가 추가되어 실행이 필요한데 빠져있어서 추가하였습니다.
> DOC: amended compilation_faq.md.

- lqdetect.c
Mac OS 에서 컴파일 에러가 발생하여 수정하였습니다.
에러 메세지에 나온 것처럼 3번째 인자는 Literal string 로 주었습니다.
```
lqdetect.c:139:51: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
keylen = snprintf(keybuf, sizeof(keybuf), key);
^~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
__builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
^~~~~~~~~~~
lqdetect.c:139:51: note: treat the string as an argument to avoid this
keylen = snprintf(keybuf, sizeof(keybuf), key);
^
"%s",
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
__builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
^
1 error …
```
> FIX: -Wformat-security compile error.

- arcus_zk.c
ubuntu 20.04 환경에서 컴파일하면 아래의 빌드 에러가 발생됩니다.
```
arcus_zk.c: In function ‘arcus_zk_init’:
arcus_zk.c:864:41: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 200 [-Werror=format-truncation=]
864 |         snprintf(rcbuf, sizeof(rcbuf), "%s:%d", hostp, arcus_conf.port);
|                                         ^~
```
hostname의 최대 사이즈가 255 byte이기 때문에, rcbuf의 사이즈가 hostname을 담을만큼 공간이 충분하지 않아 문자열이 잘릴 것 같습니다. rcbuf 공간을 충분히 늘려 수정하였습니다.
> FIX: expand array size of rcbuf to prevent the string from being truncated

- doc/ch11-command-administration.md
- include/memcached/types.h
- memcached.c
- t/keyscan.t
- t/lib/MemcachedTest.pm
`keyscan <cursor> [count <count>] [match <pattern>] [type <type>]` 명령어를
`scan key [type <type>] <cursor> [count <count>] [match <pattern>]` 명령어로 수정했습니다.
> INTERNAL: Generalize keyscan command.

- t/keyscan.t
- t/lib/MemcachedTest.pm
keyscan 명령어의 단위 테스트에서 argument 순서가 잘못된 점을 고쳤습니다.
> INTERNAL: Fix argument order in keyscan unittest.

- t/lib/MemcachedTest.pm
단위 테스트 수행 중 이미 사용 중인 포트를 사용하면 테스트가 실패하는 현상이 있어 이미 사용 중인 포트를 사용하지 않도록 수정했습니다.
> INTERNAL: Not to use already used port.

- memcached.c
scan 명령어의 타입이 item도 아니고 prefix도 아닌 경우에 대한 에러 처리가 없던 점을 보완했습니다.
> INTERNAL: Add error handling when scan type is not item and not prefix.

- doc/ch11-command-administration.md
- memcached.c
- t/keyscan.t
- t/prefixscan.t
keyscan, prefixscan 명령어의 에러 메세지를 보강했습니다.
- count가 숫자가 아닌 값이 들어왔을 경우: CLIENT_ERROR bad count value
keyscan 명령어의 에러 메세지를 보강했습니다.
- type이 1글자가 아닌 값이 들어왔을 경우: CLIENT_ERROR bad item type
기존에는 두 경우 모두 CLIENT_ERROR bad command line format를 반환했습니다.
> INTERNAL: Enhance scan error message.

- memcached.c
```c
char buffer[100];
uint64_t num = 10;
sprintf(buffer, "%llu", num);
```
위 코드가 gcc 컴파일러에서는 foramt 워닝을 발생시키고, arcus-memcached에서는 워닝을 에러로 처리하게 되어 있어 컴파일 실패 현상이 일어나고 있습니다. 이를 "%llu" 포맷을 사용하는 다른 부분을 참고하여 다음과 같은 형태로 코드를 수정했습니다.
```c
char buffer[100];
uint64_t num = 10;
sprintf(buffer, "%llu", (unsigned long long)num);
```
> FIX: Fix error in centos 7 when format "%llu" with uint64_t.

- engines/default/items.c
- memcached.c
- t/keyscan.t
scan key 명령어에서 item의 expire time이 raw 값을 그대로 반환하는 점을 수정했습니다.
> FIX: Return human readable expire time in scan key command.

- memcached.c
`usage(void)` 함수에 구동 시 engine_config 설정을 위한 `-e` 옵션에 대한 내용을 추가했습니다.
> FIX: Add usage for -e option

- engines/default/default_engine.c
- engines/default/slabs.c
- engines/default/slabs.h
- memcached.c
hubble-v3의 grafana에서 수집하는 stat을 기본 stats 명령의 결과에 포함되도록 변경합니다.
추가되는 stats는 다음과 같습니다.
- `stats settings` 결과 중 `maxconns`
- `stats slabs` 결과 중 `total_malloced`
기존 `stats settings`, `stats slabs` 명령의 결과는 그대로 유지하며, 기본 명령의 결과만 변경됩니다.
- server_stats() 함수에 `limit_maxconns`가 추가됩니다.
- slabs_stats_basic() 함수가 추가됩니다.
- `engine_malloced`를 결과에 포함합니다.
jam2in/arcus-hubble-v3#216
> ENHANCE: Add some stats to default stats command

- engines/default/default_engine.c
- engines/default/prefix.c
- engines/default/prefix.h
- engines/demo/demo_engine.c
- include/memcached/engine.h
- memcached.c
- stats.c
- stats.h
기존의 prefix_dump_stats 함수와 stats_prefix_dump 함수에 인자를 추가합니다.
- `char *prefix_dump_stats(int *length)`
- `char *prefix_dump_stats(int *length, token_t *prefix_tokenes, const size_t nprefix_tokens)`
- `char *stats_prefix_dump(int *length)`
- `char *stats_prefix_dump(int *length, token_t *prefix_tokens, const size_t nprefix_tokens)`
해당 인자에는 입력받은 token을 넘겨 해당 prefix에 대한 정보를 리턴합니다. 해당 인자가 NULL인 경우 기존과 같이 전체 prefixes에 대한 결과를 리턴합니다.
확장된 명령어는 다음과 같이 사용할 수 있습니다.
- `stats prefixes` (기존과 동일. 전체 prefixes의 item 관련 stats 리턴)
- `stats prefixes item` (`stats prefixes`와 동일. 전체 prefixes의 item 관련 stats 리턴)
- `stats prefixes operation` (`stats detail dump`와 유사. 전체 prefixes의 operation 관련 stats 리턴)
- `stats prefixes <item/operation> <prefix1> <prefix2> ...` (주어진 prefixes의 item 또는 operation 관련 stats 리턴)
이전 버전에서 …
> FEATURE: Expand stats prefixes command

- arcus_zk.c
- jam2in/arcus-works#355
- #653 
zk config string에서 두 번째 ip가 `127.0.0.1`인 경우 이를 그대로 사용합니다.
> FIX: Use the second ip when it is 127.0.0.1

- engines/default/coll_btree.c
- engines/default/coll_list.c
- engines/default/coll_map.c
- engines/default/coll_set.c
- engines/default/default_engine.c
- engines/default/item_base.c
- engines/default/items.c
- engines/default/items.h
- engines/demo/demo_engine.c
- engines/demo/dm_items.c
- engines/demo/dm_items.h
- include/memcached/engine.h
- memcached.c
- jam2in/arcus-works#357 
- hash item allocation에서 refcount를 1로 초기화합니다.
- 이에 따라 free 대신 release를 사용하도록 변경됩니다.
- `engine->free` api가 사용되는 곳이 없으므로 제거합니다.
> FIX: Increase the refcount when allocate a hash_item

- memcached.c
- collection 명령 수행 중 conn 구조체를 통해 key string에 접근할 수 있도록
`coll_key`와 `coll_nkey`를 설정하는 시점을 변경합니다.
- binary command: binary_get_key() 수행 시점에 설정
- ascii command: KEY_MAX_LENGTH 확인 직후 설정
> INTERNAL: Set coll_key and coll_nkey earlier

- arcus_zk.c
domain name의 판단 기준을 변경합니다.
- 기존: addr 개수 1개 초과
- 변경: addr 개수 3개 이상
> FIX: Change the threshold for domain name

- config/version.pl
`git describe`를 통해 태그로부터 버전 정보를 가져올 수 없는 경우, 버전을 `UNKNOWN`으로 설정하는 대신 스크립트 실행을 중단합니다.
https://github.com/naver/arcus-memcached/blob/79571d8bd48c4f6b5256407d57f6fe6e6b1f1cb6/config/autorun.sh#L3
https://github.com/naver/arcus-memcached/blob/79571d8bd48c4f6b5256407d57f6fe6e6b1f1cb6/config/autorun.sh#L43-L46
참고할 사항으로는, arcus-c-client와는 달리 `autorun.sh`가 `die` 함수를 포함하고 있어 수정 없이도 정상 동작하고 있습니다.
필요하다면 arcus-c-client의 `autorun.sh`에 `die()`를 추가하여 기존과 동일한 구현을 유지할 수 있습니다.
- arcus-memcached와 arcus-c-client가 유사한 구조를 가질 수 있음
- arcus-memcached의 `die()`는 여러 번 사용되지만, arcus-c-client에서 `die()`를 호출하는 경우는 한 번 뿐이므로
함수를 분리하는 것에 큰 이점은 없음
> INTERNAL: Do not use UNKNOWN version

- doc/ch08-command-btree-collection.md
- 오타를 수정합니다. ~~`상래로서`~~`상태로서`
- 각 line 끝의 공백을 제거합니다.
> DOC: Fix typo and remove whitespace

- arcus_zk.c
- arcus_zk.h
- memcached.c
- jam2in/arcus-works#364
memcached에서 stats 명령을 통해 zookeeper version 정보를 조회할 수 있게 추가했습니다.
version 정보 조회 코드는 아래와 같습니다.
#define STR_INNER(x) #x
#define STR(x) STR_INNER(x)
#ifndef ZOO_VERSION
#ifdef ZOO_INHOUSE_VERSION
#define ZOO_VERSION STR(ZOO_MAJOR_VERSION) "." STR(ZOO_MINOR_VERSION) "." STR(ZOO_PATCH_VERSION) "-p" STR(ZOO_INHOUSE_VERSION)
#else
#define ZOO_VERSION STR(ZOO_MAJOR_VERSION) "." STR(ZOO_MINOR_VERSION) "." STR(ZOO_PATCH_VERSION)
#endif
#endif
Arcus 및 apache 오픈소스 zookeeper 헤더 파일에서
매크로를 통해 버전 정보를 string 형태로 변환하여 가져옵니다.
버전 string 정보가 담긴 ZOO_VERSION(현재 apache zookeeper 사용 방식)가 정의 되지 않은 경우
구버전에 정의된 ZOO_MAJOR_VERSION, ZOO_MINOR_VERSION, ZOO_PATCH_VERSION 정보,
그리고 ZOO_PATCH_VERSION(현재 arcus zookeeper에서 추가한 패치 정보)를 조합하여 
ZOO_VERSION을 정의합니다.
> INTERNAL: Add zk_version to stats

- engine_testapp.c
- memcached.c
- mock_server.c
- stats.c
인자가 없는 함수에 인자로 void 키워드를 넣어야 제거되는 컴파일 워닝입니다.
MacOS 업데이트 이후 발견되어 수정합니다.
> FIX: Fix compile warning - a function declaration without a prototype is deprecated in all versions of C

- .gitignore
MacOS에서 Visual Studio Code로 작업 시 생성되는 불필요한 파일들을 gitignore에 추가했습니다.
> FIX: Remove unnecessary files from MacOS and Visual Studio Code.

- engines/default/prefix.c
- #652 
- jam2in/arcus-works#432
if문 괄호를 추가합니다.
> FIX: Add if block for misleading-indentation

- engines/default/coll_btree.c
- jam2in/arcus-works#432
```
25.83 engines/default/coll_btree.c:1587:20: error: 'upth[upp_depth].node' may be used uninitialized [-Werror=maybe-uninitialized]
25.83  1587 |             s_posi = upth[upp_depth];
25.83       |             ~~~~~~~^~~~~~~~~~~~~~~~~
25.83 engines/default/coll_btree.c:1576:30: note: 'upth' declared here
25.83  1576 |             btree_elem_posi  upth[BTREE_MAX_DEPTH]; /* upper node path */
25.83       |                              ^~~~
```
컴파일 Warning 해결을 위해 배열 생성 시 값을 초기화합니다.
> FIX: Initialize array with 0

- engines/default/coll_btree.c
- #676 
```
engines/default/coll_btree.c: In function 'do_btree_node_merge':
engines/default/coll_btree.c:1576:13: error: missing braces around initializer [-Werror=missing-braces]
btree_elem_posi  upth[BTREE_MAX_DEPTH] = { 0, }; /* upper node path */
^
engines/default/coll_btree.c:1576:13: error: (near initialization for 'upth[0]') [-Werror=missing-braces]
```
이전 PR 적용 후 생긴 Werror를 수정합니다.
> FIX: Add braces around initializer

- engines/default/assoc.c
- jam2in/arcus-works#432
`ENABLE_DTRACE` 상태에서만 사용되는 depth 변수 관련 line에 `#ifdef`를 적용합니다.
> Add ifdef for ENABLE_DTRACE

- memcached.c
UDP 프로토콜에서 유효하지 않은 데이터(멀티 패킷)에 대한 처리 로직을
이전 방식대로 READ_NO_DATA_RECEIVED를 반환하도록 변경.
out_string을 제거했습니다.
변경 이유는 현재 사용되지 않는 기능에서 발생한 에러 처리에 대하여
이후 활용될 때 해당 부분을 다시 논의하는 것이 좋으며, 우선적으로
오픈소스 memcached 에서 활용하는 방안을 따르고자 합니다. 
> 링크
https://github.com/memcached/memcached/blob/efee763c93249358ea5b3b42c7fd4e57e2599c30/memcached.c#L2415-L2418
- jam2in/arcus-works#439
- #681
> FIX: Bring back and modify an error handling logic in UDP

- configure.ac
- memcached.c
glibc 일정 버전 이상에서 컴파일되지 않는 문제를 수정합니다.
오픈소스 memcached 에서도 같은 이슈가 있었기에 동일한 방식으로 수정했습니다.
- memcached/memcached#707
- [```memcached/memcached/8e5148c```](https://github.com/memcached/memcached/commit/8e5148ca5c32fafca948e43c2e966db28a50a5f4)
> FIX: Use signal function instead of sigignore

- .github/workflows/CI.yml
GitHub action에 CI 테스트를 추가합니다.
관련 build 및 make test를 수행합니다.
환경의 경우 현재는 Arcus-java-client의 GitHub-action 환경과 유사하게 설정했습니다.
> INTERNAL: Add CI test

- config/version.pl
- jam2in/arcus-works#368
- #664 
- #689 
`git describe`에 실패하는 경우(tag 정보를 가져올 수 없는 경우) 실패하는 대신
`<latest release>-unknown` 버전을 사용하도록 변경합니다.
이 PR이 적용된 이후에는 매 릴리즈 마다 version.pl 파일을 함께 변경해 주어야 합니다.
> FIX: Revert version.pl about unknown version

- Dockerfile
- jam2in/arcus-docker#9
- jam2in/arcus-docker#19
- jam2in/arcus-works#447
[jam2in/arcus-docker의 Dockerfile](https://github.com/jam2in/arcus-docker/tree/develop/arcus-memcached)과 아래와 같은 차이가 있습니다.
- arcus-memcached를 clone받지 않고 copy해서 사용
- EE의 경우 private repo이기 때문에 clone 과정이 복잡한데, 이를 생략 가능
- commit하지 않은 로컬의 변경 사항이라도 docker image를 생성/테스트할 수 있음
- build-arg 및 label 사용
- 의존성 버전이나 configure option을 빌드 단계에서 수정 가능
예) `docker build --build-arg zookeeper_version="3.5.9-p2"`
- arg를 label로 추가하여, 빌드 결과물 이미지에서 어떤 설정에 의해 빌드되었는지 확인 가능하도록 구성
- `make install` 사용
- ~~기본 path인 `/usr/local`~~`/arcus` 하위에 설치
- 현재는 아래와 같이 make 후 관련 파일을 삭제하는 방식인데, 부자연스럽다고 생각
(소스코드를 제외한 doc 및 기타 파일들이 그대로 남아있게 되는 형태)
```dockerfile
RUN make
RUN rm -rf .git
RUN find . -type f \( -name "*.c" -or -name "*.o" \) -exec rm {} \;
```
- 기존 …
> INTERNAL: Add Dockerfile

- .dockerignore
- #691 
Docker image build 시 모든 파일을 복사하는 경우, 이전 빌드에서 생성된 object 파일 등이 함께 복사되는 문제가 있습니다.
이를 방지하기 위해 `.dockerignore` 파일을 추가합니다.
- `.dockerignore`는 `.gitignore`와 동일한 내용을 가질 것으로 생각하여,
두 파일이 함께 수정/관리되도록 symbolic link로 생성했습니다.
> INTERNAL: Add .dockerignore

- t/issue_67.t
해당 PR 작업 중 발견된 버그 사항을 분리합니다.
- #694
root 권한으로 make test 수행 중 67번 테스트가 실패하는 상황을 수정합니다.
> FIX: Make possible to test issue_67 even in root user

- configure.ac
- jam2in/arcus-works#448
libevent와 zookeeper 경로 탐색 시 prefix를 우선 확인하도록 합니다.
> FIX: Check dependencies in the prefix path before the default path

- .gitignore
- Makefile.am
- jam2in/arcus-works#457
- `make dist` 명령으로 생성되는 `arcus-memcached-<version>.tar.gz` 파일을 .gitignore에 추가합니다.
- `make dist` 명령으로 생성되는 tarball 파일에 rfc1321 폴더가 포함되도록 합니다.
> INTERNAL: Add rfc1321 to EXTRA_DIST and add dist tarball to .gitignore

- .github/workflows/CI.yml
- #696
의존성 설치에 install.sh를 사용하도록 CI 테스트를 변경합니다.
> TEST: Install dependency libraries by using an install.sh in CI test

- .gitignore
- deps/install.sh
install.sh 실행 시 상대경로를 받을 경우에도 정상적으로 구동할 수 있게끔 변경합니다.
상대경로의 경우 절대경로 변환 과정에서 해당 디렉토리가 존재하지 않을 시 실패하는
현상을 막기 위해 설치경로에 대하여 미리 디렉토리를 생성시켰습니다.
> FIX: Create an installation path and then convert to the absolute path

- Makefile.docker
- t/whitespace.t
- jam2in/arcus-docker#22
@uhm0311 의견에 따라 Makefile.docker를 추가합니다. 아래와 같이 사용할 수 있습니다.
```sh
make -f Makefile.docker                 # jam2in/arcus-memcached:develop
make -f Makefile.docker VERSION=1.13.4  # jam2in/arcus-memcached:1.13.4
```
- `memcached/memcached`
- [devtools](https://github.com/memcached/memcached/tree/master/devtools)에 dockerfile 위치
- repository root에 각 Dockerfile을 사용하는 [docker-compose](https://github.com/memcached/memcached/blob/master/docker-compose.yml) 위치(테스트 용도로 추측)
- 이미지 생성을 위한 별도의 스크립트나 Makefile은 없음
- `redis/redis`
- Dockerfile, docker image build 관련 파일 없음
> INTERNAL: Add Makefile.docker

- doc/ap01-arcus-telnet-interface.md
- doc/ch01-arcus-basic-concept.md
- doc/ch02-collection-items.md
- doc/ch03-item-attributes.md
- doc/ch04-command-key-value.md
- doc/ch05-command-list-collection.md
- doc/ch06-command-set-collection.md
- doc/ch07-command-map-collection.md
- doc/ch08-command-btree-collection.md
- doc/ch09-command-pipelining.md
- doc/ch10-command-item-attribute.md
- doc/ch12-command-administration.md
- doc/compilation_faq.md
- t/whitespace.t
- #697 
- `t/whitespace.t` 예외 대상에서 `doc/*.md`를 제외합니다.
(== 마크다운 문서를 whitespace 테스트 대상에 포함시킵니다.)
- 기존 문서를 whitespace 테스트에 통과하도록 변경합니다.
> DOC: Clean whitespace

- Dockerfile
- #696 
- 의존성 설치에 `deps/install.sh` 스크립트를 사용합니다.
- 최소한의 yum 패키지만 사용하도록 변경합니다.
- 소스 폴더 경로를 `/tmp`에서 `/src`로 변경했습니다.
- 이미지에 포함되는 LABEL을 제거했습니다.
> INTERNAL: Use deps/install.sh in Dockerfile

- doc/ch01-arcus-basic-concept.md
- doc/ch05-command-list-collection.md
- doc/ch06-command-set-collection.md
- doc/ch07-command-map-collection.md
- doc/ch08-command-btree-collection.md
- doc/ch11-command-scan.md
- doc/ch12-command-administration.md
- #697
- 링크로 연결되는 헤더에 한글을 포함하지 않도록 합니다.
- 동일 문서 내에서 이동하는 경우 파일명을 생략하도록 합니다.
- 기존 `[List collection 생성: lop create](ch05-command-list-collection.md#lop-create-list-collection-생성)`
- 변경 `[List collection 생성: lop create](#lop-create)`
gitbook에서는 문서 내에서 이동할 수 있는 헤더 별 링크를 기본 제공해 주는데,
마크다운에서 직접 작성해 두는 것이 크게 의미가 없지 않은가 하는 생각도 듭니다.
> DOC: Use English headers for stable links

- arcus_zk.c
- arcus_zk.h
- memcached.c
- jam2in/arcus-operator#49
- `arcus_zk_stats` 구조체에 `bool zk_znode_created` 필드를 추가합니다.
- `stats zookeeper` 결과에 `zk_znode_created`를 추가합니다.
- `ready` 명령을 추가합니다. 응답은 `READY` 또는 `NOT_READY` 입니다.
해당 서버가 외부로부터 요청을 받아 처리할 수 있는 상태인지 확인합니다.
- `--enable-zk-integration` flag 없이 컴파일 => 항상 `READY`
- `--enable-zk-integration` flag 포함하여 컴파일
- `arcus_zk_cfg`가 NULL인 경우(`-z` option 없이 구동된 경우) `READY`
- cache_list znode 생성 여부에 따라 `READY` 또는 `NOT_READY`
arcus_zk.c의 `azk_stat`은 현재 사용되지 않는 변수인 것 같습니다.
https://github.com/naver/arcus-memcached/blob/399c36896cdcf578a12accc0d9b94426c3485049/arcus_zk.c#L198-L199
> FEATURE: Add ready command

- README.md
`readme.md`에 memcached build에 필요한 의존성 패키지 및 라이브러리 설치 방식에 대한 내용을 추가했습니다.
libevent와 zookeeper의 경우 install.sh를 사용한 방식으로 소개했습니다.
패키지 설치의 경우 해당 패키지가 모두 필요한지에 대해서는 검토가 필요한 것 같습니다.
> DOC: Add texts for dependencies installation

- Makefile.am
- jam2in/arcus-works#457
압축파일이 libevent와 zookeeper 및 설치 스크립트를 포함하도록 변경합니다.
> INTERNAL: Add dependencies to dist file

- Dockerfile
arcus-operator에서 startupProbe로 활용하기 위한 nc 명령어를 도커 이미지에 추가합니다.
> INTERNAL: Add nc command to docker image to use ready command on startup.

- t/whitespace.t
- jam2in/arcus-memcached-EE#1088
최상위 경로의 모든 Makefile을 whitespace test에서 제외하도록 합니다.
현재 EE에서 테스트 실패하는 상태입니다.
> TEST: Exclude all Makefiles from whitespace test

- memcached.c
bop mget/smget 명령의 `..._ntokens` 관련 변수를 의미에 맞게 정리합니다.
- read_ntokens: 앞부분 처리된 token 개수 (== 다음에 처리해야 할 token idx)
- post_ntokens: 뒷부분 처리된 token 개수
- rest_ntokens: 아직 처리되지 않은 token 개수
> CLEANUP: Fix rest_ntokens calculation on bop mget/smget

- engine_loader.c
- engines/default/default_engine.c
- engines/demo/demo_engine.c
- jam2in/arcus-works#450
core 버전과 default_engine.so 버전이 서로 다른 경우 구동에 실패하도록 합니다.
실패 시 아래와 같은 메시지 출력됩니다.
```
memcached: engines/default/default_engine.c:1941: create_instance: Assertion `__extension__ ({ size_t __s1_len, __s2_len; (__builtin_constant_p (api->core->server_version()) && __builtin_constant_p ("1.13.4-53") && (__s1_len = strlen (api->core->server_version()), __s2_len = strlen ("1.13.4-53"), (!((size_t)(const void *)((api->core->server_version()) + 1) - (size_t)(const void *)(api->core->server_version()) == 1) || __s1_len >= 4) && (!((size_t)(const void *)(("1.13.4-53") + 1) - (size_t)(const void *)("1.13.4-53") == 1) || __s2_len >= 4)) ? __builtin_strcmp (api->core->server_version(), "1.13.4-53") : (__builtin_constant_p (api->core->server_version()) && ((size_t)(const void …
```
> INTERNAL: Compare core version and engine version when create_instance()

- memcached.c
- jam2in/arcus-works#472
- jam2in/arcus-works#474
new smget interface에서 offset을 허용하지 않도록 합니다.
- `offset`과 `duplicate|unique`를 함께 지정하는 경우에 `CLIENT_ERROR bad command line format`를 반환합니다.
```
bop smget <lenkeys> <numkeys> <bkey or "bkey range"> <offset> <count> <duplicate|unique>\r\n
```
위와 같은 구조의 명령이 현재는 동작하지만, PR 적용 이후 에러를 반환하게 됩니다.
- new smget에서 offset을 사용하는 테스트 코드를 제거합니다.
기존 코드의 조건문에 `#ifdef`를 끼워넣는 것은 복잡하고 잘 읽히지 않을 것 같아서
코드 중복을 감수하고 별도의 if-else 형태로 분리했습니다. 더 나은 구현 방안이 있다면 반영하겠습니다.
> FIX: Update max ntokens for bop smget(new) with offset

- Dockerfile
docker image build 과정에서 deps/install.sh 실패하는 경우,
`deps/install.sh`의 출력에는 에러 원인이 나타나지 않고 빌드 결과물도 남지 않으므로 `deps/install.log`를 확인하는 것도 어렵습니다.
실패 시 로그의 마지막 부분을 출력하여 빌드 실패 원인 파악에 도움이 되도록 합니다.
> INTERNAL: Show log when deps/install.sh fails

- Dockerfile
@oliviarla 
docker image에 아무 옵션도 설정하지 않았을 때 Dockerfile의 CMD에 의해 추가되는 구동 옵션이
캐시 서버에 아무 옵션도 설정하지 않고 구동했을 때의 default 설정값과 서로 달라 혼란을 야기합니다.
따라서 docker image의 기본 옵션을 제거합니다.
> INTERNAL: Remove CMD on Dockerfile

- ChangeLog
- config/version.pl
1.13.5 버전 릴리즈를 위한 변경을 적용합니다.
- ChangeLog 변경
- 형식 변경
- whitespace 제거
- 1.13.5 변경 내용 추가
- version.pl 변경
릴리즈 노트에서 마크다운 문법이 적용되면 아래와 같이 보여지게 됩니다.
> version 1.13.5

- util.c
- jam2in/arcus-works#475
문자열을 32bit 정수 자료형 변환 과정이 3단계(`string` -> `long(64bit)` -> `int(32bit)`)로 이루어짐으로써
overflow 발생 시 undefined value로 변환되는 현상을 수정합니다.
해당 현상 발생시 return false를 하도록 수정했습니다.
> INTERNAL: Prevent overflow when convert string to 32bit int

- config/version.pl
- jam2in/arcus-memcached-EE#1092
`git describe` 명령을 통해 버전 정보를 얻어오는 데 실패한 경우 사용할 버전 문자열을 별도의 변수로 분리합니다.
> CLEANUP: Use default_version variable in version.pl

- memcached.c
memcached 의 몇몇 구동옵션에서 허용되지 않는 수(음수)를 줄 수 있는 현상을 수정 또는 관련 로그 메시지를 수정합니다.
추가적으로 Memory Limit(maxbytes)옵션인 -m 옵션에서 0을 허용하고 있어,
slabs 모듈 확인 결과 할당 과정에서 아래의 로직을 확인할 수 있었습니다.
```c
if ((slabsp->mem_limit && slabsp->mem_malloced + len > slabsp->mem_limit && p->slabs >= p->rsvd_slabs) ||
(grow_slab_list(id) == 0) ||
((ptr = memory_allocate((size_t)len)) == 0)) {
MEMCACHED_SLABS_SLABCLASS_ALLOCATE_FAILED(id);
return 0;
}
```
mem_limit(maxbytes)를 0으로 설정한 경우는 메모리에 대한 제한을 두지 않기 위한 용도인가요?
> INTERNAL: Fix the invalid allowable range of run options

- docs/ascii-protocol/ch08-command-btree-collection.md
- jam2in/arcus-works#472
bop smget 문서를 정리합니다.
https://github.com/namsic/arcus-memcached/blob/works%23472/doc-smget/docs/ascii-protocol/ch08-command-btree-collection.md#bop-smget
- old 인터페이스 관련 내용 제거
- 구조 및 표현 전반적으로 재작성
> DOC: Cleanup doc smget documentation

- docs/ascii-protocol/ch01-arcus-basic-concept.md
- cb455c2
Small Memory 에 관한 내용을 최신에 맞추어 문서를 수정합니다.
1.10.0 버전 이후로 maximum small memory slot size가 8000Byte에서 48KB로 변경되었습니다.
> DOC: Fix the maximum size of small memory slot

- memcached.c
- jam2in/arcus-works#500
Binary 프로토콜에서 활용되는 `h/einfo_set_ascii_tail_string` 의 함수명을 변경합니다.
(set 을 append로 변경)
- `h/einfo_set_ascii_tail_string` → `h/einfo_append_ascii_tail_string`
> CLEANUP: Change the name of functions 'h/einfo_set_ascii_tail_string'

- arcus_zk.c
- jam2in/arcus-works#504
- znode watcher에서 session event 발생한 경우 별도의 로그 기록하지 않도록 변경합니다.
(global watcher인 `arcus_zk_watcher()`에서 처리하기 때문)
- session event 중 state가 connected가 아닌 경우 update flag를 설정하지 않습니다.
- reconfig watcher의 경우 event type이나 state 등을 확인하지 않고 path만 비교하여 로그를 남겼었는데,
cache_list watcher와 동일한 형태를 가지도록 변경했습니다.
> INTERNAL: Set the update flag only when ZOO_CONNECTED_STATE

- memcached.c
> I keep putting off a major refactor on the (nearly 11 year old in its current state) frontend code. Now that my internal fiddling is starting to slow down it was worth a shot at some low hanging fruit. When doing the ascii response inlining work I noticed add_iov() taking up a lot of CPU. When reviewing my old notes and the original patch from Steven Grimm it's clear that the pipeline was optimized for (2006-era) UDP traffic. All the extra wrapped code ended up causing a lot of extra work for TCP sockets.
> - memcached/memcached#243
> - [312ae0d](https://github.com/memcached/memcached/pull/243/commits/312ae0d2382f970b556b64bc63a383f83954ab2d)
TCP 프로토콜에서 첫 payload에 대하여 msghdr를 나누었던 구현을 수정합니다.
memcached에서 반영되었던 commit을 그대로 복사했습니다.
> INTERNAL: Reduce add_iov() work for TCP connections

- t/topkeys.t
Topkey 테스트에서 환경변수가 이미 설정되어 있을 시 실패하던 문제를 수정합니다.
> TEST: Unset an environment variable for topkeys

- mc_util.c
- mc_util.h
- memcached.c
- memcached.h
- jam2in/arcus-works#442
- jam2in/arcus-works#497
- #688
- #701 
기존 내용은 노션 및 이슈에 정리되었으므로 지웠습니다.
event callbacks 함수를 `mc_util` 파일로 이동시킵니다.
> CLEANUP: Move event callback functions to mc_util files

- memcached.c
- jam2in/arcus-works#510
get_item_info 실패 시 설정 에러를 ENOMEM으로 통일합니다.
> FIX: Modify mismatched error types when get_item_info failed

- memcached.c
- jam2in/arcus-works#519
- `sigterm_handler()`에서 flag 직접 설정하는 대신 `shutdown_server()` 호출하도록 합니다.
- `shutdown_server()` 함수 위치가 `sigterm_handler()` 상단으로 이동됩니다.
- 종료 전 대기 로직이 추가되는 경우, signal 수신 시의 동작이 flag만 설정하는 지금보다는 복잡해지게 될 것입니다.
이에 대한 사전 PR의 성격을 띄고 있습니다.
- zk 연결 종료
- shutdown 예약
- 꼭 위 이슈의 구현 방안과 연관짓지 않더라도, shutdown api 호출과 signal 수신 모두
graceful shutdown 수행해야 할 것이므로 하나의 구현을 공유하는 것이 나쁠 것 없다고 판단했습니다.
> CLEANUP: Call shutdown_server() in sigterm_handler()

- t/udp.t
UDP 프로토콜 테스트에서 long key에 대한 response 메시지 구성 시
패킷이 분배되어 UDP 헤더 인덱스가 1 이상으로 증가하는 경우에 대한 테스트를 추가합니다.
UDP 프로토콜 사용시 `UDP_MAX_PAYLOAD`(1400 Byte)를 초과하는
Response 메시지를 구성할 경우 `UDP_MAX_PAYLOAD` 크기로 나눈 다음
UDP 헤더를 구성하여 송신합니다.
현재 존재하는 udp 테스트에서는 `UDP_MAX_PAYLOAD`를 초과하여 Response 메시지를 구성하는 경우에 대한 테스트가 존재하지 않으므로,
이후 이루어질 udp 헤더에 대한 좀더 정학한 테스트를 위해 추가했습니다.
테스트 개수가 9개가 증가한 이유
- `"abcd" x 1024` 에 대한 Response 메시지(대략 4096 Byte)를 구성하므로 `UDP_MAX_PAYLOAD`(1400 Byte) 기준으로 3개의 Packet으로 나누어져 전송하게 되며, 각각의 패킷에 대하여 총 3번의 valid 검사를 수행합니다.
- udp 테스트는 ASCII, Binary 프로토콜에 대해 각각 수행하므로 3x2번 총 6번의 Packet valid 테스트가 수행됩니다.
- get 테스트의 경우 ASCII에서는 1번의 테스트, Binary에서는 exist status 검사 및 Value에 대한 테스트 총 2번의 테스트가 수행됩니다.
- 3 x 2 + (2 + 1) = 9번의 테스트가 수행됩니다.
> TEST: Add a distributed packet test about long key in UDP

- memcached.c
- memcached.h
- jam2in/arcus-works#509
- UDP 헤더 구성 방식을 리팩토링합니다.
- malloc을 통해 가변 길이를 가졌던 UDP 헤더를 8Byte로 고정 후 공유하여 활용합니다.
- Packet 크기로 분할된 Response 메시지를 각각 보내기 전에 UDP헤더를 구성합니다.
> CLEANUP: Refactor the method of building UDP headers

- memcached.c
- jam2in/arcus-works#533
- 사용되지 않는 명령어 `bget`을 제거합니다.
> INTERNAL: Remove an unused command 'bget'

- memcached.c
- jam2in/arcus-works#530
- Binary 프로토콜에서 Value Length가 `INT_MAX`를 초과하지 않도록 제한을 추가합니다.
> INTERNAL: Limit a value length from exceeding INT_MAX in binary protocol

- arcus_zk.c
- arcus_zk.h
- memcached.c
- jam2in/arcus-works#519
- jam2in/arcus-works#536
- `arcus_zk_shutdown` flag를 `static`으로 변경합니다.
- zk_final, hb_final 시점을 앞당깁니다.
- 기존: main thread event loop 종료 후
- 변경: shutdown api 호출 시점
- `arcus_zk_final()` 함수 안에서 `arcus_zk_shutdown` 값을 변경합니다.
- 기존: sm thread 종료(`arcus_zk_shutdown = 1`)와 zk 연결 종료(`arcus_zk_final()`)를 구분
변경: `arcus_zk_final()` 호출하면 두 동작을 이어서 수행
> INTERNAL: Do not extern arcus_zk_shutdown

- memcached.c
- jam2in/arcus-works#519
`shutdown`명령을 추가합니다. 명령 추가 후 캐시 서버의 종료 동작은 크게 3가지로 구분됩니다.
- shutdown api 호출(SIGNAL, hb fail, …)
- 즉시 종료 로직을 수행합니다. (기존 종료 로직과 동일)
- `shutdown`
- main event loop를 종료한 후 최대 2초간 대기합니다.
- 클라이언트 연결 수가 일정 시간(200ms) 감소하지 않으면 2초까지 대기하지 않고 즉시 종료합니다.
- `shutdown <seconds>`
- main event loop를 종료한 후 주어진 시간만큼 대기합니다.
- 클라이언트 연결 수가 감소하지 않아도 고정 시간만큼 대기한 뒤 종료합니다.
종료 동작은 가장 마지막에 호출된 함수 기준으로 동작합니다.
- `shutdown 30` 수행하여 종료 예약된 상태에서 SIGTERM 수신하는 경우 즉시 종료
- `shutdown 30` 수행하고 20초 뒤 `shutdown 60` 명령 수행하면,
두 번째 `shutdown` 명령 수신 시점으로부터 60초 대기 후 종료
> FEATURE: Add shutdown command

- arcus_zk.c
- arcus_zk.h
- memcached.c
- jam2in/arcus-works#551
- zk_integrated 판별을 memcached.c 가 아닌 arcus_zk 모듈을 통해 가능하게 끔 변경합니다.
- `-z` 옵션이 주어진 경우
```
zkensemble get
0.0.0.0:50000 
```
- `-z` 옵션이 주어지지 않은 경우
```
zkensemble get
ERROR not using ZooKeeper
```
- mc_pause 상태
```
zk connection closed by mc_pause.
Failed to get the ZooKeeper ensemble list. Invalid ZK handle.
zkensemble get
ERROR failed to get the ensemble address
zkensemble rejoin
Successfully rejoined
```
> INTERNAL: Add an arcus_zk_initalized function

- cmdlog.c
- cmdlog.h
- memcached.c
- jam2in/arcus-works#526
- cmdlog_in_use 변수를 cmdlog 모듈로 이동합니다. 
- 간단하게 이동만 시켰습니다.
- 이외에도 내부에 두고 API로 노출시키는 방향도 있습니다.
> INTERNAL: Move a cmdlog_in_use variable

- cmdlog.c
- memcached.c
- 컴파일 과정에서 발생한 에러를 수정합니다.
- 불필요한 cmdlog 조건문을 제거합니다.
> INTERNAL: Fix a sprintf error and remove a needless condition

- docs/ascii-protocol/ch12-command-administration.md
- memcached.c
- #755 
- https://github.com/jam2in/arcus-operator/issues/49#issuecomment-2102129933
> 그러면, ready 명령이 더 이상 사용되지 않겠네요.
(2개 commit입니다.)
- `ready` command를 md 문서에서 제거하고 `help admin` 응답에 추가합니다.
- `shutdown` command를 `help admin` 응답에 추가합니다.
> DOC: Add ready, shutdown command to help

- docs/ascii-protocol/ch01-arcus-basic-concept.md
- docs/ascii-protocol/ch02-collection-items.md
- docs/ascii-protocol/ch03-item-attributes.md
- docs/ascii-protocol/ch04-command-key-value.md
- docs/ascii-protocol/ch05-command-list-collection.md
- docs/ascii-protocol/ch06-command-set-collection.md
- docs/ascii-protocol/ch08-command-btree-collection.md
- docs/ascii-protocol/ch09-command-pipelining.md
- Btree 문서 내 이상한 글자를 수정합니다.
- `bop update` 의 ASCII 프로토콜 예시에서 data가 없어도 되는 것처럼 표현된 것을 수정했습니다.
- `bop mget` 의 ASCII 프로토콜 예시에서 큰따옴표 대신 굽은 따옴표로 쓰여 있는 것을 수정했습니다.
> DOC: Fix odd letters

- Dockerfile
- 현재 memcached에 익숙하지 않은 사용자가 docker image를 사용하고자 할 때, 11211 port가 노출됨을 파악하기가 어렵습니다.
- Dockerfile에 `EXPOSE` port를 추가하여 port 정보를 노출합니다.
- `EXPOSE`는 그 자체로 아무런 동작도 하지 않으며, 11211 port를 사용하고 있음을 알리는 역할을 합니다.
> https://docs.docker.com/reference/dockerfile/#expose
> The EXPOSE instruction informs Docker that the container listens on the specified network ports at runtime.
>
> The EXPOSE instruction doesn't actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published.
- 부가 기능으로 구동 시 `-P` option을 사용하면 사용자가 port를 명시적으로 연결하지 않아도
아래와 같이 host의 임의 port로 exepose port를 매핑하는 형태로 구동할 수 있습니다.
```
docker run -P jam2in/arcus-memcached -v
```
```
CONTAINER ID   IMAGE …
```
> INTERNAL: Add `EXPOSE` to Dockerfile

- cmdlog.c
- engines/default/cmdlogrec.c
- engines/default/items.c
- engines/default/prefix.c
- memcached.c
- jam2in/arcus-works#562
- cppchecker analyzer 에서 감지한 케이스 중 하나를 수정합니다.
- string format 내 형식과 변수 타입이 일치하도록 변경했습니다.
ex) `"%u", (int)a` → `"%d", (int)a`
> INTERNAL: Fix unmatched string formats

- memcached.c
- jam2in/arcus-works#562
- clang static analyzer 에서 감지한 케이스 중 하나를 수정합니다.
- getpeername 이 항상 주소값이 들어감을 보장해주지 않습니다.
```
memcached.c:732:38: warning: Passed-by-value struct argument contains uninitialized data (e.g., field: 's_addr') [core.CallAndMessage]
snprintf(c->client_ip, 16, "%s", inet_ntoa(addr.sin_addr));
```
```
memcached.c:13620:20: warning: Passed-by-value struct argument contains uninitialized data (e.g., field: 's_addr') [core.CallAndMessage]
if (strcmp(inet_ntoa(sin->sin_addr), ADMIN_CLIENT_IP) != 0 ||
```
- conn_new 에서는 memset을 통해 addr 변수를 초기화했습니다.
- 아래와 같이 처리했으나 여전히 warning이 발생하여 memset을 사용했습니다.
```c
if (getpeername(c->sfd, (struct sockaddr*)&addr, &addrlen) != 0) {
/* Fail Handler */
} else {
snprintf(c->client_ip, 16, "%s", inet_ntoa(addr.sin_addr));
}
- conn_listening에서는 …
```
> INTERNAL: Fix a clang static analyzer issue about getpeername failure

- engines/default/coll_map.c
- engines/default/coll_map.h
- engines/default/default_engine.c
- engines/demo/demo_engine.c
- include/memcached/engine.h
- include/memcached/types.h
- memcached.c
- t/coll_mop_upsert.t
- t/tlist/engine_default_b.txt
- t/tlist/engine_default_s.txt
- jam2in/arcus-works#578
- Mop Upsert 명령어를 추가합니다.
- Btree의 Upsert와 유사한 방식으로 추가했습니다.
- `mop upsert`의 경우, `mop insert` 로직을 공유합니다.
- 엔진 인터페이스의 `map_elem_insert`에서 replace 관련 플래그를 추가합니다.
```diff
ENGINE_ERROR_CODE (*map_elem_insert)(ENGINE_HANDLE* handle,
const void* cookie,
const void* key,
const int nkey,
eitem *eitem,
+                                    const bool replace_if_exist,
item_attr *attrp,
+                                    bool *replaced,
bool *created,
uint16_t vbucket);
```
- `replace_if_exist` : insert 시 해당 elem이 이미 존재한 경우 replace할 지 여부
- `replaced` : replace가 발생한 경우 해당 변수가 true로 설정됨
- 이 변수가 true이면, 사용자에게 `REPLACED`를 출력 
- 간단한 사용 결과는 아래와 같습니다. 
```
mop insert m 0 1 create 0 0 10
1
CREATED_STORED
mop insert m 0 1
2
ELEMENT_EXISTS
mop get m 1 1
0
VALUE 0 1
0 1 1
END
mop …
```
> FEATURE: Add an upsert command for map structure

- engines/default/coll_btree.c
- #772
- btree insert 과정에서 replaced 변수의 초기화 위치를 변경합니다.
> INTERNAL: Move a 'replaced' initialization in btree insert

- Dockerfile
- https://github.com/jam2in/arcus-works/issues/583
- Dockerfile 내의 Deprecated 항목들을 수정합니다.
> INTERNAL: Fix deprecated items, `centos:7` to `rockylinux:8` and `ENV key value` to `ENV key=value`, in Dockerfile.

- docs/ascii-protocol/ch08-command-btree-collection.md
docker-compose로 캐시 클러스터 구성하여
아래의 `bop insert`를 getrim 옵션 주어 실행시키면
END 가 아닌 TRIMMED 가 응답으로 나옵니다.
문서가 잘못된 건지 구현이 잘못된건지 확인 부탁드립니다.
PR은 문서가 잘못되었다고 가정하고 작성되었습니다.
> DOC: Fix response string when trimmed result in bop insert.

- docs/ascii-protocol/ch04-command-key-value.md
- memcached.c
- `SERVER ERROR` 대신 `SERVER_ERROR`를 사용합니다.
> FIX: Do not use space in SERVER_ERROR status

- lqdetect.c
- lqdetect.h
- memcached.c
- memcached.h
- https://github.com/jam2in/arcus-works/issues/554
- 기존 `<value, length>` 구조의 배열을 리턴하는 로직에서 간단하게 `filed_t` 하나만을 반환하는 로직으로 변경하였습니다.
- 기존의 char * 를 구조체에 담는 방식에서 실제 출력 하는 문자열을 이어붙여 만들어서 리턴하도록 함수를 변경하였습니다.
- 문자열을 이어붙이기 위한 공간을 할당하기 전에 이어붙일 문자열의 길이를 측정하여 이에 맞는 공간 만큼만 할당하도록 합니다.
- 이때 길이를 측정할 때 header 는 기존과 같이 최대 길이를 32 라고 두고 초기화 하였습니다.
- body 는 lqdetect 에 `total_offset` 을 선언하여 buffer 의 offset 이 증가할때 같이 증가하여 이를 활용했습니다. 
- 실패 할 경우의 message 는 `SERVER ERROR out of memory writing show response.` 를 출력하도록 하였습니다.
- lq->result 를 삭제함으로서 lq_release 삭제했습니다.
> INTERNAL: Refactor lqdetect show

- lqdetect.c
- lqdetect.h
- memcached.c
- memcached.h
- 헤더파일 단독으로 컴파일이 가능하도록 변경
- `lqdetect.h`의 include 위치를 `memcached.h` 에서 `memcached.c`로 변경하였습니다.
> CLEANUP: Refactor includes

- cmdlog.c
- cmdlog.h
- memcached.c
- memcached.h
- [google style guide](https://google.github.io/styleguide/cppguide.html) 에 맞춰 include 순서 변경
- `cmdlog.h`의 위치를 `memcached.h`에서 `memcached.c`로 옮김
- 헤더파일 단독으로 컴파일이 가능하도록 변경
- 꼭 필요한 파일만 include 하도록 변경
> CLEANUP: Refactor cmdlog include

- doc/protocol.txt
- docs/ascii-protocol/ch12-command-administration.md
- sasl_defs.c
- t/binary-sasl.t.in
- t/stats.t
- https://github.com/naver/arcus-memcached/commit/849f9f201f257a45357c541f5dd34b3c35a90330
- `auth_cmds` stat 기준으로 작성되어 있던 문서와 테스트를 `cmd_auth`로 변경합니다.
- auth_cmds라는 stat이 없는 상태이기 때문에 sasl 사용 시 바이너리 테스트 실패하고 있었습니다.
- sasl_callback_t의 proc 필드에 함수 전달 시 타입 캐스팅 추가합니다.
- 아래 Werror로 빌드 실패하는 문제를 해결합니다.
```
sasl_defs.c:148:4: error: initialization from incompatible pointer type [-Werror]
{ SASL_CB_LOG, sasl_log, NULL },
^
sasl_defs.c:148:4: error: (near initialization for ‘sasl_callbacks[0].proc’) [-Werror]
```
> Fix binary protocol for sasl

- lqdetect.c
- t/long_query_detect_issue.t
- 이미 접근한 키에 대해서 전체에 접근하는 연산 (ex: `sop get arcus 0`)을 나중에 실행시키면 lqdetect show 에서 빠지는 버그를 수정하였습니다.
> FIX: Fix do_command_dupcheck method that didn't show 0 at same key

- lqdetect.c
- key 를 만드는 로직과 키를 이어붙이는 부분을 간소화 시켰습니다.
- https://github.com/jam2in/arcus-works/issues/627 
위 이슈에 맞추어 입력 가능한 버퍼의 공간 보다 큰 입력이 들어왔을때에 처리를 포함하였습니다.
- key를 입력하기 전에 offset 이 length 를 넘을 경우 이후에 snprintf 에 0을 넘겨 써지지 못하도록 하였습니다.
- 마지막 까지 다 썻을때 offset이 전체 주어진 길이보다 크면 offset을 length - 1 로 옮기고 해당 자리에 줄바꿈 \n을 삽입하여 다음 명령을 받을 준비 합니다.
> INTERNAL: do_lqdetect_write method simple

- docs/ascii-protocol/ch12-command-administration.md
-
- lqdetect threshold 지정시 default threshold로 지정되는 경우를 추가하였습니다.
> DOC: Add case which set default threshold

- cluster_config.c
- https://github.com/jam2in/arcus-works/issues/627#issuecomment-2456241826
- 현재 snprintf의 반환값을 그대로 쓰여진 문자열의 길이로 간주하여 해싱을 하는데 사용하고 있습니다.
- 이에 snprintf의 반환값이 실제로 쓰여진 문자열의 길이보다 클 경우 해싱 도중에 잘못된 주소를 참조할 수 도 있고, 원하는데로 해싱이 이루어지지 않을 우려가 있습니다.
- 따라서 버퍼의 크기를 node_name을 지을 수 있는 최장 길이로 설정하여 위의 예외들을 피하고자 합니다.
> FIX: Fix node_name buffer size

- memcached.c
- memcached.h
- t/binary-sasl.t.in
- conn 구조체에 authenticated flag를 추가합니다.
- https://github.com/memcached/memcached/commit/87c1cf0f20be20608d3becf854e9cf0910f4ad32 와 동일한 변경입니다.
> It was previously possible to bypass authentication due to implicit state management.
Now we explicitly consider ourselves unauthenticated on any new connections and authentication attempts.
> INTERNAL: Add authenticated flag to conn struct

- configure.ac
- jam2in/arcus-works#590
- 기존 코드에서는 clock_gettime 사용을 위해 librt에서 확인을 수행했지만, 링킹 옵션인 `-lrt`는 따로 지정되지 않았습니다.
- 확인 후 `-lrt`옵션을 주도록 추가하도록 변경합니다.
> INTERNAL: Remove the check for clock_gettime function

- memcached.c
- memcached.h
- 사용자(클라이언트)는 `sasl auth` 명령을 통해 인증 방식과 초기 데이터를 전달하고,
그 이후에는 `sasl step` 명령을 통해 challenge와 response를 주고받게 됩니다.
- 그런데 `sasl auth`를 수행하지 않고 `sasl step` 명령을 전송하는 경우,
서버에서 `sasl_server_step()` 함수를 호출하면서 segfault 발생하게 됩니다.
- `c->sasl_started` flag를 추가하여 문제를 해결합니다.
https://github.com/memcached/memcached/commit/ced9e1730cb6bb3beece9b22e7bd5cb2d05ed2c8 구현을 참고하였습니다.
> FIX: Prevent calling `sasl_server_step()` before `sasl_server_start()`

- memcached.c
- jam2in/arcus-works#305
- `stats prefixes`, `stats detail` 명령에서 인자 개수를 확인하여 불필요한 추가 인자가 있는 경우 에러를 반환하도록 합니다.
> INTERNAL: Check ntokens in the prefix related stats command

- docs/ascii-protocol/ch02-collection-items.md
- docs/ascii-protocol/ch08-command-btree-collection.md
- engines/default/cmdlogrec.c
- engines/default/cmdlogrec.h
- engines/default/coll_btree.c
- include/memcached/protocol_binary.h
- include/memcached/types.h
- memcached.c
- t/coll_bop_eflag.t
- t/long_query_detect_issue.t
- naver/arcus-c-client#328
- eflag 관련 용어를 변경합니다.
- fwhere => offset (일부 구조체에서 offset 변수가 이미 존재하여 f_offset 이라는 이름을 사용했습니다.)
- operand => bitwvalue
- fvalue => compvalue(eflag_filter), value(eflag_update)
> INTERNAL: Modify the term related to eflag

- docs/ascii-protocol/ch12-command-administration.md
- https://github.com/jam2in/arcus-works/issues/633#issuecomment-2469703742
- exptime의 표현을 수정하였습니다.
잔여 만료 시간
-> item이 생성된 curtime과 만료 시간을 더한 값
> DOC: Fix cachedump exptime comment

- memcached.c
- memcached.h
- sasl_defs.c
- `memcached.h`에서 `sasl_defs.h`를 include하는 대신, sasl API를 사용하는 각 소스 파일에서 include하도록 변경합니다.
> INTERNAL: Do not include `sasl_defs.h` in `memcached.h`

- engines/default/coll_map.c
- engines/default/coll_set.c
- Set와 Map에서의 get 명령 DFS 탐색 순서를 변경했습니다.
- 기존 방법: 모든 해시 테이블을 우선 탐색한 뒤 element 체인을 탐색
- 변경 방법: 해시 테이블의 인덱스 순서에 따라 탐색
> INTERNAL: Change DFS traverse order in set and map

- engines/default/coll_set.c
- engines/default/item_base.h
- Set에서 `tot_elem_cnt`를 해당 노드의 subtree에 포함된 모든 element의 총 개수로 변경
- 기존에는 현재 노드의 element 개수만 의미했으나, subtree 전체를 포함하도록 수정하였습니다.
- `tot_elem_cnt` 크기 확장
- 기존 `uint16_t` 에서 `uint32_t`로 변경
- Set의 최대 element 개수(1,000,000개)를 표현하기 위해서입니다.
- `tot_elem_cnt` 변수 관리
- Element Insert (`do_set_elem_link()`)
- Parent 노드들과 현재 노드의 `tot_elem_cnt`를 1 증가
- Element Delete (`do_set_elem_traverse_dfs()`, `do_set_elem_traverse_delete()`)
- DFS 탐색하면서 `tot_elem_cnt`를 1 감소
- Chain -> Hash table 변경 (`do_set_node_link()`)
- Parent 노드의 `tot_elem_cnt` 유지
- Child 노드의 `tot_elem_cnt` = 기존 Chain element 개수 (num_found)
- Hash table -> Chain (`do_set_node_unlink()`)
- Parent 노드의 `tot_elem_cnt` 유지
- Child 노드의 `tot_elem_cnt` = 0
- offset 내부 구현 PR
- random 구현 PR (parsing, 내부)
> INTERNAL: Change tot_elem_cnt to include subtree element count in set

- README.md
- naver/arcus-c-client#343
- 줄바꿈 대신에 Markdown의 리스트를 활용합니다.
> DOC: Use a list instead of line breaks

- engines/default/coll_map.c
- engines/default/item_base.h
- Map에서 `tot_elem/hash_cnt` 의 변수명을 `cur_elem/hash_cnt`로 변경합니다.
- Set에서 `tot_elem_cnt`의 변수명의 의미가 달라지면서 Map에서의 변수명과 헷갈릴 여지가 있기 때문에 변경합니다.
> INTERNAL: Change variable name in map

- memcached.c
- t/binary-sasl.t.in
- jam2in/arcus-works#634
`-S` option을 ascii protocol과 함께 사용할 수 있도록 확장합니다.
ascii protocol에서 SASL 인증 수행할 방법이 없는 상태이므로,
`-S` 옵션 사용 시 ascii conn에서는 허용된 명령만 사용할 수 있습니다.
1. 기존에는 `-S` option을 설정하면 binary protocol으로 고정되고,
`-B` option에서 `auto`나 `ascii`를 명시한 상태에서 `-S` 함께 지정하면 구동 실패합니다.
2. 변경 후에는 `-S` option을 설정하더라도 ascii protocol을 사용할 수 있습니다.
3. `-S` option을 설정하여 구동한 경우에 ascii protocol 사용하는 연결은
허용되지 않은 명령에 대해 `CLIENT_ERROR unauthenticated` 응답합니다.
> INTERNAL: Make the -S option available with ascii protocol

- docs/ascii-protocol/ch12-command-administration.md
- engines/default/default_engine.c
- engines/default/prefix.c
- include/memcached/engine.h
- memcached.c
- memcached.h
- t/flush-prefix.t
- https://github.com/jam2in/arcus-works/issues/625
- 서버 자체적으로 prefixes 수가 많은 경우, prefix 관련 stat 정보 제공 기능을 제한하기 위해 `max_stats_prefixes` 설정값을 추가했습니다.
- `max_stats_prefixes` 설정값을 추가했습니다.
- Default: 50, Min: 0, Max: UINT32_MAX
- 변경 방법:
- 명령어: `config max_stats_prefixes [<value>]`
- `help admin` 명령어를 통해서 확인할 수 있습니다.
- 변경 로직은 `scrub_count` config 관련해서 참고했습니다.
- `stats prefixes` 명령어 제한 (Item)
- 서버의 Prefix 수가 설정값보다 많은 경우, 로그를 남기고 동작을 차단합니다.
- `Too many prefixes. Operation blocked.`
- `stats detail dump` 명령어 제한 (Operation)
- operation 관련 stats를 출력할 때 엔진을 거치지 않기 떄문에 logger 대신 printf를 통해 에러 메시지를 출력하고 동작을 차단합니다.
- `Too many prefixes. Operation blocked.`
- Test file 변경
- flush-prefix.t에서 기존에 Prefix를 1000개 추가하던 로직을 50개로 변경해, 새 설정값에 맞춰 테스트가 작동하도록 수정했습니다.
- 서버 내의 Prefix 개수에는 NULL prefix도 포함해서 동작을 제한합니다. …
> INTERNAL: Add max_stats_prefixes limit to stats prefix command

- engines/default/coll_set.c
- engines/demo/dm_items.c
- https://github.com/jam2in/arcus-works/issues/682
- `do_set_elem_delete_fast()` 함수와  `do_set_elem_traverse_fast()` 함수를 삭제했습니다.
- Set 구현에서 SET_DELETE_NO_MERGE 관련 최적화를 통한 성능 향상 결과가 미미하기 때문입니다.
> CLEANUP: Remove do_set_elem_delete_fast() functions

- engines/default/coll_set.c
- engines/default/default_engine.c
- Hash table을 이용해서 Set에서 get 동작을 random get으로 변경했습니다.
1. 해시 테이블 관리
- coll_set.h
- hash table 구조체 정의
- coll_set.c 
- init, insert, free, next_prime 함수 구현
2. `do_set_elem_traverse_dfs` 함수 수정
- 랜덤 offset에 위치한 element를 가져오기 위해 offset을 이용한 탐색 기능
3. `do_set_elem_get` 함수 수정
- 케이스 분류
- 전체 요소 가져오는 경우
- 가져오면서 삭제 진행하는 경우 (`get count delete`)
- hash table을 이용하는 경우
4. default_engine.c 수정
- srand() 추가
- 크기: `count` * 1.3 이상의 소수
- 버킷: 한 버킷에 최대 3개 key insert 가능
- 해당 버킷이 가득 찼을 때 Insert 하면 다시 랜덤 offset 선택
- Key: rand_offset
- Index: rand_offset % (크기)
- 기존 함수에서 offset 파라미터를 추가해서 지정된 offset 전까지의 요소들을 건너뜁니다.
- node 단위에서도 건너뛰고 element chain 단위로도 건너뜁니다.
- node 단위
- offset이 마지막 element index 보다 크면 continue, 그렇지 않으면 해당 node 탐색
- element chain 단위
- offset이 마지막 …
> INTERNAL: Change get to random get in set using hash table

- engines/default/coll_set.c
- Set의 random get 동작에서 selection sampling 방법을 추가했습니다.
- `do_set_elem_traverse_sampling()`
- Set 전체 크기의 10% 이하의 크기를 요청하면 hash table 방법을 이용합니다.
- Set 전체 크기의 10% 초과의 크기를 요청하면 sampling 방법을 이용합니다.
- count개의 element를 모두 선택한 뒤 shuffle 합니다.
- 요소를 만났을 때 선택 확률 = `(남은 필요 요소 개수) / (남은 탐색 요소 개수)`
```
총 10개에서 3개를 요청하는 상황에서 0~9 Index를 탐색하면서 선택합니다.
- 0번 index에서 뽑을 확률 = 3/10
- 1번 index에서 뽑을 확률
- 0번 index에서 뽑았을 때,     현재 뽑을 확률 = 2/9
- 0번 index에서 뽑지 않았을 때, 현재 뽑을 확률 = 3/9
...
3개를 다 뽑게 되면 바로 종료합니다.
```
> INTERNAL: Add sampling method to random get in set

- docs/ascii-protocol/ch06-command-set-collection.md
- memcached.c
- memcached.h
- t/coll_sop_unittest.t
- jam2in/arcus-works#571
`sop get` 연산에서 일부 element 조회 시 가능한 개수를 1000개로 제한합니다.
처음에는 core(memcached.c)에서 1000개 이하로 조회 개수를 제한하고 에러 메시지를 반환했으나,
이 경우, count가 1000을 초과하는 set에 대해 *전체 조회*가 불가능했습니다.
그래서 현재 PR은 count 정보를 가진 엔진에서 제한을 적용하고 있습니다.
> INTERNAL: Limit the count of elems get from set structure

- t/issue_arcus_655.t
- t/tlist/engine_default_b.txt
- t/tlist/engine_default_s.txt
- #655
- jam2in/arcus-works#357 
- 관련 이슈에서 발생한 segfault 문제에 대한 unit test를 추가합니다.
> TEST: Add test for issue #655

- ChangeLog
- jam2in/arcus-works#708
- Changelog 형식을 수정합니다.
> DOC: Update Changelog format

- engines/default/prefix.c
- jam2in/arcus-works#704
- NESTED_PREFIX 전처리기에 의해 제외되는 변수임에도 제외되지 못한 부분을 수정합니다.
- `int ret = 0;` 처리는 unused variable 때문입니다.
- 현재 arcus-memcached 버전에서 NESTED_PREFIX를 제외하고 컴파일할 경우 아래의 에러가 발생합니다.
```js
engines/default/prefix.c:556:17: error: no member named 'items_count_inclusive' in 'struct _prefix_t'; did you mean 'items_count_exclusive'?
pt->items_count_inclusive[ITEM_TYPE_KV],
^~~~~~~~~~~~~~~~~~~~~
items_count_exclusive
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
__builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
```
> INTERNAL: Preprocess nested prefix variables

- ChangeLog
- jam2in/arcus-works#472
- jam2in/arcus-works#703
- ChangeLog에 unstable version 관련 내용을 추가합니다.
> DOCS: Set unstable version to ChangeLog

- docs/ascii-protocol/ch06-command-set-collection.md
- docs/ascii-protocol/ch12-command-administration.md
- memcached.c
- t/flush-prefix.t
- #710 
- 클라이언트가 인식하지 못하는 `DENIED` 응답을 `CLIENT_ERROR` 응답으로 변경합니다.
- 이후 `INVALID` 응답으로 변경할 때 구분하기 쉽도록, message에 `invalid:` prefix를 임시로 추가해두었습니다.
> CLEANUP: Revert `DENIED` to `CLIENT_ERROR`

- memcached.c
- jam2in/arcus-works#710
- mop 명령어 중 swallow 처리가 필요한 명령어에 swallow 핸들링을 추가했습니다.
- mop get
- mop delete
- mget, bop mget, bop smget 등에는 이미 swallow 로직이 적용되어 있었으나, mop 명령어에는 빠져 있어 이를 보완했습니다.
> INTERNAL: Add a swallow handler for mop

- memcached.c
- #835 
- https://github.com/naver/arcus-memcached/commit/2626bcbb2bc7cb26ade075dd908b3223dcaebabe#r160371701
- lenfields, numfields 검사 로직을 리팩토링합니다.
> INTERNAL: Refactor the len/numfields validation logic

- ChangeLog
- config/version.pl
> version 1.14.1

- memcached.c
- memcached.h
- sasl_defs.c
- #843 
- #814
- conn 구조체에 sasl 인증 요청 시 사용할 필드를 추가합니다.
- `char sasl_mech[MAX_SASL_MECH_LEN+1]`
- `int sasl_auth_data_len`
- `char *sasl_auth_data`
- 이에 따라 필요하지 않게 된 sasl_tmp 구조체를 제거하고, 관련 구현을 수정합니다.
- memcached.h에서 `MAX_SASL_MECH_LEN` 사용하기 위해, sasl_defs.h를 memcached.h에서 include하도록 이전 변경사항을 revert 합니다.
> INTERNAL: Add sasl related fields to `conn` and remove `sasl_tmp`

- memcached.c
- memcached.h
- jam2in/arcus-works#634
- 인증 과정을 수행하는 `sasl auth` 명령을 추가합니다.
명령/응답 예시는 아래와 같습니다.
```
sasl auth SCRAM-SHA-256 70\r\n
n,a=testUser@arcus,n=testUser@arcus,r=KDGgMvgWKAesWV+XW1y+qzRAA7bxd2Ys\r\n
SASL_CONTINUE 100\r\n
r=KDGgMvgWKAesWV+XW1y+qzRAA7bxd2YsqKTQDjxlGg6PC+hnyzLJuZSHlf+z873C,s=qO/j4RQBJRttoagRvrwQkg==,i=4096\r\n
```
```
sasl auth 144\r\n
c=bixhPXRlc3RVc2VyQGFyY3VzLA==,r=KDGgMvgWKAesWV+XW1y+qzRAA7bxd2YsqKTQDjxlGg6PC+hnyzLJuZSHlf+z873C,p=M/TOzndLJnRD60+VicZSzmEFQ8u8v65nb3m0Czzzx7o=\r\n
SASL_CONTINUE 46\r\n
v=HoGV6rivvLX6zT+ktkcCnPxNLAlLGHiCvDLPRwla1tI=\r\n
```
```
sasl auth 0\r\n
\r\n
SASL_OK\r\n
```
> FEATURE: Add sasl auth command

- isasl.c
- isasl.h
- memcached.c
- sasl_defs.c
- sasl_defs.h
- shutdown 과정에서 `shutdown_sasl()` 호출하도록 합니다.
- `isasl.c`에서 `shutdown_sasl()`을 직접 구현하는 대신, `sasl_done()`을 구현하도록 합니다.
- `sasl_defs.c`에서 `sasl_done()`을 호출하는 `shutdown_sasl()`을 구현합니다.
> CLEANUP: Call shutdown_sasl() in shutdown process

- Makefile.am
- configure.ac
- sasl_defs.h
-
- `--with-sasl` 플래그를 통해 SASL 경로를 지정할 수 있도록 했습니다.
- 구현 방식은 arcus-zookeeper와 최대한 유사하게 맞췄습니다.
- SASL 버전에 따라 `-lsasl2` 또는 `-lsasl`로 링크해야 하므로, `AC_SEARCH_LIBS` 매크로를 사용해 `sasl2`, `sasl` 순으로 탐색한 뒤, 사용 가능한 라이브러리를 링크하도록 했습니다.
- 탐색에 성공한 경우, 해당 라이브러리 링크 옵션(`-lsasl2` 또는 `-lsasl`)을 `LINK_SASL` 변수에 저장하고, 이를 `Makefile.am`에 전달해 빌드 시 사용할 수 있도록 했습니다.
- `--with-sasl` 옵션이 지정된 상태에서 SASL 라이브러리를 찾지 못하면 빌드가 실패합니다.
- 단순히 `sasl/sasl.h`의 존재 여부를 확인하는 `AC_CHECK_HEADERS_ONCE`에서는 SASL을 제외했고,
그에 따라 코드 내 `HAVE_SASL_SASL_H` 관련 부분도 필요없다고 판단하여 모두 제거했습니다.
> INTERNAL: Add support for specifying SASL path

- ascii_scrub.c
- include/memcached/types.h
- memcached.c
- memcached.h
- sasl_auxprop.c
- sasl_auxprop.h
- sasl_defs.c
- jam2in/arcus-works#748
SASL 권한 부여 기능 추가를 위한 PR입니다.
이번 PR에서는 최종적으로 구현하고자 하는 구조를 먼저 공유드리기 위해, 전체적인 틀을 포함한 초기 구현을 올렸습니다.
리뷰를 위해 구조 위주로 확인 부탁드립니다.
- 권한 플래그는 types.h에 `AUTHZ_{}` 형태로 정의하였습니다.
- 기본값은 AUTHZ_ALL로 설정했습니다.
- 이는 권한 부여 기능을 사용하지 않을 경우, 모든 권한을 가진 상태로 동작하도록 하기 위함입니다.
- 기본적으로 전체 권한을 부여한 뒤, 권한 기능이 활성화된 경우에 한해 권한을 제한하는 방식이 구현 측면에서 간결하다고 판단했습니다.
- 권한 플래그 정의를 `sasl_defs.h`가 아닌 `types.h`에 위치시킨 이유는, 권한 기능이 memcached.c 뿐 아니라 향후 extension을 통해 추가되는 ASCII 명령어 등에도 적용될 수 있기 때문입니다.
- auth_data_t 구조체에 권한 정보를 포함하도록 아래와 같이 수정했습니다.
```diff
typedef struct {
const char *username;
const char *config;
+  const uint16_t *authz_flag;
} auth_data_t;
```
- 이를 통해 memcached.c 뿐만 아니라 extension에서도 get_auth_data API를 통해 현재 커넥션의 사용자 권한 정보를 조회할 수 있습니다.
- 인증 성공 시 권한 플래그를 설정하는 방식은 ON_AUTH 이벤트에 대응하는 콜백 함수인 …
> INTERNAL: Add command authorization support

- include/memcached/types.h
- memcached.c
- sasl_defs.c
- #864 
- `kv` role 없이 collection role만 가진 경우 `delete` 명령 수행할 수 없던 문제를 수정합니다.
- 이를 위해 `delete` 명령 수행을 위한 `AUTHZ_DELETE` 플래그를 분리합니다.
> CLEANUP: Add `AUTHZ_DELETE` to auth_flag

- sasl_defs.c
- #871 
- default auxprop plugin(== sasldb) 사용하는 경우에 인증에 성공했음에도 권한이 없는(`AUTHZ_NONE`) 문제를 수정합니다.
> CLEANUP: Add `default_sasl_authz()` callback on auth

- sasl_defs.c
-
- sasl_callback_ft 대신 해당 타입을 직접 정의하여 사용하도록 변경합니다.
- 일부 컴파일 환경(MacOS)에서 sasl_callback_ft 타입을 찾지 못하고 아래와 같은 에러가 발생합니다.
```js
sasl_defs.c:213:28: error: use of undeclared identifier 'sasl_callback_ft'
213 |    { SASL_CB_GETCONFPATH, (sasl_callback_ft)sasl_getconf, NULL },
|                            ^
1 error generated.
```
> INTERNAL: Fix the undeclared sasl_getconf error
